Flow-Launcher/Flow.Launcher

- Flow.Launcher.Infrastructure/StringMatcher.cs
- Flow.Launcher.Test/FuzzyMatcherTest.cs
Problem context:
Previously search results such as searching 'code' for 'Visual Studio Codes' does not make the regular precision cut as it does not get the bonus, where as both 'cod' and 'codes' do make the cut.
Solution:
Less than 5 chars scoring is 10 per char, else onward 5 per char
> Fix substring scoring

- Plugins/Flow.Launcher.Plugin.Program/Settings.cs
Remove default loading of .bat extension files, less clutter in program list. User can still add it if they choose to.
> Remove default loading of .bat extension files

- Plugins/Flow.Launcher.Plugin.Folder/ContextMenuLoader.cs
Current folder delete function in Folder plugin does not delete folders that contain files. 
Fix by adding true to recursive delete
> Folder plugin- Recursive delete sub folders and files

- Flow.Launcher.Core/Plugin/PluginInstaller.cs
- Flow.Launcher.Plugin/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
- Plugins/Flow.Launcher.Plugin.PluginManagement/Main.cs
- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Replace `IPublicAPI.RestarApp` with `IPublicAPI.RestartApp` and mark `IPublicAPI.RestarApp` obsolete.
> fix typo in IPublicAPI

- Flow.Launcher.Core/Plugin/PluginsLoader.cs
- Flow.Launcher.Plugin/AllowedLanguage.cs
- Flow.Launcher.sln
- Plugins/HelloWorldFSharp/HelloWorldFSharp.fsproj
- Plugins/HelloWorldFSharp/Main.fs
- Plugins/HelloWorldFSharp/plugin.json
It is trivial to write plugins in F# for Wox already, and I have written a few in the past ([example](https://github.com/JohnTheGr8/Wox.Plugin.Bang)). The only trick was to specify `csharp` in the plugin.json file.
This PR:
* adds F# to the supported languages in `PluginsLoader`
* adds `fsharp` as a supported value of the `Language` field in `plugin.json`
* adds a sample hello-world plugin project written in F#
Cheers
> Add support for F# plugins

- Flow.Launcher/Flow.Launcher.csproj
The translation files from `Flow.Launcher/Languages` are currently not included in the build output and are therefore not available at runtime. 
Changing the language from settings only affects the plugin-specific fields in the `Plugin` tab, because the plugin projects are copying their language files correctly.
> Fix translations for the main project

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
This should fix the `Symbols package publishing failed.` error when uploading the .snupkg file to nuget.
> Create a portable pdb file in release builds of Flow.Launcher.Plugin

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- appveyor.yml
This PR solves the issue we had with publishing symbols to nuget: `The checksum does not match for the dll(s) and corresponding pdb(s).`
After a bit of digging, I figured out that the problem was caused by Fody. Switching the PDB format to embedded solves this issue.
I have also:
* enabled deterministic builds for the plugin project in AppVeyor
* removed the `FodyWeavers.xml` file from the plugin project's nupkg
* removed `SolutionAssemblyInfo.cs` from the plugin project, which was causing the plugin dll to have the wrong `AssemblyFileVersion`, `AssemblyFileVersion` and `AssemblyInformationalVersion` in CI builds
Opening the nupkg file with NugetPackageExplorer verifies that SourceLink is valid now and the URLs are correctly embedded:
I have also decompiled the dll with dotPeek and …
> Plugin enhancements

- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Web Search should not activate if query is a directory/network path
Before:
After:
> Exclude directory/network path for Web Search plugin

- Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
- Flow.Launcher.Infrastructure/FodyWeavers.xml
- Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml.cs
- Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml
- Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml.cs
Fixed various options from the settings form requiring a restart to take effect - fixed by adding Fody to the Infrastructure project.
Examples of options that now work without requiring a reload:
- `General` > `Maximum results shown`
- `Hotkey` > `Custom query hotkey` > `Add`, `Edit`
- update `set browser path` text boxes
* remove text wrapping
* allow manual editing, so that values like `chrome` or `firefox.exe` etc are also accepted.
- remove `success` message boxes (from custom query
> Various UI fixes and enhancements

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/Bookmarks.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/EdgeBookmarks.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
Load Edge (Chromium) bookmarks
Todo:
Allow user to specify which browser's bookmarks to load
Closing #75
> Add chromium Edge bookmark loading

- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Fix missing result list preview in the Theme tab
> Fix missing result list preview in Theme tab

- Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Ensure paths resolved from environment variables are absolute paths. Examples of fixed searches include `%homepath%`, `%homedrive%` and `%systemdrive%`.
fixes #139
> plugin/explorer: ensure environment variable paths are absolute

- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
In the URI make up, the '#' symbol is the syntax to indicate the fragment part of the URI:
We replace the symbol with the encoded syntax %23 so it is escaped and LocalPath property returns the full path.
Note:
the LocalPath property returns the unescaped localised path of a directory. I have not found a good replacement.
Closing https://github.com/Flow-Launcher/Flow.Launcher/issues/142
> Fix missing fragment portion of the file path

- Flow.Launcher.Core/Configuration/Portable.cs
- Flow.Launcher.Core/Updater.cs
- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
Copy => CopyAll - more descriptive
FileExits=> FileExists
> Update Flow.Launcher.Plugin method name typos

- Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
Sort plugin ProcessKiller's results ascending
> Sort plugin ProcessKiller's results ascending

- Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
1. do not show a "kill all instances" item in the context-menu listing of "kill all X processes"
2. make the "kill all X processes" result item a bit nicer
Before:
After:
3. hide the "kill all X processes" option when the associated executable path is empty
Before:
After:
> plugin/ProcessKiller: enhancements to the kill-all functionality

- Flow.Launcher/App.xaml.cs
Fixes #163
Fix Encoding error of "GB2312" due to .net core problem by adding the injection.
> Fix Encoding Error

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Bookmark.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/Bookmarks.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/EdgeBookmarks.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
1. Add Edge Dev Bookmark to the cache list
2. Use the fuzzy search score as the result score
> Bookmark Plugin fix

- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
- Plugins/Flow.Launcher.Plugin.Program/Settings.cs
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
Link to #193 
This is only for program plugin for now.
> Add Exploere Customization

- global.json
This PR fixes the recent build failures we have seen. 
I have pinned the .NET Core SDK version to `3.1.xxx` with a minimum of `3.1.201`. I think this is reasonable...
check [this link](https://www.appveyor.com/updates/2020/11/14/) for details
> add global.json to pin SDK version

- Flow.Launcher.Core/Resource/Theme.cs
- Flow.Launcher.Infrastructure/Constant.cs
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
Link to #201 
Add a quick link to access user theme folder.
If anyone would like to make it looks better, feel free to do it!
> Add quicklink to customized theme folder

- Plugins/Flow.Launcher.Plugin.Program/Logger/ProgramLogger.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
> Fix unauthorize exception lead to the whole directory unable to index.

- Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
- Flow.Launcher/ReportWindow.xaml.cs
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
#203 Use the Default Browsers in the computer instead of simply using chrome as default.
> Use default system browser

- Flow.Launcher.Infrastructure/Image/ImageCache.cs
- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/ViewModel/ResultViewModel.cs
This PR cherry pick some of the commit in #195 related to the flickering fix.
1. Use customized Async Image load instead of the one provided by WPF.
2. Create Lazy Async class for doing 1.
Closing https://github.com/Flow-Launcher/Flow.Launcher/issues/42
> Fix image flickering

- Flow.Launcher.Infrastructure/Image/ImageCache.cs
Allow MissingImgIcon and DefaultIcon to be removed from image cache.
If these two's usage is high, keeping it as original behaviour, but if low, shouldn't have any impact if removed from image cache as their usage drops.
Enhancements to #221 & #195
> Allow MissingImgIcon and DefaultIcon to be removed from image cache

- Flow.Launcher.Core/Resource/Internationalization.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/MainWindow.xaml.cs
> fix tray menu translation

- Flow.Launcher.Infrastructure/PinyinAlphabet.cs
> Add space for pinyin translation

- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Directly restart flow without another prompt after plugin install/uninstall. This helps make the experience more seamless
> Plugin installation and uninstallation restart without prompt

- Scripts/post_build.ps1
JsonRPC folder is deleted as part of the work in #225, remove this copy command from postbuild script
> Remove post build script target of JsonRPC folder copy

- Flow.Launcher/Languages/sk.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
- Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
- Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
- Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
- Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
- Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
- Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
- Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
- Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
- Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
Some plugin translation files are not included in the output folder, and are therefore missing at runtime. I have switched all plugin projects to use a wildcard for including all xaml files in the `Languages` folder, so that this doesn't happen again... (it has happened before for the main project, see #48)
Closes #258 
I have also fixed a minor issue with the Slovak translation.
> Include all plugin translation files as content

- Flow.Launcher/Flow.Launcher.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
- Plugins/Flow.Launcher.Plugin.ControlPanel/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Bump all plugins' version for #259 
- Use wildcard to include images
> Use wildcard to include images

- Flow.Launcher/ViewModel/MainViewModel.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Scripts/post_build.ps1
- Fix wrong error message for PluginsManager
- Added try catch for install plugin call
- Added try catch for querying plugin and plugins tasks
- Fixed postbuild script to remove duplicate with the condition that the versions are the same. Specific to issue 256, the direct  package reference (ICSharpCode.SharpZipLib 1.2.0) used by PluginsManager has a different version to the output of other packages' ICSharpCode.SharpZipLib (0.86) dependency.
Closing #256
> Fix error handling in PluginsManager and plugins query, fixed postbuild script duplicate deletion during build

- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Add ability to manual reload the plugins manifest
> Add ability to manual reload PluginsManifest data

- Flow.Launcher/ViewModel/ResultViewModel.cs
Since most of the image will be stored on cache, so synchronous action will be done quite significant for SetImage method in ResultViewModel, using ValueTask instead of Task can avoid those cost.
> Use ValueTask instead of Task

- Flow.Launcher/Flow.Launcher.csproj
- Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
- Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
- Scripts/post_build.ps1
- appveyor.yml
This is the continuation of the work done in #35 back in May.
The `post_build.ps1` script has been repurposed to be called from `AppVeyor` to create a self-contained version of the project. Squirrel artifacts are deployed to Github as a draft release, which means the only manual work for a release is to edit the draft release with release notes and press `Publish`.
Note that I have removed `post_build.ps1` as a post-build script of the main project because the script calls `dotnet publish` which has to build the main project again, and that would result in a build loop. I have also bumped `PropertyChanged.Fody` to `3.3.1` (which made this entire PR possible, see #248) and added `SatelliteResourceLanguages` to some plugin projects to reduce the output files.
- merging into master will …
> Create and deploy releases from CI

- Flow.Launcher/Flow.Launcher.csproj
The `mainsearch.svg` file is not being copied to the output folder, causing a "file not found" exception on start-up.
This one flew under the radar when #278 was merged and I re-based from #275 to resolve the merge conflict (admittedly, without testing). We used to copy all contents of `Flow.Launcher\Images` to the output folder from the post-build script but that [was removed](https://github.com/Flow-Launcher/Flow.Launcher/pull/275/files#diff-59a3ced9b3067f709e8217b1c76003031953426af6108db3390348574ae9da8aL38), so we need to copy the SVG file from the csproj.
> fix: copy svg images to output from the main project

- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
- Flow.Launcher/Storage/TopMostRecord.cs
- Flow.Launcher/Storage/UserSelectedRecord.cs
fix TopMostRecord and UserSelectedRecord due to System.Text.Json cannot parse private field in version 3.1 
#253
> fix TopMostRecord and UserSelectedRecord

- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Allow Flow to be used without internet connection, or else it will wait a long time to startup during plugin initialization for downloading plugin manifest since we don't assign an timeout for Http.Get.
> Plugin manager init timeout

- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
fix pm initialisation error message not working due to main window not initialised yet
ran into the init error message several times during debug sessions, so increase delay
> fix error message not working + increase delay

- Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
- Flow.Launcher.Test/Plugins/ExplorerTest.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
fix #308 
The reason is `IsLocationPathString(string)` unable to recongnize `D:\>*` as location string, so that it treat it as a file search.
> Fix unrecognized path

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
#128 
https://github.com/Wox-launcher/Wox/pull/3246
Co-Authored-By: imsh <9258159+imsh@users.noreply.github.com>
> Stop ProgressBar animation when Flow is hidden

- Flow.Launcher.Core/Updater.cs
- Flow.Launcher/CustomQueryHotkeySetting.xaml
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Plugins/Flow.Launcher.Plugin.Url/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Url/SettingsControl.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
fix #305 
I fix most of them except for these two, which I am not sure how to add translated string to them.
> Fix untranslated string

- Flow.Launcher.Infrastructure/Http/Http.cs
- Flow.Launcher/App.xaml.cs
This PR should make connections follow the proxy in the settings correctly.
> Fix Http Proxy

- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Fix move method call only restricted to within the same drive
Closing #323
> Fix move method call only restricted to within the same drive

- Flow.Launcher.Core/Plugin/JsonPRCModel.cs
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
> Fix python plugin Json Desterilize issue

- Flow.Launcher/PublicAPIInstance.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
fix #265 
TODO: 
create an interface for cleaning up plugin information if they store setting or some data.
> Remove setting after uninstalling plugin

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/Msg.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- README.md
Press F5 in query window to reload all plugin data
> Press F5 in query window to reload all plugin data

- Flow.Launcher.Plugin/Interfaces/ISavable.cs
TODO: an async version for this interface?
> move ISavable to Flow.Launcher.Plugin\Interfaces

- Flow.Launcher.Infrastructure/Http/Http.cs
For stream reading and copy, we don't need to wait until the body finish and then start processing them.
According to some internet resource, this can help reduce the use of memory for storing the temp stream, and improve speed (no wait before processing).
> Use HttpCompletionOption.ResponseHeadersRead

- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
- Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
- Flow.Launcher.Plugin/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
> Expand PluginAPI with Log and JsonStorage

- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultsForUpdate.cs
- Flow.Launcher/ViewModel/ResultsViewModel.cs
I just heard that there is a new, faster, lower cost Channel class for doing the producer-consumer logic we want. Therefore, no need to include the TPL because it is much heavier, and we didn't use other feature of TPL.
Channel class use ValueTask instead of Task, IAsyncEnumerable instead of creating another IList when reading them all.
Although we should only have a few items in the queue (generally less than 20), reading is quite frequently.
It won't be a large difference, because we didn't include async read & write, but more than nothing.
> Use Channel instead of BufferBlock

- Flow.Launcher.Core/Plugin/ExecutablePlugin.cs
- Flow.Launcher.Core/Plugin/JsonPRCModel.cs
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Flow.Launcher.Core/Plugin/PythonPlugin.cs
Question:
1. why not use json serialize method in ToString method in JSONRPCModel.
2. whether we want an async version of action?
3. async version for context menu?
> JSONRPC Async Model

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
fix #345 
The cancellation process is done by HttpClient natively by throwing TaskCancelledException, so no need to check the Stream length for that.
Seems that throwing exceptions makes the programs runs really slow in debug mode? Not quite sure for that.
> Remove unused check for Stream length

- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
> don't remove setting when updating

- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
When result exists from both Quick Access and file search, use unionwith and custom comparer instead of append, so this will return distinct results of duplicates
> Remove duplicate entry

- Flow.Launcher.Core/Updater.cs
fix #357
This may because HttpClient throws TaskCanceledException when timeout instead of HttpException, which is previously thrown by the old HttpWebRequest.
> add taskcanceledexception to updater exception catch

- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
> filter description existence before passing it to distinct & separate user selected result from hashing

- Flow.Launcher.Core/Flow.Launcher.Core.csproj
- Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Flow.Launcher.Test/Flow.Launcher.Test.csproj
- Flow.Launcher/Flow.Launcher.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
- Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
- Plugins/Flow.Launcher.Plugin.ControlPanel/Flow.Launcher.Plugin.ControlPanel.csproj
- Plugins/Flow.Launcher.Plugin.PluginIndicator/Flow.Launcher.Plugin.PluginIndicator.csproj
- Plugins/Flow.Launcher.Plugin.ProcessKiller/Flow.Launcher.Plugin.ProcessKiller.csproj
- Plugins/Flow.Launcher.Plugin.Program/Flow.Launcher.Plugin.Program.csproj
- Plugins/Flow.Launcher.Plugin.Shell/Flow.Launcher.Plugin.Shell.csproj
- Plugins/Flow.Launcher.Plugin.Sys/Flow.Launcher.Plugin.Sys.csproj
- Plugins/Flow.Launcher.Plugin.Url/Flow.Launcher.Plugin.Url.csproj
- Plugins/Flow.Launcher.Plugin.WebSearch/Flow.Launcher.Plugin.WebSearch.csproj
This allows generating the new PDB format (which is smaller cross-platform, although we don't need that feature), and it allows us to debug with vscode.
Since we are on .net core 3.1, or higher in the future, this should not have negative impact on Flow.
https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md
> Use PortablePDB instead of Full pdb for debugging

- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/setting.json
1. Since web searches is performed many times, let's change the default to global action keyword so first time users do not need to go hunting in settings to find out the action keyword to activate it.
2. Update so if a action keyword is matched, display on top of global action keyword ('*') 
before:
after: 
suggestions also follow the same format.
> Change WebSearch default to global

- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Realised Google Scholar action keyword is missing- 'sc', this adds it back in.
> Fix missing google scholar action keyword

- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
> Add Open Log Location command to sys plugin

- README.md
I made a table with all the plugins listed as compatible on https://github.com/Flow-Launcher/Flow.Launcher/issues/170  ... the plugin names would need to be verified in terms of being able to use them to install correctly but since there doesn't seem to be anywhere else in the docs that this lives i thought it might be a good addition.
> Added Plugins section with curently compatible plugins

- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
> Stop await indexing when indexing is required and cache exist

- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
'Index Search Excluded' path does not kick in when using Windows Index to search for files and folders. This adds an exclusion call to filter out the index search result from exclusion list.
closing #384
> Fix exclusion of Windows Index search for files and folders

- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
- Add ConfigureWait and cancellation token for https://github.com/Flow-Launcher/Flow.Launcher/pull/386
- Remove unnecessary catching of OperationCanceledException because it will be caught by PluginManager from each plugin query call
> Add ConfigureWait and cancellation token & remove unnecessary OperationCanceledException

- Flow.Launcher.Core/Plugin/PluginConfig.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
A few enhancement I found during the investigation of #371
> Optimize startup

- Flow.Launcher.Infrastructure/Constant.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Add documentation link in About to the usage tips section
> Add documentation link

- Flow.Launcher.Plugin/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
Keep align with the usage of JsonStorage that use an instance holding the data to load and save instead of creating a new one every time. It uses dynamic to fit the generic type, but I also see someone use a generic type with static class to achieve similar result, but that will change quite significantly.
#388
> Make PluginJsonStorage in IPublicAPI become single instance per type

- Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Core/Plugin/PluginsLoader.cs
- Flow.Launcher.Plugin/IAsyncPlugin.cs
- Flow.Launcher.Plugin/IPlugin.cs
- Flow.Launcher.Plugin/PluginPair.cs
The currently separated interface create quite significant code duplicate, so I try making the old plugin interface extends from the new plugin interface with the default implementation of interface from c# 8. (This is similar to the first version of the new Async model which directly use the default implementation in IPlugin interface).
It is hard to say which choice is better🤔🤔🤔, but this prevents the weird empty default implementation in legacy Query method.
> Make IPlugin inherit from IAsyncPlugin

- Flow.Launcher/Storage/UserSelectedRecord.cs
Only bump score when not only the result has been matched, but also the query has been match.
This will help users to separate the use of query for different high score results that both can be matched with separated query.
close #394
> add score bumping with query and do hashcode customized

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Plugins/Flow.Launcher.Plugin.Shell/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
- Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml
- Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Added saving executed cmds to settings
- Added option to show 5, 10, 20 most used cmds in settings
close #403, #405
> save Shell plugin cmd history

- Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Use `Contains` instead of `StartWith` to allows search with middle part of name, also score bump to 100 since it is not a fuzzy, but a full matched.
Or using Fuzzy would be better?
> Allow Quick Access Links to be accessed with middle string

- Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
> Fix concurrent access issue

- Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/AccessLink.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Remove the brackets in folder name display from this:
To:
> Remove redundant QuickAccess folder nickname path

- Flow.Launcher.Plugin/Result.cs
Fix issue revealed from #398 :
Since we are allowing optionally setting subtitle, fix by providing a default value.
> Dev branch: Fix optional subtitle

- Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
Add tips and UserData location commands for Sys plugin
close #414
> Add tips and UserData location commands for Sys plugin

- Flow.Launcher.Plugin/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Add API error msg method to display message with Flow's standard error icon. This fixes the Explorer's confusing error message which shows with default Flow icon.
> Add API error msg method

- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
- Flow.Launcher/Storage/UserSelectedRecord.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
following on from https://github.com/Flow-Launcher/Flow.Launcher/pull/398
close #402
> Bring Legacy records together

- Flow.Launcher/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Hello, I updated the Chinese translation
> Added and corrected Chinese translation

- Plugins/Flow.Launcher.Plugin.PluginIndicator/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Problem:
The Plugin Indicator's result should not continue if user continues typing, otherwise when hitting enter would go to the github action keyword instead of google search git tips:
Solution:
Only activates Plugin Indicator if the query has only one word/term:
> fix Plugin Indicator when more than one query term is typed

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
- Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
- Flow.Launcher.Plugin/IPublicAPI.cs
- Flow.Launcher.Plugin/Interfaces/ISavable.cs
- Flow.Launcher/PublicAPIInstance.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
- Plugins/Flow.Launcher.Plugin.Calculator/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/Main.cs
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
> Use API call to save instead of direct call

- Flow.Launcher/PublicAPIInstance.cs
My bad, obviously we need to use ConcurrentDictionary for PublicAPIInstance because it will be accessed concurrently.
> Dev branch: Use ConcurrentDictionary to replace Dictionary

- Flow.Launcher.Infrastructure/UserSettings/PluginSettings.cs
- Flow.Launcher/ViewModel/PluginViewModel.cs
- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
Web Searches plugin allows users to fully delete all search setting entries, resulting in a scenario where there could be empty action keyword. Current code when flow starts up and there are no action keywords present for the plugin, it switches to populating the action keywords from metadata (plugin.json). 
For Web Searches plugin, this causes a mismatch between the flow's setting plugin action keywords data (has action keywords because repopulated from metadata) and the action keywords in Web Searches plugin's own setting (has no action keywords because all deleted).
close #432 
also added tool tips to make functionality clearer
> Fix loading when no action keywords present for a plugin in user plugin setting

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
When a plugin has multiple global action keywords, flow loops through the plugin's global (*) and action keywords and fire them off to query. This creates a scenario where a plugin with multiple global action keywords (*), for example 4, running the plugin search 4 times unnecessarily. This also could potentially have a performance cost to it.
This fix excludes adding multiple duplicate global and action keywords even if the plugin has 4 global action keywords, only fire search once.
> fix duplicate query searches from same global action keywords

- Flow.Launcher.Core/Plugin/JsonPRCModel.cs
It seems that System.Text.Json won't parse base class property? Add property name fix that. This change fix the broken python plugin callback.
#459 
Do we want a hotfix for that (though we don't have much python plugin)?
> Fix unparsed property

- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
fix a bug that setting hasn't been initialized but was accessed
> change sequence of loading for shell plugin to avoid null reference

- Flow.Launcher.Core/Plugin/JsonPRCModel.cs
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Flow.Launcher.Core/Plugin/PythonPlugin.cs
Related to Later discussion in #461
> Use JsonLibrary to Parse object, and replace ProcessStartInfo.Arguments with ArgumentList

- Flow.Launcher.Core/Plugin/JsonPRCModel.cs
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
My Bad, I forget to add the same logic checking whether hide for quick break when actionresponse from callback is empty.
Related to #464 Discussion
> Fix hide logic

- Flow.Launcher.Core/Resource/Theme.cs
Add window margins when the shadows are enabled to avoid shadow cut off
Before:
There are cut off to shadows at the top and bottom. (check the bottom right corner)
After:
The shadows in all corner are properly rendered.
> Add Margin When Enabling Box Shadows

- Flow.Launcher.Core/Flow.Launcher.Core.csproj
- Flow.Launcher.Core/Plugin/PluginsLoader.cs
switch to using python 3.8.9 embeddable
1. prompt user if want to manually set python path or use Python Embeddable 3.8.9
2. if user chooses manually set, dialog box opens for selecting the folder
3. if chooses to let flow install python flow will download and extract the Python Embeddable and set it as the python path for use on python plugins
> dev branch: switch to python 3.8.9 embeddable

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
resolve #433 
We need votes for this pr
@Flow-Launcher/team
> stop hiding scroller

- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
Why: `GetMethod(String)` raise AmbiguousMatchException when method have overloads (e.g. `ShowMsg`)
Solution: `Use GetMethod(String, Type[])`
https://stackoverflow.com/questions/1969411/avoiding-an-ambiguous-match-exception
> Fix AmbiguousMatchException when plugins call Flow API (JsonRPC)

- Flow.Launcher/SettingWindow.xaml
**Why:** The bottom margin (little gap) under General tab of Settings
make it hard to "feel" the space is scrollable or not.
New Windows 10 Settings style and websites tend to not have margin in the bottom
Related to: Issue [#443](https://github.com/Flow-Launcher/Flow.Launcher/issues/433) and PR #440
Before:
After:
> [UI/UX] Remove bottom margin of General tab (Settings)

- Flow.Launcher/Helper/SingletonWindowOpener.cs
Bug reproduce steps:
1. Right click on Flow icon in Notification Area, click settings
2. Minimize Settings-window (or Alt+Tab to different window)
3. Right click on Flow icon in Notification Area, click settings
4. Settings-window will not show back up 
I'm not really sure why this solution works tho 😅 
Maybe `.Show()` fails when `window.WindowState == Minimized` (not `Normal`)
Not sure why need .Activate() too
Ref: https://stackoverflow.com/a/59719760/4230390
Please delete unnecessary comments if this is too obvious to C# devs 😅
> [UI] Fix `Settings-window` doesn't show back up when minimized in taskbar by user

- Flow.Launcher/MainWindow.xaml.cs
The storyboard is only able to be controlled if using Begin(object, controllable) for beginning.
Maybe this can actually drop cpu usage to 0.
Related to #128
> fix storyboard animation control error

- Flow.Launcher/ViewModel/MainViewModel.cs
When `Shift+Enter/Ctrl+O` right after `Alt+Space` (input query (QueryTextBox?) is **empty**, i.e. `SelectedItems == null`), Flow still switch to ContextMenu mode, which cause a really weird UX, user sees nothing happen on the screen but the mode is switched.
When switch to ContextMenu from QueryResults, but no item being chosen, should do nothing
i.e. Shift+Enter/Ctrl+O right after Alt + Space should do nothing
Solution: Detect SelectedItems == null
> Fix ContextMenu bug

- Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
> [Plugin.Shell] Fix: The Query Box Is Not Focused When HotKey Invoked

- Flow.Launcher/SettingWindow.xaml
Why?
Seems cleaner and similar UX to other apps/website
Before:
After:
> Remove top margin of General tab (Settings)

- Flow.Launcher.Core/Resource/Theme.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/Themes/Base.xaml
- Flow.Launcher/Themes/BlurBlack Darker.xaml
- Flow.Launcher/Themes/BlurBlack.xaml
- Flow.Launcher/Themes/BlurWhite.xaml
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
- shadow does not work when blur is enabled via the theme file. This automatically disables shadow when blur is enabled
close #478 
- make query window width dynamic
> auto disable shadow when blur is enabled and make query window width dynamic

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
- Flow.Launcher.Infrastructure/Logger/Log.cs
- Flow.Launcher.Plugin/IPublicAPI.cs
- Flow.Launcher/Helper/ErrorReporting.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultsForUpdate.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Program/Logger/ProgramLogger.cs
> Exception log partial opt

- Flow.Launcher.Core/Plugin/PythonPlugin.cs
This will cause we are unable to query once loading a context menu for the specific python plugin.
> fix unintended use of direct startInfo.Arguments in context menu

- Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
> Fix Explorer unexpected action keyword for folder index search

- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
Co-authored-by: taooceros <hongtao_zhang@outlook.com>
Discussions: https://github.com/Flow-Launcher/Flow.Launcher/discussions/543
https://stackoverflow.com/questions/4951058/software-rendering-mode-wpf
> Fix (workaround) for the settings-window freezes after lock screen (Win+L)

- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
> fix unexpected Task Status

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher/MainWindow.xaml.cs
Dispose Disposable or AsyncDisposable plugin on mainwindow close
> Dispose Disposable or AsyncDisposable plugin on mainwindow close

- Flow.Launcher/App.xaml.cs
- Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/HotkeyControl.xaml
- Flow.Launcher/HotkeyControl.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
**Description**
After changing the hotkey that triggers flow's query window, the query window that get triggered by new hotkey can not be used- unable to move up and down on the result list, unable to move the cursor on the query test box, the query text is not select if you have this option enabled, and query window's position is not in the same place as previous. 
**Changes**
- consolidated duplicate hotkey behaviour code into one class HotkeyMapper
- added focus to custom query hotkey preview so can be used when previewing
- behaviour should be the same for when a hot key/custom query hotkey is changed and when these hotkeys are loaded during startup
**How to reproduce**
Change hotkey. Trigger the query window, then unable to use it with the issues described above.
**Tested with this …
> Fix flow's hotkey not working correctly after changing in settings

- Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Models/PluginsManifest.cs
use the [new branch](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/53) in PluginsManifest per [discussion](https://github.com/Flow-Launcher/Flow.Launcher/discussions/535)
> point pluginsmanifest to new api branch

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
fix Custom Plugin Hotkey not deselect text when current query text is equal to custom plugin hotkey.
The part I describe in #565.
> fix Custom Plugin Hotkey not deselect text

- Flow.Launcher.Test/Plugins/ExplorerTest.cs
This test fails when run on system have different locale than en-US, because of the hard-coded 1033 LCID (en-US).
> [Test.Explorer] Fix hard-coded  LCID (1033 - en-US)

- Flow.Launcher/SettingWindow.xaml
When user scroll down to the end, it will have some space around there.
> add some space to the end of the scrollviewer

- Flow.Launcher/MainWindow.xaml
reduce the size of the magnifying glass icon on the query window. for a preview of the before and after effects, see #588
> reduce magnifying glass icon size

- README.md
- Scripts/post_build.ps1
- appveyor.yml
Pack flow for portable release
1. install with silent flag
2. create userdata folder
3. zip to output location
4. upload artifact
This release is also helpful for users who are unable to use the installer
> Add portable release

- Flow.Launcher.Core/Flow.Launcher.Core.csproj
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
> Add a MemoryStream buffer to ReadStream first

- Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Repro:
Going to any context menu other than pm install and select open website will get the exception pop up
Fix:
- Added handling when the object can not be cast as UserPlugins. This means the selected result was not provided the plugins list from the manifest, as a result we bypass creating menu items for them.
- Added context menu for pm update
Tested:
- pm install and pm update all can use the context menu
- all other context menus will go to the default items with out those options available in install and update
> Fix PluginsManager context menu crashing

- README.md
- appveyor.yml
- Fix portable download link in readme
- Fix WinGet deployment so it occurs only on non-pr master branch builds.
- Change Nuget publish to tag only
> Fix portable readme download link & WinGet pipeline & change Nuget publish on tag only

- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Delay the create query helper call to avoid Windows Search not running, follows on from #599 , missed the query helper call which also requires Windows Search service.
> Delay the create query helper call to avoid Windows Search not running

- Flow.Launcher/ViewModel/MainViewModel.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- README.md
- Scripts/post_build.ps1
Standardise Flow's exe installer by removing the version at the end, this will make it easier to link to the latest download e.g. https://github.com/Flow-Launcher/Flow.Launcher/releases/latest/download/Flow-Launcher-Setup.exe
Tested:
1. changed the build version to 1.0.0 for testing
2. downloaded the artifact after build
3. Enabled portable mode
4. moved to different location
5. disabled portable mode
6. update to the latest via update command in query window
7. redid the steps 2-5 and updated flow via settings About tab
8. redid 2-7 for portable zip version
Updated readme to fix c# plugin dev doc and getting started section
> Standardise Flow's exe installer + readme update

- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Fix PluginsManager InstallOrUpdate method call's query window focus
> Fix PluginsManager's InstallOrUpdate focus

- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
#632 discussion
1. Expose Exception from JsonRPCPlugin so users may notice there's an exception thrown.
2. Don't stop result parse when stderr contains message.
> Adjust JsonRPCPlugin.cs Exception Handling

- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Fix Explorer's file result subtitle tool tip as file path instead
> Fix Explorer's file result subtitle tool tip as file path instead

- appveyor.yml
Simple one that I missed- fix WinGet publish due to change installer name https://github.com/Flow-Launcher/Flow.Launcher/pull/615 in 1.8.2 release. 
I have published 1.8.2 update to WinGet.
> Fix WinGet publish due to change installer name

- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Fix error from changing the File Content action keyword
Changes:
- add File Content Search Enabled status property
- remove null state from action keyword Enabled status
- rename IndexOnlySearchKeywordEnabled for consistency
- allow File Content Search to be turned on/off
Close #669
> Fix File Content action keyword change error

- Flow.Launcher.Plugin/GlyphInfo.cs
- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/ViewModel/ResultViewModel.cs
> Add Glyph Icon Support

- Flow.Launcher.Core/Plugin/PluginsLoader.cs
Change the message when Python plugins are detected and requiring Python. Instead of wording it as install which we no longer do as we use embeddable zip version, update the message to indicate download instead.
> update python message from install to download

- Flow.Launcher.Core/Plugin/ExecutablePlugin.cs
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Flow.Launcher.Core/Plugin/PythonPlugin.cs
- Flow.Launcher.Test/Plugins/JsonRPCPluginTest.cs
We don't need to provide a virtual method separately for query, context menu, and callback. The virtual method should only provide a way to pass the request model to the executable or something received the jsonrpc request.
Query, ContextMenu, and Callback should be indicated within the JsonRPC model.
> Refactor JsonRPC structure

- Flow.Launcher.Core/Flow.Launcher.Core.csproj
- Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Flow.Launcher.Test/Flow.Launcher.Test.csproj
- Flow.Launcher/Flow.Launcher.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
- Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
- Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
- Scripts/post_build.ps1
#486 
We cannot bump squirrel higher than 1.9.0
> Bump applicable nuget packages to latest versions

- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/PublicAPIInstance.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
> Implement Requery option and requery when calling customQueryHotkey

- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Fix Explorer plugin crash on semicolon
Repro:
type `;` with Explorer
> Fix Explorer plugin crash on semicolon

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
Sometimes the bookmark file may not be constructed property, leading the issue. This patch add a check for that to safely handle that.
> quick exit when children property is not found

- Flow.Launcher.Core/Resource/Internationalization.cs
- Flow.Launcher.Plugin/Interfaces/IPluginI18n.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/Classes/WindowsSetting.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/TranslationHelper.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/Main.cs
Add OnCultureInfoChanged to IPublicI18n to allow plugin do action when change language.
It is added with default implementation for interface for backward compatibility (so optional).
> Add OnCultureInfoChanged to IPluginI18n

- appveyor.yml
This stems from the 1.8.3 release which failed with the latest winget-create version. Simplest fix is just to fix the version we are using since our release is a simple straight forward update.
> Fix winget update causing incompatibility with always retrieving latest

- Flow.Launcher/MainWindow.xaml.cs
https://github.com/Flow-Launcher/Flow.Launcher/pull/763
Other pr contents were removed and simplified.
> Tray Menu Redesign

- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
Fix #783 
1. There is no problem with 'Hide on startup' and config
2. It related https://github.com/Flow-Launcher/Flow.Launcher/pull/749
3. The Hide() function uses the toggleFlowLauncher function. (Copied from PT)
4. Hide() run when start of the flow in somewhere. Since this function was wearing a toggle, it was a problem that the hidden state was toggled again at the beginning.
5. Power Toy seems to have had something different because it doesn't have Startup Setting.
6. I changed Hide() to just close window.
There was no problem when I tested it, but I don't know if it'll be okay because I didn't understand the code exactly. Please check.
> Force Exit & Fix HideonStartup (#783)

- Flow.Launcher.Plugin/SharedCommands/ShellCommand.cs
- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
close #828 
This pull request remove the pause/wait for enter for shell command.
> Refactor Shell Command

- Flow.Launcher.Plugin/Result.cs
It will break backward compatibility for plugin use Icon field (although I think not a lot use it).
> [dev] Change Icon back to field to maintain backward compatibility

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
Switch off the default launch on system start up, user can set it if they wish to launch with system start up
> Switch off the default launch on system start up

- Flow.Launcher.Core/Plugin/PythonPlugin.cs
Providing this data can help a plugin determine which version of Flow Launcher it's running on as well as help find settings.
> Provide Flow Launcher program data in Environmental vars

- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
Simply adds a method for jsonRPC to call and place test into the system's clipboard.
```
print(json.dumps({"method": "flow.CopyToClipboard","parameters":["text"]}))
```
> Add Clipboard copy to jsonRPC API

- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultViewModel.cs
Pressing <kbd>Tab</kbd> will replace the current Query with the selected result's `Title`.
https://user-images.githubusercontent.com/535299/144630236-62f19803-49a0-4fa2-b0da-217d28b71024.mp4
> Global TAB complete

- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Adds Auto Complete support to the file explorer plugin
> Explorer plugin: Support AutoCompleteText Field

- appveyor.yml
> Refresh Nuget publish

- Flow.Launcher/CustomQueryHotkeySetting.xaml
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/PriorityChangeWindow.xaml
- Flow.Launcher/Resources/Pages/WelcomePage3.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml
1. https://github.com/Flow-Launcher/Flow.Launcher/issues/883 Change Wizard window to modal when open in about only
2. Change Label Width Size 
3. Change Checkbox Position
4. Add Tab Key description in page 3 in wizard window
> Small Design Fix in Setting Window

- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
> Adjust Vertical Alignment and Margins in JsonSettingPanel

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
version bump plugins for  https://github.com/Flow-Launcher/Flow.Launcher/pull/895
> dev version bump plugins for pr 895

- Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
- Flow.Launcher.Core/Updater.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
> Remove Startup Error notification for updating manifest and update check

- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- appveyor.yml
bump version for release 1.9.1
> Release 1.9.1 version bump

- Flow.Launcher/MainWindow.xaml.cs
The trigger key is very important, but it is currently notified on the Wizard screen, and in the settings, you need to go to the hotkey tab to know the set key. Add display the trigger key so that you can know immediately when you open the tray menu.
> Display hotkey in tray context menu

- Flow.Launcher/Resources/CustomControlTemplate.xaml
- Flow.Launcher/SettingWindow.xaml
**Before** 
- The knob position of the toggle switch is wrong.
- This is a problem caused by the use of RTL for right alignment.
- When the window size increases, the positions of the Priority button and the toggle switch operate incorrectly.
**After**
- Toggle Switch with LTR
- Fix Toggle Switch Circle Positioning
- Change "Open Theme Folder" Button Width to Responsive
- Adjust Priority Button Position
- Even if the window size changes, it is aligned to the right.
**Test / Validate**
- When the toggle switch is turned on, the inner round circle (aka Knob) must be on the right.
- For languages with long toggle switch on/off labels, the area is automatically adjusted and all must be displayed. 
- The dot mark in Slovak language should be displayed on the right.
- When adjusting the size of …
> Fix Toggle Switch Knob (White Circle) Positioning

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Languages/ko.xaml
- Flow.Launcher/Languages/pt-pt.xaml
- Flow.Launcher/Languages/sk.xaml
- Flow.Launcher/ReportWindow.xaml.cs
- Flow.Launcher/SelectBrowserWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Fixes this:
The translation keys were flipped for tab/browser, and the `DynamicResource` was incorrectly set for the "New Tab" case.
Also resolved some compilation warnings.
> Fix incorrect text for "New Tab" and "New Window" buttons

- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
temporary fix for #950 
We should stop init disabled plugin when startup. corresponding to idea of #391
> stop trigger global hotkey when shell plugin is not enabled

- Flow.Launcher/ViewModel/MainViewModel.cs
- Plugins/Flow.Launcher.Plugin.PluginIndicator/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
Quick one to address some minor annoyances:
1. hitting Tab from a context menu seems to be only intended for accidents... I've ended up with "Set as topmost in this query" as my query text a few times 😂 I have disabled auto-completion in context menus since I don't see a use for it...
2. hitting Tab from a ProcessKiller result would append the process number to the query, which would no longer work be a valid `kill` query
3. hitting Tab from a PluginIndicator result would not append a space at the end
> Minor enhancements to query auto-completion

- Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
- Flow.Launcher.Infrastructure/Http/Http.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
The main change introduced here is the use of conditional http requests when fetching the plugin manifest json. This allows us to always check for changes to the manifest repo when running one of `pm install`, `pm update`, with very little performance overhead (for me it is about 50ms). It also allows us to simplify the relevant code a bit.
Also some quick refactoring in `PluginsManager` and a couple quality-of-life enhancements:
1. typing `pm inst` and hitting tab would autocomplete to `pm install` without a space at the end (same for the other base commands)
2. fix incorrect link (for some plugins) when selecting to open an issue from the context menu
PS: I missed #682 until I started writing this PR text... my apologies. I see similarities, perhaps we can pick some of the missing …
> Improvements to PluginManager plugin

- Flow.Launcher/App.xaml.cs
- README.md
> Add scoop install to readme

- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/SuggestionSource.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
> Add null check before enumerating the enumerable

- Flow.Launcher/ViewModel/ResultViewModel.cs
WPF requires font name after the font source. This patch adds support for that.
> Revise ttf/otf code

- Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
WindowsSettings results are higher than normal due to intentional score bumping. This fix removes the bump for settings name matched results and for non-name matched results reduce by 10 points.
This means normal Windows settings results should rank the same order as all other plugin results, and the lower ranked non-name matched results behaviour is still kept.
**Before**, should actually show SourceTree program from Program plugin:
**After**
Addresses #1008
> Fix WindowsSettings plugin result scores higher than normal

- Flow.Launcher.Infrastructure/Image/ImageCache.cs
This pull request fixes the race condition when calling `.ToArray()` on a `ConcurrentDictionary` in the `ImageCache` class.
Related issue: close #1039
> Remove calling `.ToArray()` on a `ConcurrentDictionary`

- Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
This fixes the issue where multiple plugins using shared assembly like SQLite, where the ones loaded later will not be able to access the shared assembly.
Previous I check all the loaded assembly before allowing the pluginassemblyloader to load the assembly. However, this doesn't seem like a good practice, since this will prevent a assembly context to load the same assembly if another assembly context has already loaded it (which are isolated).
I have tested it for the winrt.dll situation as well. The default assembly loader will load the winrt.dll before we trigger a deferred load so all assembly should be good with that. However, I am curious whether we should match with Name instead of FullName.
> Fix Shared Assembly Issue

- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Fix incorrect logic added in https://github.com/Flow-Launcher/Flow.Launcher/pull/968 where application URIs opened from WebSearch plugin are not be triggered
> [Dev] Fix application URI logic when opening via WebSearch plugin

- Flow.Launcher/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.resx
Fix typo for plugin title in context menu and WindowsSettings name, `Plugins` -> `Plugin` & `Windows settings` -> `Windows Settings`:
Checked that the plugin string is only used by the context menu.
> Fix typo for plugin title in context menu and WindowsSettings name

- Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
- Flow.Launcher.Infrastructure/Image/ImageCache.cs
- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Languages/ko.xaml
- Flow.Launcher/Languages/pt-pt.xaml
- Flow.Launcher/Languages/sk.xaml
- Flow.Launcher/ReportWindow.xaml.cs
- Flow.Launcher/SelectBrowserWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/ResultViewModel.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Baidu.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Bing.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/Google.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/SuggestionSource.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
Release Notes
=========
- Addresses the issue where WindowsSettings plugin results appear higher than other results #1020 
- Fixed an issue where full screen mode does not disable hotkey when enabled #1037 
- Fixed some potential issues when loading plugins that use shared assembly #1036 
- Sorted out a race condition issue causing image loading on some results to fail #1040 
- Revised ttf/otf support #935 
- Resolved the issue where WebSearch plugin would crash if not connected to internet #977 
- Fixed incorrect text for "New Tab" and "New Window" buttons under Settings' default browser section #951 
- Fixed typos in plugin title and WindowsSettings name inside the context menu #1056
> Release 1.9.3

- appveyor.yml
WinGet deployment has not being working too well, let's remove it from our deployment pipeline as flow is actually being automatically updated with every release thanks to @vedantmgoyal2009's [WinGet Automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation)
> Remove obsolete WinGet from appveyor.yml deployment pipeline

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
Every time I start Flow Launcher since the plugins refactor, the Bookmarks plugin has been throwing an exception.  The issue stems from it parsing the Bookmarks file, and assuming that every JsonElement in the "roots" element is a JsonValueKind.Object.  My Bookmarks file though has a JsonValueKind.String value off the roots key of `"sync_transaction_version": "20297",` along-side the bookmark_bar, other, and synced keys, which ARE objects.  When it calls EnumerateFolderBookmark with the value from the sync_transaction_version key, it gets into the method because the string value of `20297` IS a JsonElement, but then throws an exception on the folderElement.TryGetProperty("children", ...) call because you can't call TryGetProperty on a String, only Objects.  So... only try to Enumerate …
> avoid exception in ChromiumBookmarkLoader.cs

- Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
Set Shell plugin's default replace Win R hotkey to off, it has been confusing new users.
> Set Shell plugin's default replace Win R hotkey to off

- Flow.Launcher/Themes/Base.xaml
**What's the PR?**
- Fix for https://github.com/Flow-Launcher/Flow.Launcher/issues/1066
- For older versions, there is no problem with high resolution (over 1920x1080), but it appears to be a problem with typical FHD.
- Removed All CleartypeHint Rendering (RenderOptions.ClearTypeHint="Enabled")
I don't have a 1920x1080 monitor, so it's hard to test.
(It cannot be properly tested by changing the resolution.)
In my case with this PR, the higher resolution(over FHD) was no problem, and it looked okay on FHD. Other people's tests are needed.
**Refer**
- https://github.com/microsoft/PowerToys/issues/6462
- https://github.com/microsoft/PowerToys/pull/10568
**Test Case**
- In 1920x1080, the Chinese language shall be displayed smoothly.
- In higher resolution thatn 1920x1080, fonts should be …
> Remove All Cleartype Rendering

- .github/ISSUE_TEMPLATE/workflows/stale.yml
With this workflow Issues and PRs that have not received any updates will be marked with a `stale` label. 
Any Issues will be closed after 5 days if they are not updated after being marked. 
PRs will never be closed.
Any PR that has a milestone will be exempt from the stale label.
> Add Stale issue workflow

- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
I include the PR #1074 because they both tried to address the same problem. I don't know if there are cases where #1074 applies or not, but it's more robust code, thus better.
Reason for this PR are explained in various comments of #1074
Should close #1025 close #1070 and close #1078
> Caret position fix : Include PR #1074

- .github/workflows/stale.yml
Changed some configuration on Stales Bot. 
1. Increase the number of days an issue/PR is marked stale to 45 days.
>Hopefully this will give some issues some breathing room to be resolved.
3. Increase the number of days until an issue is closed to 7 days (up from 5 days).
>Should give a more reasonable chance for anyone to respond before the issue is closed.
4. Ignore PRs that are in progress or awaiting approval
5. Ignore Issues and PRs that are marked with a "keep fresh" label.
> Give some control to the team on whats marked stale or not.
> Update Stale bot

- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
When a plugin's settings is clicked on, it will automatically snap to the top to fill the entire settings window.
> Scroll to selected item when expanded or size changed

- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
> Use Cancellation Token to avoid potential race tracing issue

- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher.Test/Plugins/JsonRPCPluginTest.cs
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
Result Execution can take quite long (Especially for JsonRPCPlugin), which cannot handle threadpool easily (requiring subprocess to prevent long execution time).
> Implement Async Result Execution

- Flow.Launcher.Core/Plugin/QueryBuilder.cs
- Flow.Launcher.Test/QueryBuilderTest.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
Trailing whitespace can be very helpful for argument detection.
This PR removes any whitespace trimming from Query before being passed to the Plugin.
> Pass query without trimming whitespace

- Flow.Launcher.Core/Flow.Launcher.Core.csproj
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/Themes/Base.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
- Plugins/Flow.Launcher.Plugin.Calculator/Settings.cs
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/Properties/Resources.resx
- Scripts/post_build.ps1
- appveyor.yml
Release Notes
=========
- Bumped NuGet.CommandLine from 5.4.0 to 5.7.2 #1241
- Fixed shell cmd command when used with quotes and spaces #1205
- Fixed occasional NullReferenceException error #1204
- Updated Python download mirrors #1187
- Fixed font-anti-aliasing #1119
- Fixed decimal separator when used as part of the query #1108
- Fixed plugins inside settings window to expand correctly and fill the entire window when required #1098
- Updated Shell plugin's default setting for replacing Win R hotkey to off #1087
- Fixed incorrect button visibility in Explorer plugin's setting panel #1077
- Updated Explorer's path search to not use index by default when searching inside directories #1076
- Fixed a silent error thrown when Chromium bookmarks are loaded #1071 
- Fixed typos in context menu …
> Release 1.9.4

- Flow.Launcher/SettingWindow.xaml
Fixes #1284: `CollectionViewSource` will synchronize the current item across all users of the same view source unless they explicitly set `IsSynchronizedWithCurrentItem`.
> Fix theme fonts not changing separately for query box and results

- Flow.Launcher.Core/Resource/Theme.cs
Fixes #625 & #637 
This will mean that changing some settings will be a bit slower than before, especially when enabling blur which will reload resources twice but this is negligible and only hits in settings.
> Force reload theme resources when changing fonts etc in settings 

- Flow.Launcher/MainWindow.xaml.cs
When browsing directories and using ctrl backspace to go back up one directory, flow will throw error if ctrl backspace is pressed when there is no query text.
Currently error exists in Dev branch.
> [Dev] add check query length when calling backspace command action

- Flow.Launcher.Core/ExternalPlugins/FlowPluginException.cs
- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher/ReportWindow.xaml.cs
Add exception handling thrown by plugins.
Update user error window to point to plugin's Url.
> Add handling of exceptions from plugins

- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
1. Unregister `kill` callback by disposing the registered event.
2. Fix Error Message not being read
> [Dev] Unregister Cancellation Event by disposing the delegate

- Flow.Launcher/SettingWindow.xaml
Move 'icons by icons8.com' to the About tab instead of a hyper link.
**Before**
**After**
Related https://github.com/Flow-Launcher/Flow.Launcher/pull/843
> [Dev] Add icons to About tab

- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/SettingWindow.xaml
- Change Max Width to 1920 from 900 (Window Size Slider in setting window)
- Adjust Result Item Layout
**Check List**
- Even if you increase the window size, the item layout must be displayed normally.
- The shortcut (alt+1 things) display should be displayed normally when turned on and off.
**ETC**
- 1920 is a temporary. I hope the width will be changed based on the Monitor's Width.
> Adjust Max Width Window Size

- Flow.Launcher/ReportWindow.xaml.cs
To repro:
1. Cause an exception
2. Ctrl + click on the exception report window link
3. Observe the link is opened twice in two browser tabs
(If you can debugging locally, you can install GitHub Quick Launcher and type query 'gr' and exception window will pop up. This exception is not an issue with the plugin, but because flow is not run from the expected Local AppData location.)
> Fix opening url twice when clicking on exception report link

- Flow.Launcher/Languages/es-419.xaml
- Flow.Launcher/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.Calculator/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Calculator/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.PluginIndicator/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.ProcessKiller/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.Program/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Program/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.Shell/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Shell/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.Url/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Url/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/es.xaml
These are all language files for Spanish & Spanish Latin America added to the dev branch at the time of this PR, copied across for v1.9.5 release.
I purposely left out the language files in Windows Settings plugin because the changes are too drastic.
Expected:
Should not have any differences in the language files between this branch and dev branch.
Tested:
Selected both Spanish and Spanish Latin America and observed that the language has changed on each screen including plugin settings.
> Spanish & Spanish Latin America languages release for v1.9.5

- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
Throw exception when type "＃, ＆, ＊, ＠".
> Special character error in ole db query

- Plugins/Flow.Launcher.Plugin.PluginIndicator/Main.cs
The error may happen when user set an action keyword to plugin indicator, in which the query may have empty Search and empty SearchTerms.
fix #1371
> Use Search instead of SearchTerm[0] in PluginIndicator

- Flow.Launcher.Core/Plugin/PluginManager.cs
Defensive coding. The error suggests there's something here that can be null, which can only be the query. However, I am not sure when it will happen since the reporter doesn't provide way to consistent reproduce the error.
fix #1366
> check query for null

- Flow.Launcher.Core/Resource/Theme.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/Themes/BlurBlack Darker.xaml
- Flow.Launcher/Themes/BlurBlack.xaml
- Flow.Launcher/Themes/BlurWhite.xaml
- Flow.Launcher/Themes/League.xaml
- Flow.Launcher/Themes/Win11Light.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
1. Adjust Blur themes
- Fix outside blur and adjust colors in Blur Themes.
2. Adjust Shadow
- Changed shadow more similar to native window shadow (win10~11)
3. Align about panel
4. Add Tooltip in Hide in tray
5. Add glyph in language item 
6. Changed 'settings' command's subtitle to more searchable.
> Adjust designs & Texts

- Flow.Launcher/Resources/CustomControlTemplate.xaml
**What's the PR**
- It's a small difference, but the font in the Context menu that opens in Querybox looks blurry.
- Fix the issue
**Before**
**After**
**References**
- https://stackoverflow.com/questions/21538296/wpf-dropshadow-on-button-causes-blurry-text
- The same style is shared by the Tray menu, but there is no problem.
> Fix Blurry Context menu in query box

- Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
Some display texts in results' subtitles and tooltips of WindowsSettings plugin are hard coded. They have been translated but remain unused.
> Change hard-coded strings in WindowsSettings plugin to translated

- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
from https://github.com/Flow-Launcher/Flow.Launcher/issues/1309
**Before (and other languages)** 
**After**
Currently, the text is separated into three paragraphs, and inline bold cannot be used. To produce as requested, the design must be changed to four paragraphs, and all existing translations must be changed.
Therefore, it becomes the current editing form, and it is necessary to check if it is okay. Other languages will remain in their existing form, leaving each language worker at their discretion to translate according to the layout.
> Search Source Setting guide text

- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/Themes/Base.xaml
- Flow.Launcher/ViewModel/ResultViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
When the item in the ResultListBox was added, fixed progressbar binding error.
```
System.Windows.Data Error: 40 : BindingExpression path error: 'ProgressBarVisibility' property not found on 'object' ''Result' (HashCode=1859780700)'. BindingExpression:Path=Result.ProgressBarVisibility; DataItem='ResultViewModel' (HashCode=1859780700); target element is 'ProgressBar' (Name=''); target property is 'Visibility' (type 'Visibility')
```
> Fixed Progressbar Binding Error (ProgressBar Value is Not Nullable)

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
Fixed an error when typing QueryTextBox in specific language.
For example, if the user enters "안녕하세요" and presses the Enter key immediately, it will be searched as "안녕하세".
> Fixed QueryTextbox Binding event

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- works like install button. (automatically change the query to pm uninstall ...)
> Add Uninstall Button

- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/ViewModel/ResultViewModel.cs
Allows plugins to apply a rounded mask to a result icon.
Plugin need only provide the field `RoundedIcon` with a Boolean. Defaults to `False`
Some API's provide a square icon but intend to be displayed with rounded edges. This will help display images correctly.
Before:
After:
> Rounded icon mask field

- Flow.Launcher/Converters/OpenResultHotkeyVisibilityConverter.cs
- Flow.Launcher/Converters/OrdinalConverter.cs
- Flow.Launcher/MainWindow.xaml
So currently HOTKEY+1-9 (Alt by default) are desinated to opened search results, HOTKEY+0 is unused. Made some changes to allow HOTKEY+0 to open the 10th result.
> Allow 10th result hotkey

- .github/dependabot.yml
Add automatic check for dependency update
> Add github dependency bot

- Flow.Launcher.Infrastructure/UserSettings/CustomShortcutModel.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/CustomShortcutSetting.xaml
- Flow.Launcher/CustomShortcutSetting.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Implemented changes required in #930.
> Custom Shortcut update

- Flow.Launcher/Languages/en.xaml
Update with adjustment shortcut wording
> [Dev] Update with adjustment shortcut wording

- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
In dev branch, the init method of `PluginsManager` awaits the result of updating plugin manifest. With a slow internet connection (like public wifi) it could significantly slow down startup. The manifest can be updated later (since we can use Flow without internet).
> [DEV][Plugins Manager] Remove await in updating plugin manifest to speedup startup

- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Old source code doesn't check if an indexed program is marked as `Valid`. So .url files with http protocols (disabled by default) can be shown in result. Fixed.
> [Dev] Fix unwanted URL protocols and invalid programs in custom sources

- Flow.Launcher.Infrastructure/StringMatcher.cs
- Flow.Launcher.Test/FuzzyMatcherTest.cs
Currently scoring is the same regardless of the position of the matched string, e.g. 'hello world' and 'world hello' have the same score. This change adds an adjustment during score calculation to allow 'world hello' to score higher than 'hello world' when query is 'world'.
The conditions for this adjustment to kick in is:
- the matched string has to be immediately preceding a space, and
- query must be a fully contained substring of the compare string.
Score adjustment is done by:
Counting the number of spaces from the start of the string and deduct this from the score. So when matching 'world', 'world hello' has 0 spaces, so nothing is deducted from the score. On the other hand 'crazy on fire world' has three spaces so deduct three from the score.
Before, notice 'Graphics Settings' …
> Score adjustment for a match that is closer to the start of string

- Flow.Launcher/ViewModel/MainViewModel.cs
Fixed a bug where shortcut causes a null query when clipboard has no text (empty or an object)
> [Dev] Fix clipboard shortcut error when clipboard is empty

- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/Resources/Dark.xaml
- Flow.Launcher/Resources/Light.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
- Decode Image Size in Theme Preview 
- Reason : if user use big size wallpaper, it will effect to flow. size decode will solve the problem.
- I don't think it's a big problem, although the image drops to low definition.
- Use Virtualizing Panels in Plugin Store List / plugin list / ETC for memory leak
- Refactor Plugin Store UI (Changed Wrap panel from Uniform grid.)
- Reason : in this case, item size doesn't fit with list width. Several implementations were attempted, but this condition was judged to be good because performance problems occurred and design problems were not significant.
- 'Update Label' (Green Ball) changed placement to icon's right.
- Reason : Due to implementation problems, it could not be displayed in the upper right corner.
> Fix memory leaks with Plugin store layout

- Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
Program plugin can't get icons for some uwp programs because of complex icon filenames or path finding issue. Tried to fix it.
> [Program Plugin] Fix UWP icon missing issue

- appveyor.yml
- Recently CI fails because some weird issue that it detects the Flow.Launcher.Test.dll in path that contains an extra parent of `Any CPU`. This pr try to manually run the test to avoid that.
- Also let the package run after test step is done
- Added caching config to let the builds done faster
> Appveyor test executable unfound fix and add caching

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/SettingWindow.xaml.cs
- Before : When you close the setting window in full screen state, it does not go into full screen state when you reopen it.
- After : When you close the window in full screen state, it also opens to the full screen when you reopen it.
> [Dev] Save Setting Window State (full / normal)

- Flow.Launcher.Test/Flow.Launcher.Test.csproj
- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/Resources/CustomControlTemplate.xaml
- Flow.Launcher/SettingWindow.xaml
**What's the PR**
<strike>- Seperate style to other file from SettingWindow.Xaml (SettingWindow.xaml was too long)</strike>  Let's apply this task when working with valonia.
- Change the Checkboxes to Toggle button in general / Hotkey / Proxy Tab
**Before**
**After**
**Fix Plugins Designs**
- Fix Clickable Area
- Fix Hover Color
- Adjust Some Colors
Fix Store with Darkmode
**Why?**
- https://uxdworld.com/2018/08/13/checkbox-vs-toggle-switch-7-use-cases-of-forms-design/
- It is not recommended to mix check boxes and toggles. Organize in a toggle for a sense of unity.
- It was a todo that I tried to do in the beginning redesign, but I didn't know how to bind at the time.
**Test Case**
- Each Toggle Button must operate correctly.
- The color shall be marked accurately when you mouse over the …
> Fix Setting Window Designs 

- Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
- Plugins/Flow.Launcher.Plugin.Program/Views/Models/ProgramSource.cs
Fix bug introduced in #1496 and make some fields not null. User disabled programs can't be correctly hidden in results because UID case was incorrect. Forgot to test user disabled programs:(
> [Dev][Program Plugin] Fix uid case of user disabled programs

- appveyor.yml
**Context**
Update our deployment pipeline to deploy to the GitHub Releases page in the new [Flow-Launcher/Prereleases](https://github.com/Flow-Launcher/Prereleases) repo when a PR is merged into dev.
**Why:**
We want a place where we can download prerelease builds that is separated from our main repo's releases so it's cleaner and easier to navigate for average users. Having a prerelease repo will bring the following additional benefits:
- Overcome the AppVeyor dev branch artifact download limit
- Easier linking to the prerelease build artifacts via https://github.com/Flow-Launcher/Prereleases/releases/latest
- A dedicated place for all prerelease versions
- Set the foundation for setting up the ability to switch to prerelease version from within Flow's settings by switching the endpoint …
> Deploy prerelease builds to Flow-Launcher/Prereleases

- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
This is a optimization of #1479. PATH can be a subfolder of custom program sources. It makes unnecessary I/O when enabled PATH indexing because indexing for custom sources is recursive. And a custom source can be a subfolder of another.
And let file change watcher only watch files that can be indexed (`exe`, `lnk', ...).
1. Refactored some code for readability.
3. Detect if PATH is a subfolder of a custom source.
4. Detect if a custom source is a subfolder of another.
5. Only watch specific file extensions.
6. Fix an issue where trying to open a .lnk files parent folder, it acutally opens its target's folder.
> [Dev][Program Plugin] Optimize program indexing performance 

- appveyor.yml
1. Branch builds are required in order for the dev branch pushes to deploy to the Prerelease repo as configured [here]( https://github.com/Flow-Launcher/Flow.Launcher/pull/1547). When the branch build is disabled, the release pr only does PR builds and consequently does not deploy to prerelease repo. I do not see another way to restrict branch build to only a specific branch so just have to enable it for all.
2. Skipping md files will cause the GitHub build status check to hang and consequently the PR can not be merged, so removing it unless there is a way to get status feedback when the build is skipped.
> [Dev] Allow branch builds and do not skip md files

- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/HotkeyControl.xaml
- Flow.Launcher/HotkeyControl.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/Resources/CustomControlTemplate.xaml
- Flow.Launcher/Resources/Dark.xaml
- Flow.Launcher/Resources/Light.xaml
- Flow.Launcher/SettingWindow.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
- There is a size problem in some languages. The size of some fixed controls has been changed flexibly.
- I had to use the context menu while doing this work. Therefore, the template of the context menu was also modified.
- As the context menu changed, some color issues happened, so also corrected.
- If the version is 1.0.0, it is marked as Dev. (I think it's unnecessary now...)
- Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/1522
- You should check these with Slovak / Spanish / Russian language mode.
- with Minimun Window Width
- The color should be displayed correctly on other context menus and flyouts.
**Before**
**After**
**Before**
**After** (Adjust wrapping)
**Before** (Problem with some languages)
**After** (Put items into one button)
**Before**
**After** (Merge with …
> Fix Narrow Items & Adjust Context Menu Design

- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
#1546 changed the behavior of launching .lnk programs. It directly launches the program pointed to. It wasn't intended. Got mislead by the varaible name.) which brings an issue. Start Menu shortcut of Discord can't be launched. This is because it acutally points to `blabla\Discord\Update.exe --processStart Discord.exe` and we don't parse the params. Fixed in this pr.
Known issue of program plugin (not related to this pr or 1546): can't distinguish different .lnk files pointing to the same target but with different params.
> [Dev] Use path of lnk file when launching proram

- Flow.Launcher/SettingWindow.xaml
- Fix the problem of hotkey settings appearing when switching tabs.
- This issue is caused by a change in the TabControl template.
- I recently changed the size of the left menu flexibly. The effect of this change.
> Fix Focus hotkey box when change tab

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
- Change Theme Preview area to non-clickable (avoid click error when click item inside Theme Preview)
- Fix margin issue (when change shadow setting). Window will be fixed position.
- Change Preview Item Texts to translatable
> Fix Theme Preview area

- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
Add Focus to plugin/plugin store search box when changed tab
- Keyboard focus should be in the search box when switching tabs.
- When entering the hotkey tab, the hotkey tab must not be focused.
> Add Focus to plugin/plugin store search box when changed tab

- Flow.Launcher/App.xaml.cs
fix second startup not show the main window. (I believe it's the issue of transparency that will only be changed by the Show() in MainViewModel).
Tested in discord
https://ptb.discord.com/channels/727828229250875472/727828229250875476/1048414123270090822
> Fix Second Run not trigger the first run window to show up

- Flow.Launcher/Themes/Base.xaml
- Glyph Icon Size 128 to 96.
- Correction missed in image preview pr.
> [Dev] Fix Glyph Icon Size in preview

- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/WelcomeWindow.xaml
- Fix #1607
- Fix Welcome Window's Title
> Change hardcoded text to string

- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Fix action keyword missing when traversing paths or using autocomplete
Repro:
1. Use path action keyword to go to c:\users\
2. see action keyword for path is removed after entering into the directory.
Tested:
1. Path traversing with action keyword
2. Path traversing without action keyword
3. Autocomplete with action keyword on Open Current Folder result
4. Autocomplete with action keyword on Drive Disk Space result
5. Autocomplete without action keyword on Open Current Folder result
6. Autocomplete without action keyword on Drive Disk Space result
> [Dev] Fix action keyword missing when traversing paths or using autocomplete

- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
1. Fix duplication when Quick Access is added from the open current folder result
2. Fix duplication of results due to case sensitivity
Repro:
1. Go to c:\users\ and on the top result open current folder go to context menu
3.  select 'Add to Quick Access'
4. while still in c:\users\ see the duplicated entries.
Before:
After fix:
> [Dev] Fix duplicate Quick Access results from CreateOpenCurrentFolderResult

- Flow.Launcher/Languages/da.xaml
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Languages/es-419.xaml
- Flow.Launcher/Languages/es.xaml
- Flow.Launcher/Languages/fr.xaml
- Flow.Launcher/Languages/it.xaml
- Flow.Launcher/Languages/ja.xaml
- Flow.Launcher/Languages/ko.xaml
- Flow.Launcher/Languages/nb.xaml
- Flow.Launcher/Languages/pl.xaml
- Flow.Launcher/Languages/pt-br.xaml
- Flow.Launcher/Languages/ru.xaml
- Flow.Launcher/Languages/sk.xaml
- Flow.Launcher/Languages/sr.xaml
- Flow.Launcher/Languages/uk-UA.xaml
- Flow.Launcher/Languages/zh-cn.xaml
- Flow.Launcher/Languages/zh-tw.xaml
- Flow.Launcher/Resources/CustomControlTemplate.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/PluginViewModel.cs
- It simplified the plugin info area
- init/query time changed it to be seen as a tooltip in version.
- The relevant String has been cleaned up.
> Adjust Plugin info area

- Flow.Launcher.Core/Plugin/JsonRPCConfigurationModel.cs
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Plugins/Flow.Launcher.Plugin.Sys/SysSettings.xaml
- Plugins/Flow.Launcher.Plugin.Sys/SysSettings.xaml.cs
- Adjust Setting Panel Margin & Column Width to responsive (System plugin)
- Adjust JsonRPC Panel Layout
- Added layout for input box with browse button / hyperlink (function not implement,  This part will be implemented later.)
> Adjust Setting Panel Layout (System & JsonRPC)

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/Themes/Base.xaml
- Flow.Launcher/Themes/Win10Light.xaml
- Fix the problem that the bottom margin was larger than before when loading without the result item.
> Fix the bottom margin issue when loading progress

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/Themes/Base.xaml
- Fix #1655
- Fix wrong margin with non-result with preview state.
- Changed Progress bar height (to large)
- The Progress bar screen has been adjusted so that it does not come out of the screen.
- With no items present, there should be no margin below when loading.
- If there are no result items, the separator (middle line) should not be displayed.
> Fix Progressbar & Margin issue with preview panel

- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
- Plugins/Flow.Launcher.Plugin.Program/Settings.cs
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
Rename the variable in settings to disable indexing PATH programs by default.
Tested:
> Disable PATH programs by default

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Converters/BoolToIMEConversionModeConverter.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
- Add settings that always start in English when you start flow.
-  If the user is using a Native/English layout, Sometimes the input will start in an unwanted language.
- It always starts in English, regardless of your language status, so you can avoid typing incorrectly.
- This setting can be turned on and off; the default is off.
> Always Start in English Layout

- Plugins/Flow.Launcher.Plugin.Program/Languages/ko.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/ko.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
In the past, True False was changed to Enabled/Disabled and Header was changed to Status. 
At this time, some enabled labels were changed to status. 
This PR changed it because the Enabled item is displayed as Status in some windows. I adjusted this part because I judged that there were cases where it was necessary to separate depending on the language.
> Change Status Label to Enabled

- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
Changes:
- Refactored Toggle Game Mode logic.
- Fixed an issue that changing Open Result modifier in settings window won't reflect to main window.
- Formatting and removed redundant codes.
Tests:
> Refactor Toggle Game Mode logic in main window

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/da.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/de.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/fr.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/it.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/ja.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/nb.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/nl.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/pl.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/ru.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/sr.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/tr.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/uk-UA.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/zh-tw.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Before:
After:
Tested:
- Correct warning displayed
- Select the warning result and install Everything
> Fix wrong Everything service warning displayed when not available

- Flow.Launcher.Test/Plugins/ExplorerTest.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Fix directory path search when triggered from quick access
- Fix autocomplete text when both path and search action keywords are disabled
- Added unit tests
Note: if both path and search action keywords are disabled, selecting the result will open the folder instead of navigating to the path. 
**Tested:**
- Select folder result listed via Quick Access will navigate to the path with search action keyword when both search and path search action keywords are enabled or only search action keyword is enabled
- When search action keyword is disabled and path search is enabled, selecting result will navigate to the path with path search action keyword
- When both path and search action keywords are disabled, selecting result will open the folder instead
- When both path and search action …
> Fix quick access path search and autocomplete text

- Flow.Launcher/ViewModel/MainViewModel.cs
Fix #1697 #1629.
Can't reproduce those issues so no actual test was done. A catch all should fix them.
> Catch exceptions during shortcut expansion

- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
#1678 Added hh:mm:ss tt to the clock formats to show seconds in the clock.
> Add "hh:mm:ss tt" to clock formats.

- Flow.Launcher/Resources/CustomControlTemplate.xaml
- If there is nothing on the clipboard, a problem occurs when an empty context menu is displayed.
- Resolve the issue by disabled context menu by not hiding it
> Remove Hiding the Disabled menu Item

- Flow.Launcher.Infrastructure/Image/ImageCache.cs
- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
No need to append ImageType to path. `loadfullimage==true` already indicates that it's a full image.
> Fix ImageCache when loading full image

- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Changes:
- Clear logs of all versions
- Use binding for button text
- Move open log dir to vm
- Text: "Bytes" to "B"
Tests:
- Logs of all versions are cleared
- Log size text updated after clearing
> Refactor clear log folder logic

- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
> Add glyph for open with editor/shell

- .github/workflows/spelling.yml
Stop checking on push to avoid checking merge commits on dev branch. Commits of PRs can be checked on synchronized.
> Stop spell check on push

- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/ViewModel/MainViewModel.cs
When Flow Launcher is invoked with an active Explorer.exe window selected Flow Launcher will open with that folder path selected.
https://user-images.githubusercontent.com/535299/146168862-f5bba285-f310-4acb-9e5c-a1760b2ddb36.mp4
> Insert active explorer path

- Flow.Launcher/ViewModel/ResultViewModel.cs
Let's trust plugin developer when they use that for icon
This will solve the icon blink for uwp and some other plugin that use IconDelegate.
Tested:
> Remove await Task.Run for IconDelegate

- Flow.Launcher.Infrastructure/FileExplorerHelper.cs
When used via Explorer plugin this will help results come up already inside the directory.
> Add slash to active explorer path return string

- Flow.Launcher/ViewModel/MainViewModel.cs
Explorer shortcut in #1275 is laggy. No need to calculate the shortcut when the shortcut is not in the query.
> Expand builtin shortcuts when needed

- .github/actions/spelling/expect.txt
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/AccessLink.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
> fix explorer setting UseLocationAsWorkingDir

- Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Always show/search description in program results if description is enabled in settings. If name and desc are equal the desc is omitted.
This pr is done because an uwp app named "Xbox" but with a description "XboxPcApp". Currently in this case the result title is "XboxPcApp" when description is enabled. In this pr the title will be "Xbox: XboxPcApp".
P.S: The diff view is messy somehow. git blame is fine. Most of the changes are deletion.
Change:
- Always show description if enabled, unless name and description are equal.
Test:
- programs can be searched via name and description
> Always show/search description in program results if enabled

- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
> catch exception when killing unused jsonrpc process

- Flow.Launcher.Infrastructure/Hotkey/HotkeyModel.cs
- Flow.Launcher/HotkeyControl.xaml
- Flow.Launcher/HotkeyControl.xaml.cs
- Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
- Prevent user from setting single "Alt" "Ctrl" "Shift" "Win" as hotkey. Fix #1755.
- Prevent setting single alphanumeric key as hotkey.
- - When a pressed hotkey is unavailable, stay focused inside the text box so user can continue to try a new hotkey.
- When clicked away and the hotkey is unavailable, return to the previous set hotkey.
Tests:
- Toggle hotkey can be modified.
- Preview hotkey can be modified.
- Single special key can't be set as hotkey.
- Single function key can be set as hotkey.
- Single alphanumeric key can't be set as hotkey.
- When a pressed hotkey is unavailable, stay focused inside the text box so user can continue to try a new hotkey.
- When clicked away and the hotkey is unavailable, return to the previous set hotkey.
> Validate hotkey when setting it

- Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
- Flow.Launcher.Test/FilesFoldersTest.cs
- Flow.Launcher.Test/Plugins/ExplorerTest.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Exceptions/EngineNotAvailableException.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Changes:
- Fix #1802 (Fix null subtitle when creating disk result)
- Fix #1796 (Only expand environment var when path starts with %)
- Use case-insensitive comparator for path results
- Use api for subpath check
Tests:
- A single ":" when excluded path is not empty won't cause exception. (1802)
- Unit test for environment path expansion
- Unit test for subpath check
- Unit test for result comparator
> Fix bugs in explorer plugin

- Flow.Launcher.Core/Updater.cs
- Flow.Launcher/App.xaml.cs
might close https://github.com/Flow-Launcher/Flow.Launcher/issues/1504
Note:
I am not so sure why the autoupdater may crash flow itself...I guess it is because the Elapsed callback is triggered from the main thread, but I cannot find evidence to support it, because based on document, this happens only when SynchronizingObject is set which is not we have done.
Though, I have suppressed the error of general exception from updater, so now at least it will be safer to use the autoupdater.
> Safer Updater

- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
Change the shortcut for the `Plugin Indicator` plugin  to `?`, to make the Out Of The Box experience better for new users of Flow.Launcher
Closes #1825
> Change the default shortcut for Plugin Indicator to `?` #1825

- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingAPI.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchOption.cs
This option makes searching take into account the full path of a file at once, instead of "chunks of the path delimited by "/" (folder separator)".
For example:
I have a folder `D:/all/wallpapers/artstation/pics and nested folders here`
In `Everything`, if i enable `Search` -> `Match Path` (<kbd>Ctrl</kbd>+<kbd>U</kbd>) i can simply type `wall arts` and it shows me all the correct files. It matches the folder `D:/all/wallpapers/artstation/` and everything underneath it.
With FL, before this feature, i have to type `wall*/arts` to have the same. Typing `wall*arts` does not work either.
Basically i have to:
1. add `*` to instruct "match all characters after `wall` until folder separator
2. add `/` (folder separator) because  `*` character does not match it
With this feature, it is enough to …
> Everything Search: Match Path 

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/BookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/CustomFirefoxBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Models/CustomBrowser.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml
Close #1856 
Add a combobox in add custom browser dialog to choose browser engine (chromium or Firefox)
Test:
- Firefox bookmarks can be searched by adding data folder path to custom browser
> [Bookmarks Plugin] Add custom firefox browser support

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
> add option for everything search in full path (default true)

- Flow.Launcher.Infrastructure/Hotkey/HotkeyModel.cs
- Flow.Launcher/HotkeyControl.xaml.cs
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
- Check if preview hotkey is a valid KeyGesture when setting and loading
- Ban more printable characters
- Automate fix for #1755.
- Fix #1927.
- Invalid preview hotkey in settings.json won't crash.
- Invalid preview hotkey or toggle hotkey can't be set.
> Fix preview hotkey issue

- Flow.Launcher/Resources/Dark.xaml
- Flow.Launcher/Resources/Light.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/SearchSource.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SearchSourceSetting.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml.cs
- Fix #1956 
- Fix #1948 
- Fix Enabled Label in Source Setting Window
> Remove Obsolete Property and use Status Property for Sorting

- Flow.Launcher/ViewModel/PluginStoreItemViewModel.cs
- Resolve https://github.com/Flow-Launcher/Flow.Launcher/issues/1979
- Previously, we simply compared string differences. In this version, we changed it to only determine if it was high in the dotnet's version format.
> Fix Wrong Version Check in plugin store

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
- Changed the size of the preview area to be resizable with mouse dragging.
- The size is reset when turned on and off. As long as the process is alive, the size you changed will be retained.
- Is it a good idea to save this size? I'm having a little trouble with this.
> Add Grid Splitter for preview resizing

- .github/actions/spelling/expect.txt
- Flow.Launcher/Flow.Launcher.csproj
Since we will be moving to a new UI framework in the future, this is an interim fix for notification platform unavailable error caused by ModernWpfUI version bump from https://github.com/Flow-Launcher/Flow.Launcher/pull/1773. 
ModernWpfUI v0.9.5 introduced [change around WinRT usage](https://github.com/Kinnara/ModernWpf/pull/451) that causes notification platform unavailable error for flow on some machines.
Context:
Tests:
Win 10:
- Notification shown for plugin data reload
- Notification shown for plugin already installed
- Notifications shown for plugin install process
- Plugin Store plugin install pop up is shown
- Resizing preview window
- Increasing/Decreasing width of search window via hotkey
- Increasing/Decreasing maximum displayed result rows via hotkey
Win 11:
Same tests as …
> Interim fix for notification platform unavailable error

- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
When dealing with duplicates, try to preserve the shortcut in start menu.
Test:
- Dup removed  (second onenote is from registry)
> Prioritize shortcut in start menu

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
When starting up for the first time, the 'Remember Last Position' setting does not work well. Search window shows up top lefthand corner. This change makes it to follow the cursor, so users with multiple monitors using flow for the first time can benefit.
Relates to #1978
Before
After
> Change default search window position to follow cursor

- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
As mentioned in #2132 , I have added the two APIs to help plugins hide MainWindow
> Add plugin API: HideMainWindow(), IsMainWindowVisible()

- Flow.Launcher/SettingWindow.xaml.cs
Fixes #2049.
Hello everyone! This is my first time contributing to Flow Launcher, and I am very new at C# in general. My goal is (hopefully) get all the latest plugins into the store and show all the most up-to-date installed plugins, and allow the search function to work even after the refresh button is clicked. Can anyone check that the implementation is correct, and if not, let me know if there are any fixes? 
Thanks so much!
> Plugin Store search (should) work after refresh button clicked

- Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ResultHelper.cs
Fixes #1396.
What I am trying to do in this PR is that we run the process as normal, and if the process throws an "elevated permission error" (belonging to Win32Exception), it tries again with elevated permissions, and if that doesn't work, we throw. My (hopeful) reasoning is that we don't want to elevate permissions right from the get-go and only elevate when we need to.
Again, I'm pretty new to the codebase and C# in general, so feedback is greatly appreciated!
> Fix: Add admin permissions when non-admin doesn't work

- Flow.Launcher/Flow.Launcher.csproj
- Scripts/post_build.ps1
AppVeyor now [has the nuget CLI pre-installed](https://www.appveyor.com/docs/windows-images-software/#tools) in the build image we use (version 6.5.0 atm), so we no longer need to manually install and alias it in our build script.
closes #2057
> Remove NuGet.CommandLine package dependency

- Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
- Plugins/Flow.Launcher.Plugin.ProcessKiller/ProcessHelper.cs
> plugin/ProcessKiller: honor "Last Query Style" after kill

- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/PublicAPIInstance.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
In this commit, several changes were made to improve the copying functionality in the application.
1. In the `MainViewModel.cs` file, an empty string was replaced with a `CopyText` field. This field is used to store the text to be copied. The logic for copying was also updated. Instead of solely checking if the input string was empty, the code now determines whether the input represents a file or folder. If it does, the file drop list is set on the clipboard with the appropriate path. If not, the input text is set as the data object on the clipboard. This change allows for better handling of different types of content to be copied.
2. In the `MainWindow.xaml.cs` file, the `OnCopy` method was modified. Previously, it only checked if there was no selection in the `QueryTextBox` before …
> Consistent handling of clipboard copying

- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.Program/Settings.cs
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
- Make use of cache. Add expiration time (30 hours) to program cache on disk. 
- 24 hours is too short. If I turn on my PC about the same time everyday I'd have a 50% to index every time. 30 hours is basically bi-daily.
- Note that it doesn't immediately refresh cache when it expires. i.e. If you keep Flow running for more than 30 hours it doesn't reindex. Next reindex is done on next startup. This is intended because this PR is focused on reducing CPU and disk usage during init.
- Stop indexing on init when cache on disk existing and not expired. Significantly reduce CPU and disk usage.
- Save cache right after indexing.
- Cache can be saved and loaded.
- No indexing on init when cache is not expired.
- Indexing is done on a first-time startup.
> Reduce CPU and disk usage during Program plugin init

- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/PublicAPIInstance.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ContextMenuHelper.cs
**Context:**
Following on from #2143, further refactor and making copy consistent throughout flow.
**Changes:**
1. Updated CopyToClipboard API method
a. Added directCopy parameter for directly copying files/folder
b. Added showDefaultNotification parameter to allow caller to suppress the method's notification and provide its own
c. Move actual copy code away from ViewModel, they do not need to live there
2. Nothing is using `TryToCopyToClipBoard` method, removed.
3. This error occurs occasionally when using Clipboard.SetText call rather than SetDataObject.
4. Added CopyText for Shell plugin
**Tested:**
1. Copy selected query does not show notification
2. Copy Bookmark plugin result copies the url
3. Copy Shell plugin result copies the command
5. Explorer Context Menu result 'Copy Path' …
> Refactor clipboard copying

- Flow.Launcher.Plugin/Query.cs
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
This quick PR introduces the following changes:
1. the `IsReQuery` property is added to the `Query` class, which will be set to `true` whenever a Query is re-executed.
2. the `Ctrl + R` key binding is added for quickly re-executing the current query.
This enables `Ctrl + R` to act as a "refresh" mechanism. When users type a query and the shown results seem out-of-date (for example, due to caching), they can hit `Ctrl + R` to get fresh results.
The Github plugin caches all query results to avoid rate-limits (and because the Github API is pretty slow). When the user tries to list the issues for a repository, they are likely to get cached results, and therefore recently created issues may be missing. `Ctrl + R` can be used to signal the plugin to skip the cache and load the repository's …
> Improvements for re-queries

- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Plugins/Flow.Launcher.Plugin.Shell/Settings.cs
- Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml
- Plugins/Flow.Launcher.Plugin.Shell/ShellSetting.xaml.cs
Add `Pwsh` as a shell option. Powershell users would probably prefer to use Pwsh over the old `(Windows) Powershell` that ships with Windows.
This raises everyone's favorite problem: how to name each case to distinguish between v5 (`Windows Powershell`) and v7.x (`Powershell (Core)` or `Pwsh`). Thoughts welcome...
( changes partly picked from #1116 )
> plugin/shell: support Pwsh (PowerShell 7.x)

- Flow.Launcher.Plugin/ActionContext.cs
- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Flow.Launcher.Plugin/Interfaces/IContextMenu.cs
- Flow.Launcher.Plugin/Interfaces/IPluginI18n.cs
- Flow.Launcher.Plugin/Interfaces/ISavable.cs
- Flow.Launcher.Plugin/PluginInitContext.cs
- Flow.Launcher.Plugin/Query.cs
- Flow.Launcher.Plugin/README.md
- Flow.Launcher.Plugin/Result.cs
- README.md
Started wanting to update the Readme to mention `Ctrl+R` after https://github.com/Flow-Launcher/Flow.Launcher/pull/2174#issuecomment-1588820459 ... ended up doing a documentation pass in the `Flow.Launcher.Plugin` package.
I also updated the plugin readme and made it show up on the nuget page.
> Update Plugin documentation

- Flow.Launcher.Plugin/Result.cs
Fixes #2201.
The current equality implementation for `Result` does not check for differences in `AutoCompleteText` or `CopyText`.
> fix: :bug: check autocomplete and copy text for `Result` equality

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Added a slider in Appearance to adjust the length of the open animation for the launcher. 
By default the animation should be the same as it was previously (the first part of the animation is about 10ms shorter so that the ratio is simpler - 2/3 instead of 25/36).
Currently only has language support for English and the length is adjustable from 100ms to 2000ms in steps of 10ms.
> Added Animation Length slider

- Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
- Flow.Launcher.Core/ExternalPlugins/CommunityPluginStore.cs
- Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Main.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Added an abstraction for **community plugin stores**, which can be configured with one or more manifest file URLs (for example, a Github link and a few CDN links). When fetching plugin data, all manifest file URLs are used until one of them succeeds. This fixes issues with geo-blocking such as #2195 without compromising performance.
For the moment we only have one plugin store (the PluginsManifest repository), but this concept can be expanded later to be fully customizable and to support unofficial plugin communities (see #2178)
Using `Ctrl+R` from a `pm install` or `pm update` query will result in fetching plugin data from the primary manifest URL, which is a github link. This will bypass any configured CDN links and force Flow to get the latest data, which helps with #2048
PS: I had a …
> Rework how we fetch community plugin data

- .github/workflows/winget.yml
As discussed in #2218 I have updated the winget release action to only fire manually, as a temporary solution to #2086
> Switch winget release action to manual

- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
Fix for #2270 
Ignore 'file:' windows search results as they produce URI constructor exception.
> Fix windows search empty paths

- Flow.Launcher.sln
Context:
Currently on a fresh clone of the project, when the solution is opened up in Visual Studio it has Flow.Launcher.Test set as startup.
Change:
This small convenience change makes it so that the main flow project is the startup project after a fresh clone.
Tests:
Clone the project down in sandbox env and open in Visual Studio, able to just press F5 to run as the project is already set as the startup project.
> Set main Flow Launcher project as default start up

- .github/actions/spelling/expect.txt
- Flow.Launcher.Core/ExternalPlugins/Environments/PythonEnvironment.cs
- Flow.Launcher.Core/Flow.Launcher.Core.csproj
Context:
Close #2176
Changes:
Upgrade Embeddable Python used by Flow to v3.11.4 from 3.8.9.
Upgrade will be silent.
Tests:
- Only the Embeddable Python is upgraded, custom Python location set by user will not
- Automatically and silently upgraded to v3.11.4
- Tested all current Python plugins via this PR https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/261, only one Python plugin is not compatible and failed running on v3.11.4
**TODO:** Update documentation
> Update Python to v3.11.4

- .github/actions/spelling/expect.txt
- .github/workflows/default_plugins.yml
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Context:
Allows the user to reinstall a default plugin from the Store instead of having to reinstall flow entirely.
Changes:
- All default plugins have their own [repo](https://github.com/orgs/Flow-Launcher/repositories?q=flow.launcher.plugin.&type=all&language=&sort=) for holding their releases
- Use workflow to publish plugins to their repo if their plugin.json is modified
- The actual installation code checks a plugin's ID against a list of default plugin IDs, if matches a default plugin's ID the install directory is changed to the program directory's plugin folder instead of the usual UserData location. This ensures that when flow is updated the default plugins are also reinstalled, otherwise if placed in UserData directory then will end up with duplicate default plugins.
Tests:
- …
> Publish installable default plugins to Store

- Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
- Flow.Launcher.Test/FilesFoldersTest.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Exclude path is broken because `FilesFolders.PathContains` doesn't return true when two paths are equal.
Tests:
> Fix exclude path check for index search

- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/Languages/en.xaml
Related https://github.com/Flow-Launcher/Flow.Launcher/issues/1923
- Add title bar 
- Add more text
**Before**
**After**
> Improve hotkey registration failure popup

- .github/workflows/default_plugins.yml
Currently not triggering due to the comparison is against the very last commit on master (because 'base' option is not set).
Fix publish default plugins action not triggering:
- Push trigger branch should be 'dev'
- Compare branch should be 'master'
This means once the plugin's plugin.json has been modified and merged into dev branch a publish event should occur which will compare this change between dev and master, and consequently pushes to the plugin's repo.
> Fix publish default plugins action not triggering

- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Fix #2366 
Currently `ExecutableName` property includes file extension like `.exe`. So query "ex" matches any ".exe" in `ExecutableName` property which is unnecessary for Program plugin.
Test:
- "Excel" is prioritized when querying "ex".
> Ignore .lnk target file extension

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
Fix #2158 #2375 
Fixes exception when loading Edge bookmark file with workspace feature enabled.
Tested:
- No errors when starting Flow, when Bookmark plugin and Edge's workspace enabled.
- Bookmarks in workspace can be indexed.
> Add Edge Workspace support

- .github/workflows/spelling.yml
Fix wrong dotnet and php dict file URL. See [here](https://github.com/Flow-Launcher/Flow.Launcher/actions/runs/6462190051/job/17543371187#step:2:462).
Tests:
- [php](https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20230509/dictionaries/php/src/php.txt) and [dotnet](https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20230509/dictionaries/dotnet/src/dotnet.txt) are available.
> [ci skip] Fix missing dotnet and php dict

- Plugins/Flow.Launcher.Plugin.Sys/SysSettings.xaml.cs
fix #2406 
This happens when filtering the result.
> fix a negative width

- Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
https://github.com/microsoft/vs-streamjsonrpc/discussions/959
NewLineDelimitedMessageHandler hasn't supported SystemTextJsonFormatter yet.
Sorry for the change without testing😭I assume this is something that should not cause any issue.
> switch back to jsonmessageformatter

- Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Use `StringMatcher.FuzzySearch()` to search Access links in Explorer plugin to improve search results, like allow searching in pinyin.
- Access links can be fuzzy-searched.
> Use FuzzySearch to search access links

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Flow.Launcher.Plugin.PluginsManager.csproj
- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml
- Delay restart after installing/uninstalling/updating plugins.
-  **Move Install/Uninstall plugin logic to `Core.PluginManager`**
- Disallow modifying a plugin twice in a session.
- New option for Plugins Manger: `AutoRestartAfterChanging`. Default is `false`. (Should we set to true to keep current behavior?)
- Exclude installed plugins from `pm install`
- Exclude modified(i.e. updated/installed/uninstalled in this session) plugins from `pm install` and `pm update` results
- Show plugin remote icons in `pm Install` results.
- Add glyphs for pm context menu
- Reduce messageboxes to improve consistency
- Fix #2419
>  Delay restart after installing/uninstalling/updating plugins

- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
There is some potential of data race between queries.
> Use ConcurrentDictionary for JsonRPC Settings

- Flow.Launcher.Core/Plugin/JsonPRCModel.cs
- Flow.Launcher.Core/Plugin/JsonRPCPluginBase.cs
The `JsonRPCResponseModel` was inadvertently changed and may cause issues with backwards compatibility.
We revert the change to keep compatibility with older plugins.
> Revert SettingsChanges to SettingsChange for backwards compatibility

- Flow.Launcher.Core/Plugin/JsonRPCPluginBase.cs
- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
- JsonRPC plugins are unable to make settings changes unless they have a `SettingsTemplate.yaml` file.
- Plugin's are unable to initiate new setting keys
- Plugin settings are only saved to disk upon exit
> Improve JsonRPC plugin settings

- Flow.Launcher.Plugin/ActionContext.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
Fix the issue when pressing <kbd>Ctrl</kbd>+<kbd>Num</kbd> to open result, the <kbd>Ctrl</kbd>+<kbd>Enter</kbd> action is triggered. 
- close #2191
- close #2425
(on Program and Explorer plugin)
> Ignore modifier key when using key + number to launch result

- Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
> Set default value of `AutoRestartAfterChanging` to `true`

- Flow.Launcher.Core/Flow.Launcher.Core.csproj
- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
- Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
- Update `StreamJsonRPC` and use `System.Text.Json` Formatter
- fix an error of triggering setting panel when configuration is null (I think it is caused by loading default json storage, which is not null)
The sample needs a small revision as now the message is passed with `camelCase` rather than `PascalCase` (which aligns with the behavior of v1)
[Lb0LD5a8.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/13627033/Lb0LD5a8.zip)
> JsonRPCV2 Small revision

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
Strip all newlines and return characters from texted pasted into Flow Launcher's textbox.
Addresses:
https://github.com/Flow-Launcher/Flow.Launcher/issues/2039
https://github.com/Flow-Launcher/Flow.Launcher/issues/2380
> Strip newlines for multi line paste

- .github/workflows/stale.yml
* Increases the number of days until a issue is marked as stale, as We seem to get a lot of issues that are still relevant but marked as stale.
* Include helpful message reminding Team members of the `keep-fresh` label.
> Update stale workflow

- Flow.Launcher/ViewModel/MainViewModel.cs
Flow Launcher currently rebuilds the context menu each time the query changes, leading to potential slowdowns. The process becomes even more sluggish if a context menu result requires a network call.
Implement a memory cache for built results. This optimization ensures that querying the context menu becomes nearly instantaneous, and it enables the caching of expensive results.
The introduction of a memory cache may result in increased memory usage. However, this impact should be manageable, given that the machine would need to load these results initially. The trade-off is justified by the significant improvement in context menu querying speed and the ability to cache resource-intensive results.
https://github.com/Flow-Launcher/Flow.Launcher/assets/535299/94dda425-c73e-47af-9126-2f15196e32 …
> Speed up context menu search

- README.md
- fix [appwrite](https://appwrite.io) logotype
- Markdown improvements
- Replace some HTML links to MD ones
- Hotkeys table is pretty now
> [no ci] README: fix appwrite logo, md improvements

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
add a safety check for https://github.com/Flow-Launcher/Flow.Launcher/issues/2395#issuecomment-1803229966
This seems to be the only place that we didn't check whether property exists.
> add a safety check for getproperty

- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
Reverts https://github.com/Flow-Launcher/Flow.Launcher/pull/2492
Unfortunately this seems to break Windows index. Reverting to original regex allows results to populate once more.
> Fix: Explorer plugin's Windows Index search returning no results

- Flow.Launcher/ViewModel/MainViewModel.cs
When using tab suggestions it is more consistent to prepend the  `ActionKeyword` to the query. Currently the `ActionKeyword` is not added by default and can have unexpected results.
> Prepend actionkeyword to suggestions

- Flow.Launcher.Core/Flow.Launcher.Core.csproj
- Flow.Launcher.Core/Plugin/ProcessStreamPluginV2.cs
https://stackoverflow.com/questions/6266820/working-example-of-createjobobject-setinformationjobobject-pinvoke-in-net
The plugins processes should be killed after flow dies.
> Job Object to kill child processes

- Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SuggestionSources/DuckDuckGo.cs
Fixes #2554. I added DuckDuckGo to the list of web search completion providers. I copied the Google one, changed the name everywhere, changed the API address and correctly handled the situation with an empty query that DuckDuckGo handles differently than Google.
> Implement DuckDuckGo web search suggestions

- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
Settings UI is not loading for newly installed plugins due.
A check for empty settings skips loading a plugin's settings UI if empty. However newly installed plugin's always have an empty settings file.
Tested with a newly installed plugin to verify it's settings UI was fully loaded.
> Remove short circuit check for empty Settings

- Flow.Launcher.Core/Plugin/NodePlugin.cs
Fixes #2553. Nodejs plugins currently aren't working. The reason is always the same: it throws an index out of bounds exception on line 31.
I added line 45 just like in `PythonPlugin.cs` and this exception disappeared. Even though the exception disappeared, plugins still don't work, now for another reason: they except the JSON they receive to have lower-case keys, and they receive them capitalized (`Method` instead of `method`, `Parameters` instead of `parameters` etc). Now they just don't respond with anything.
After I added the same serialization options that were used for C# and Python plugins (lines 31 and 38), Nodejs plugins started working:
> Fix Nodejs plugins not working

- Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
- Flow.Launcher.Core/ExternalPlugins/UserPlugin.cs
#2476 
Ignore any potential null value for struct (DateTime) which causes failed deserialization.
https://docs.microsoft.com/en-us/dotnet/api/System.Text.Json.Serialization.JsonIgnoreCondition?view=net-7.0
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/default-values
> ignore null datetimes for pluginstoreitem

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
Fix for #2598
Take "custom_root" sub-object into account.
> Fix opera bookmarks

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
Solves #2051 #2329 
When pressing ctrl+shift+c, instead of copying the file, it will only copy the path to it, as it's a commonly used shortcut.
> Added ctrl+shift+c

- Flow.Launcher.Core/Plugin/ExecutablePluginV2.cs
- Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
- Flow.Launcher.Core/Plugin/NodePluginV2.cs
- Flow.Launcher.Core/Plugin/ProcessStreamPluginV2.cs
- Flow.Launcher.Core/Plugin/PythonPluginV2.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
~~- Fix Python plugin v2~~
- Fix Node plugin (we didn't redirect input before)
- Fix job process associate to the child process created by program plugin which causes the exit of flow causing the program being created exited.
- Fix JsonRPCV2 plugins setting not sent via query
~~I don't know when but somehow python plugin doesn't pass the required argument which will create start a empty python interactive. So anyone with a python plugin v2 will simply can't run flow...~~
It's not as bad as I anticipated. The argument will still being passed. It's just the place is weird.
> fix node plugin, job object association, v2 context menu

- Flow.Launcher/ResultListBox.xaml.cs
Hide main window when dragging results, so users can see where they're dragging to.
> Hide main window when dragging results

- Flow.Launcher/ViewModel/MainViewModel.cs
Previous behavior:
- Shortcut will be replaced in order they are created, so if two shortcut share same prefix the early one will be replaced even if the later one is longer.
Correct behavior:
- Match longest shortcut first
This only appears when using `@{key}` as this will match prefix.
> match longest shortcut by default

- .github/actions/spelling/expect.txt
- Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
- Flow.Launcher.Infrastructure/Image/ImageCache.cs
- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
Why bother handling the cache ourselves. This pr uses https://github.com/VictoriaMetrics/fastcache for Image Cache. Should resolves #2477 
Tested:
> Use 3rd party for image cache

- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
This PR closes #2390.
I added a new result in the context menu for programs to open the destination folder.
Only in `win32 ` this new result is added, because `UWP` work differently and have no links, so "open containing folder" already opens the correct location automatically
Add `open target folder` option for programs
> Add open target for program shortcuts

- Plugins/Flow.Launcher.Plugin.Program/Main.cs
https://github.com/Flow-Launcher/Flow.Launcher/pull/2508#issuecomment-2028550756
Reindex during initializing Program Plugin, when win32 OR uwp cache is empty, instead of both are empty.
Downside: When user choose not to index uwp in plugin settings, reindex is unnecessary.
Not dev only. it's in release as well.
> Fix program indexing logic when cache is empty

- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
`Result` should be responsible for how it's deep copied and not the context menu method.
Move all deep copy logic into `Result`
> Improve context menu results

- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Show target path in result's hover tooltip. Continuation of #2508.
> Show target path in hover tooltip

- .editorconfig
- Flow.Launcher/Converters/BoolToIMEConversionModeConverter.cs
- Flow.Launcher/Converters/BoolToVisibilityConverter.cs
- Flow.Launcher/Converters/BorderClipConverter.cs
- Flow.Launcher/Converters/DateTimeFormatToNowConverter.cs
- Flow.Launcher/Converters/DiameterToCenterPointConverter.cs
- Flow.Launcher/Converters/HighlightTextConverter.cs
- Flow.Launcher/Converters/IconRadiusConverter.cs
- Flow.Launcher/Converters/OpenResultHotkeyVisibilityConverter.cs
- Flow.Launcher/Converters/OrdinalConverter.cs
- Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
- Flow.Launcher/Converters/StringToKeyBindingConverter.cs
- Flow.Launcher/Converters/TextConverter.cs
- Flow.Launcher/Helper/AutoStartup.cs
- Flow.Launcher/Helper/DWMDropShadow.cs
- Flow.Launcher/Helper/DataWebRequestFactory.cs
- Flow.Launcher/Helper/ErrorReporting.cs
- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/Helper/SingleInstance.cs
- Flow.Launcher/Helper/SingletonWindowOpener.cs
- Flow.Launcher/Helper/SyntaxSugars.cs
- Flow.Launcher/Helper/WallpaperPathRetrieval.cs
- Flow.Launcher/Helper/WindowsInteropHelper.cs
- Switch from block-scoped namespaces to file-scoped
- Reduce nesting by early exiting functions
- Replace `using` block with `using` declaration
- Rename a few private variables for consistency
GitHub's diff viewer behaves weirdly on this one, so I'd recommend reviewing it in an IDE. I don't know about Visual Studio, but in Rider it looks fine.
> Code cleanup: Flow.Launcher/{Converters,Helper}

- Flow.Launcher.Infrastructure/Constant.cs
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/SettingWindow.xaml
- Resolve https://github.com/Flow-Launcher/Flow.Launcher/issues/1919
- You can enter the TrayMenu from the keyboard.
- Changed Toggle Switch to be selectable with keyboard navigation.
- The title of the selected result item is screen-readable.
- This is a basic change, and we can use this as a reference to work with in the future.
- WIN+B -> Move to Flow Launcher Tray Icon -> Press the Context Key in Keboard -> Arrow or Tab
- Read the title of the resulting item in a screen reader (NVDA).
- This requires a lot of additional work, which we will continue to work on later.
- Add screen reader properties to each setting item
- Make context menu items readable
- Allows settings to be set for what to read (including subtitle).
> Support Screen Reader

- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
Previous pr only change the behavior for a command with argument. This pr fixes it.
> Change shellexecute for command without argument

- Flow.Launcher.Infrastructure/Hotkey/IHotkeySettings.cs
- Flow.Launcher.Infrastructure/Hotkey/RegisteredHotkeyData.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/CustomQueryHotkeySetting.xaml
- Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
- Flow.Launcher/HotkeyControl.xaml.cs
- Flow.Launcher/HotkeyControlDialog.xaml
- Flow.Launcher/HotkeyControlDialog.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Resources/Pages/WelcomePage2.xaml
- Flow.Launcher/SettingWindow.xaml
Now that users have the ability to customize many hotkeys in Flow Launcher, we should prevent them from accidentally using the same hotkey for multiple actions.
- ~~Maybe offer the ability to remove the other hotkey directly from the hotkey change dialog?~~
Done.
> Handle duplicate hotkeys in HotkeyControlDialog

- .github/actions/spelling/allow.txt
- .github/actions/spelling/expect.txt
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromeBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/BookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/CustomChromiumBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/CustomFirefoxBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/EdgeBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/IBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Models/Bookmark.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Models/CustomBrowser.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Models/Settings.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/CustomBrowserSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Views/SettingsControl.xaml.cs
Mostly just moving from block-scoped namespaces to file-scoped, and renaming private properties to start with `_` for consistency.
There are a few other minor changes that I will address in comments.
Since GitHub's diff view doesn't work well for migrating from block-scoped to file-scoped namespaces, and as it turns out, Rider also doesn't display it well when looking directly at the pull request, I suggest pulling this branch in Rider locally and looking at the diff there as it seems to work correctly when the diff is local.
> Code cleanup: Flow.Launcher.Plugin.BrowserBookmark

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
Fix incorrect game mode hotkey and add requery hotkey.
> Fix hotkey guide in settings

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/2595
- When the window is visible, it blocks mouse hover events. 
- Fixes a situation where the mouse is recognized when the up or down arrow key is pressed and held while the mouse is over a window.
> Block Mouse Hover event when Show / Keyboard Navigation

- Flow.Launcher/SettingWindow.xaml.cs
- Fixed getting stuck in the upper left corner when opening the settings window after the first launch.
- If Setting Window Position is null, center the screen.
I think I made it this stupid for a reason, but I can't remember. 
Needs to be reviewed to see if null is acceptable.
When you open the settings window after the first launch with no settings, it is displayed in the center of the screen.
> Fix SettingWindow's LeftTop Position when first launch

- Flow.Launcher/Resources/Controls/ExCard.xaml
- Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
> Fix Xaml Binding Errors

- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.Program/Settings.cs
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Closes #2717.
This PR adds an option in Program plugin to hide uninstallers from results. It does so by filtering out common uninstaller file names if the program is of type `Win32`. For `UWPApp` it does nothing.
> Program plugin: add option to hide uninstallers from results

- Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
Send a request to jsonrpcv2 when flow is closing.
> add a close overload for jsonrpcpluginv2

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Languages/ru.xaml
- Flow.Launcher/SettingPages/ViewModels/DropdownDataGeneric.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
* Comboboxes in Settings — General now reflect the language change immediately
* Query search precision ComboBox is now also localized
> Real-time updates to ComboBox localization in general pane of settings after changing the language

- Flow.Launcher/App.xaml.cs
Fixes #2620.
I moved HotKeyMapper initialization below InternationalizationManager initialization. After this change, the startup error message is correctly translated.
> Fix startup error message when not able to register hotkey being English-only

- Flow.Launcher/Resources/Controls/InstalledPluginDisplay.xaml
- Flow.Launcher/Resources/Controls/InstalledPluginDisplayBottomData.xaml
- Flow.Launcher/Resources/Controls/InstalledPluginDisplayBottomData.xaml.cs
- Flow.Launcher/Resources/Controls/InstalledPluginDisplayKeyword.xaml
- Flow.Launcher/Resources/Controls/InstalledPluginDisplayKeyword.xaml.cs
- Flow.Launcher/ViewModel/PluginViewModel.cs
I extracted parts of the plugin display component that are only displayed when it's expanded (keyword, bottom part with author, version, directory etc.) into 2 separate controls. Now they render lazily, only after the plugin has been expanded. Before this change, only custom plugin settings were rendering lazily.
Time required to render my list of 31 plugins:
Before (700 ms):
After (400 ms):
This feels wrong to do, but I haven't managed to make virtualization work with plugins being able to expand, which changes their size. With virtualization enabled, it seems to work fine when using the scroll wheel, but if I try to use the scrollbar, the settings window freezes. This PR is the best working solution I have found.
> Improve plugins pane performance in settings

- Flow.Launcher/ViewModel/MainViewModel.cs
This fixes the annoying behavior when you return from the context menu and Flow resets the selected item to the first one in the list. This was happening because Flow was re-running the last query every time the user would return from the context menu. Now it doesn't. Instead, now it restores the previous list of results without re-running the query.
> Don't re-run queries after returning from context menu

- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/app.manifest
- ref https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process
- from https://github.com/microsoft/PowerToys/pull/32882
- Fixes blurry window when DPI is changed in dual monitor state.
- Previously, in two DPI states, the behavior was based on the DPI of one side, causing problems with sharpness on the other side. After this change, it will render to the DPI of each monitor.
- 10 You must have at least two monitors.
- 20 In an flow(dev), change the dpi to see what happens when you get a blurry state (175, 200, 225, 250...)
- 30 build this PR
- 40 goto 20
> DPI per Monitor

- Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
Use binding for values introduced in Resizable PR to simplify code.
Tests:
> Use binding for values introduced in Resizable PR

- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Now it displays the actual hotkey instead of `{0}`.
> Fix "always preview" card subtitle not displaying the hotkey in Settings — General

- .cm/gitstream.cm
No need for a label when no screenshot
> Remove no-screenshot labelling from gitStream

- .cm/gitstream.cm
- .github/workflows/pr_milestone.yml
- Added auto assign milestone GitHub action
- Fixed gitStream screenshot request configuration issue
> Add auto assign milestone GitHub action

- Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml
- Add Style for hiding separator when turning off all "more info" state in preview panel
- The bottom separator should be hidden when no additional information is displayed.
> Fix Preview Panel Separator

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/PublicAPIInstance.cs
- Flow.Launcher/SelectFileManagerWindow.xaml
- Support for opening tab in exist window when using qttabbar.
- Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/2790
- Added a QtTabBar in "File Manager" entry. 
- For new installations, the qttabbar setting is listed.
- Existing users are not listing. but if user add and select "qttabbar" (in name. case-insensitive), it will behave as a qttabbar.
> Support QTTabBar

- .cm/gitstream.cm
remove cm's percent new code automation + ignore dev and l10n_dev branches
> Remove cm percent new code automation & ignore specific branches

- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Fix to allow env variable be used as part of a path
Close https://github.com/Flow-Launcher/Flow.Launcher/issues/2301
> Fix partial env variable path search

- .cm/gitstream.cm
Fix gitStream image request regex- wasn't capturing pasted image
> Fix gitStream image request regex

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
- User can add file types through Explorer Settings which should be ignored in search results.
- Partially fixes #2144 since there was another idea to filter certain folders.
> feat: Exclude certain File Types from the Index search result

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Core/Resource/Internationalization.cs
Fixes issue from https://github.com/Flow-Launcher/Flow.Launcher/pull/2769
> Fix startup localization issues

- Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
Fixes #2882.
Date and Time previews are using `CurrentCulture` which is incorrect.
In order to use the correct UI culture managed by FlowLauncher, they should be using `CurrentUICulture`.
> Fix ClockText and DateText to use CurrentUICulture

- Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
`MaxResult` value in `Settings.json` was ignored for *Everything* searches. Pass the value to `EverythingApi` for all searches.
Fixes #2873.
> Pass MaxResult setting to EverythingApi

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
- Resolve https://github.com/Flow-Launcher/Flow.Launcher/issues/2821
- Added "Enabled" Column
> Add "Enabled" Column in Customize Action Keyword Tab

- .github/workflows/top-ranking-issues.yml
Automatic action to update a new dashboard issue showing top feature & bug issues
> Create Top-Ranking Issues workflow

- Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/2901
Tested select working for .exe files.
> Fix Node.js path select error in settings window

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
> Release version bumps

- .cm/gitstream.cm
Update gitstream.cm minutes to review trigger rule
> Update gitstream.cm minutes to review trigger rule

- Flow.Launcher/MainWindow.xaml.cs
https://github.com/microsoft/PowerToys/pull/33784
Tested with @Garulf about the correct position compared to the current release 1.19
> Fix Multiple Display different DPI causing weird staring position

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
> Release 1.19.3 version bumps

- Flow.Launcher/Helper/WindowsMediaPlayerHelper.cs
> Null check when detecting Windows Media Player installation

- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
> fix out of index error when install source is not standard github link

- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
Closes #3056.
The button in `inputWithFileBtn` in `SettingsTemplate.yml` wasn't working because the button was created and displayed, but it had no click listener attached.
While fixing this, I found out that it's not easily possible to make a dialog that would let the user selected either a file or a folder. It's always either a dialog for selecting only files or a dialog for selecting only folders. Considering this, I also added another type of possible input for JS/Python plugins: `inputWithFolderBtn`.
I added static imports (`using Checkbox = ...`, `using ComboBox = ...`, etc.) because I needed to add the import statement for `System.Windows.Forms`, but as soon as I added it, it started complaining about ambiguous imports: it didn't know whether it's supposed to use UI components from …
> Fix `inputWithFileBtn` not working in SettingsTemplate.yml

- README.md
> Add sponsor to readme

- Flow.Launcher/App.xaml
- Fixed an issue where windows os built-in highcontrast mode caused by a crash or the context menu color does not come out properly
- Processes to just call the dark style when highcontrast mode is on
- Technically we need to support high contrast mod style separately, but this is currently difficult to make and we have a separate built-in theme system, so this kind of support is enough.
> Fix Style for Highcontrast mode

- .cm/gitstream.cm
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1ijFr6wJb6bw00lvWmnabixQfJQAD9Q%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=HOTZUVl)
This pull request includes a small change to the `.cm/gitstream.cm` file. The change updates the regular expression pattern used for matching branch names to be case-insensitive for "Dependabot" and "Renovate".
* [`.cm/gitstream.cm`](diffhunk://#diff-065a0926b6e84a4f4a9ccff59eecfa8960bd0fb2a013dfbb75e2770c35cbfb75L13-R13): Updated the regular expression pattern to match both uppercase and lowercase versions of "Dependabot" and "Renovate".
> Suggest fix regex in gitstream CM file

- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/WelcomeWindow.xaml
- Flow.Launcher/WelcomeWindow.xaml.cs
Long before, when I have upgraded Flow.Launcher to v1.19.x version, I encountered the setting window navigation issue like this:
(Note: This is just a demo screenshot. I just cannot find the original screenshot. :( I forget to create a issue for this.)
Now, I fix this possible issue to make sure the navigation event will only happen after all ui components are loaded. (I guess this is the problem)
> Fix possible content frame navigation issue in welcome window & setting window

- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
- Flow.Launcher.Plugin/Result.cs
Also, bit of silly sanitizing data (accept only `data:image`)
Any documentation changes needed?
> Return data uri image as icon support

- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
Improve windows index search with special character like `\@\＠\#\＃\&\＆＊_;,\%\|\!\(\)\{\}\[\]\^\~\?\\""\/\:\=\-`.
If you type `Zotero & Obsidian` in search bar, the command will look like this:
```
SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType" FROM "SystemIndex"
WHERE CONTAINS(System.FileName,'"Zotero*" AND "&*" AND "Obsidian*"',2057)
AND scope='file:' ORDER BY System.FileName
```
And `"&*"` can cause issue like this:
```
17:34:42.0030+08:00 - ERROR - WindowsIndex.ExecuteWindowsIndexSearchAsync - Failed to execute windows index search query: SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType" FROM "SystemIndex" WHERE (System.FileName LIKE '8+16%1%' OR CONTAINS(System.FileName,'"8+16*1*"',2057)) AND scope='file:' ORDER BY System.FileName
EXCEPTION …
```
> Improve windows index search with special character

- Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
Closes #3128.
This PR adds two more date format options to settings:
* `dd.MM.yy` (`15.12.24`)
* `dd.MM.yyyy` (`15.12.2024`)
> Add more date formats in settings

- Flow.Launcher.Core/Resource/AvailableLanguages.cs
> add Hebrew in available languages

- .github/workflows/pr_assignee.yml
- .github/workflows/pr_milestone.yml
- added permissions, so it should fix `Resource not accessible by integration`
- migration from https://github.com/thomaseizinger/assign-pr-creator-action (archived from oct. 2023) to https://github.com/toshimaru/auto-author-assign (last commit 6 months ago)
> ci: fix permissions + migrate to fresher action (Pr Assign)

- .github/workflows/pr_assignee.yml
- .github/workflows/pr_milestone.yml
Small addition to #3117 ( [Discussed here](https://github.com/Flow-Launcher/Flow.Launcher/pull/3117#discussion_r1891426832) )
> ci: pull_request_target & remove useless secret

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
Closes #3116. My IDE also removed a bunch of unnecessary whitespace when I edited these files. I thought it's not a big deal and that whitespace should have been removed anyway, so I didn't exclude those changes from the PR.
These changes introduce two new options to Last Query Style in settings: "Preserve Last Action Keyword" and "Select Last Action Keyword". They work just like "Preserve/Select Last Query", but only for action keywords, not for whole queries. With these options, when there is an action keyword, the next time the user opens Flow Launcher, the query is set to `keyword ` (with a space after it, so the user can immediately begin typing). If the last query didn't have an action keyword, the query is set to an empty string.
I've tested:
* That the previous options still work …
> Add preserve last action keyword options

- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
1. Fix user result set max value issue
If one plugin set the score of one result to int.MaxValue, `FL` should not add selected count & priority score.
Generally, this plugin want this result to the top of the query list.
2. Add support for removing selected count from score
If one plugin want to force the sequence of its results, it can set the `AddSelectedCount` to false so that `FL` will not add selected count.
Like one plugin with many query items which needs to allow user to set the sequence manually (order by datatime, etc.).
> Add options for setting result on top & keeping result order

- Flow.Launcher/ViewModel/MainViewModel.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
This issue could happen when calling `ResultsUpdated.Invoke` event in `IResultUpdate` interface so fast that main view model cannot complete update event (still execute foreach sentence).
Take `WebSearch` plugin for example, I change its `QueryAsync` function to this:
```
public async Task<List<Result>> QueryAsync(Query query, CancellationToken token)
{
var results = new List<Result>();
for (var i = 0; i < 1000; i++)
{
var result = new Result
{
Title = $"{i}",
SubTitle = $"{i}",
Score = i
};
results.Add(result);
// here we update the results very fast and call results update event
ResultsUpdated?.Invoke(this, new ResultUpdatedEventArgs
{
Results = results,
Query = query
});
}
return results;
}
```
And I can catch the exception in `UpdateResultView` function of `MainViewModel`:
The key of …
> Fix possible result update issue for plugins with IResultUpdate interface

- Flow.Launcher.Infrastructure/FileExplorerHelper.cs
Fix operator equal application issue for #3122
> Fix operator equal application issue

- Plugins/Flow.Launcher.Plugin.PluginsManager/Utilities.cs
Use System.Text.Json to replace Newtonsoft.Json for better performance & Improve code quality
> Use System.Text.Json to replace Newtonsoft.Json for better performance

- Plugins/Flow.Launcher.Plugin.Program/Main.cs
Improve uninstaller check function
> Improve uninstaller check function

- Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
We shouldn't try catch the error when querying, but instead should let flow handle it.
> do not try catch the error for jsonrpc v2

- Flow.Launcher/Helper/SingletonWindowOpener.cs
- Flow.Launcher/SettingWindow.xaml.cs
Fix setting window freeze issue after lock screen (Win+L) or sleep (Some commits seem to change the codes that try to fix this issue 😢)
Improve singleton window opener
Already tested on my computer and it works well now!
Related issue: #3139, #3169, #3187
> Fix setting window freeze issue & Improve singleton window opener

- Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCPublicAPI.cs
#3087 created the `BackToQueryResults` API method, but didn't make it accessible to Jsonrpc-v2 plugins, so this pr lets jsonrpc v2 plugins use the api method
> add BackToQueryResults to JsonRPCPublicAPI

- Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Fix issue when user uses forward slash as directory seperator, like C:\Test/Test.
Related issue in #3229.
> Fix unix directory seperator issue

- Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
When reupdating the plugins manifest, the user plugins cannot be updated which causes plugin store page cannot be refreshed when clicking the refresh button.
If the count of the `UserPlugin` is zero, FL has not loaded the plugins correctly so we need to re-fetch the plugins.
Related issue:
Original:
https://github.com/user-attachments/assets/19709a5b-1cfa-494e-8a31-c2ce3e1a1cc4
Now:
https://github.com/user-attachments/assets/b0c714a5-7fda-49bd-b801-ce2561573c42
> Fix Plugin Store Page Refresh Issue

- Flow.Launcher.Infrastructure/FileExplorerHelper.cs
If the path from the active explorer is already end with backslash, do not add backslash to it.
If the active explorer path is `C:\`, adding `\` to it will cause issues.
Original:
New:
> Improve explorer path parse when path ends with backslash

- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/Storage/TopMostRecord.cs
- Flow.Launcher/Storage/UserSelectedRecord.cs
* The key to identify the record. This is used when FL checks whether the result is the topmost record. Or FL calculates the hashcode of the result for user selected records.
* This can be useful when your plugin will change the Title or SubTitle of the result dynamically.
* If the plugin does not specific this, FL just uses Title and SubTitle to identify this result.
E.g. The records of plugin `Edge Workspace` have subtitles which can change based on the tab number of the edge workspace, but FL should regard these records as the same. (Full issue in https://github.com/cspotcode/Flow.Launcher.Plugin.EdgeWorkspaces/issues/3)
More details in #3178.
* `Title` and `SubTitle` of the `Result` should be the properties for display, and `RecordKey` can be the property for identification. That way …
> New API for Record Key of Results & Fix Result Clone Issue

- Flow.Launcher.Core/Plugin/PythonPlugin.cs
- Flow.Launcher.Core/Plugin/PythonPluginV2.cs
Currently, due to Flow Launcher using embedded Python by default, plugin directory doesn't get added to path. This causes inconvenience for plugin developers. The plugin development documentation for Python suggests using `./lib` for installing dependencies and `./plugin` for actual plugin code, but developers can't import anything from there because these directories are not in Python's path. They have to add them to path manually in every plugin before they can start importing their code. For example, FlowYouTube plugin:
```py
import sys
import os
plugindir = os.path.abspath(os.path.dirname(__file__))
sys.path.append(plugindir)
sys.path.append(os.path.join(plugindir, "lib"))
sys.path.append(os.path.join(plugindir, "plugin"))
from plugin.main import FlowYouTube
```
We can't simply add …
> Add `.`, `./lib`, `./plugin` directories to path for Python plugins

- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Use `HideMainWindow()` instead of `Application.Current.MainWindow.Hide();` for code consistence
> Use api function to hide window

- Flow.Launcher.Plugin/Query.cs
- Flow.Launcher/Storage/TopMostRecord.cs
- Flow.Launcher/Storage/UserSelectedRecord.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.Program/Main.cs
For those actions in the FL and Program plugin (Pin / Unpin record to the topmost; Disable one program), when you click those records, like pin / unpin it to the topmost without closing the FL, the search bar will be empty and you must need to click `esc` to return back to the query list before any other actions.
Now with new API `BackToQueryList` (#3087), we can improve those behavious.
What's more, we need to remove the context menu cache feature, it can cause the cache of the original wrong context menu.
By the way, I do not think context menu caching is a good idea because the plugin with dynamic context menu will have a bad experience if user open the context menu of the same record twice.
Original:
Now:
https://github.com/user-attachments/assets/b3b3f752-7222-4e3d-8b7f-f9daf3003779 …
> Improve context menu item action response & Fix origin query null exception

- Flow.Launcher.Core/Resource/Theme.cs
- Flow.Launcher/MainWindow.xaml
Because adding drop shadow effect will change the margin of the window border, we need to update the resize thickness of the window chrome to correct set the resize border. Otherwise, scrollbar selection is unable to work because resize area override it.
* Related issue: #3185
Regardless of whether the shadow effect is enabled, the window border remains outside the resizing area.
https://github.com/user-attachments/assets/5619dccf-d8ae-464d-b036-a10d40a5bc34
> Fix main window resize border thickness issue

- Flow.Launcher.Infrastructure/Image/ThumbnailReader.cs
For some files in the recycle bin, we may encounter issue like this:
This can cause:
> Fix Exception When Getting Thumbnails

- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
- Plugins/Flow.Launcher.Plugin.Sys/NativeMethods.txt
Replace them with PInvoke function which can slightly improve execution speed.
* Shutdown & Restart & Restart With Advanced Boot Options & Hibernate action
> Improve Shutdown & Restart & Hibernate in Sys Plugin

- Flow.Launcher.Infrastructure/Hotkey/HotkeyModel.cs
- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/HotkeyControl.xaml.cs
- Flow.Launcher/HotkeyControlDialog.xaml.cs
Split from #3157, this PR focuses exclusively on letting the LWin/RWin to be used for opening flow. It is split so I can add this feature in while I work on the support for key combinations.
Source code for ChefKeys that handles the Win key operations in this change is available at https://github.com/jjw24/ChefKeys.
Most of this code is temporary and will be replaced by PR 3157.
Tested:
- LWin can open flow
- Can not use Win key as part of a combo (will be handled in the other PR)
- Can only use the Win key for open Flow hotkey and not for other hotkey actions
- Once Win key is not used ChefKeys is stopped.
- ChefKeys is only started if Win key is used
Close https://github.com/Flow-Launcher/Flow.Launcher/issues/662, https://github.com/Flow-Launcher/Flow.Launcher/issues/2709, …
> Enable the use of Win hotkey to trigger flow

- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/Languages/en.xaml
Follows on from #3262, adding exception handling.
> Add exception handling for register unregister hotkey

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
* Because old data does not have this key, we should use null as the default value for consistency.
* Because FL will change the score property of the results during results update, so before we update the results, we need to deep clone the result list, so that plugin can cache them for performance improvement (like Flow.Launcher.Plugin.Program).
This can fix issue in #3203. Tested.
> Fix Issue that Plugin Cannot Cache Records

- Flow.Launcher.Core/MessageBoxEx.xaml
When we disable `Hide FL when loss focus` option, we need to make `MessageBoxEx` window topmost so that it can show in the top.
Already tested.
> Make Message box Window to be Topmost

- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.Program/Settings.cs
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
For Program plugin, we can get results with duplicated apps. (One is Win32 app, another is UWP app.)
So I add option to let us remove the duplicated apps.
I remove the Win32 apps instead of UWP apps because the name, description and some other properties of Win32 apps are always wrong if these apps are duplicated.
As you can see above, the top item is from Win32 app and its name is `olk` but actually this name should be `Outlook (Classic)` (same as bottom item which is from UWP app).
Settings Panel:
Search:
> Support removing duplicated programs

- Flow.Launcher.Core/Plugin/JsonRPCPluginV2.cs
There's a problem with the current implementation.
`Reload` will restart jsonrpc_v2 plugin, but not calling `initialize`. This may break the plugin state that are not what plugin developer may assume.
There are two solution:
This will be a breaking change regardless, but given the relatively small number of v2 plugin now it should be fine.
@Flow-Launcher/team which one would you think is better?
> Reload Context

- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
fix #3011 
cc [helmesjo](https://github.com/helmesjo)
> resolve link before using File.Replace

- Flow.Launcher/Flow.Launcher.csproj
Fix EventLog access is not supported on this platform exception for installers. Tested.
More in #3273.
> Fix dependency injection issue in installer

- Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
There is `Background="{Binding PreviewBackground}"` in `WelcomePage2.xaml`, but I cannot find this in `WelcomePage2.xaml.cs`, so I believe this brush seems to have been left out.
> Add preview background in welcome page 2

- Flow.Launcher/CustomQueryHotkeySetting.xaml
- Flow.Launcher/CustomShortcutSetting.xaml
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/PriorityChangeWindow.xaml
- Flow.Launcher/ReportWindow.xaml
- Flow.Launcher/ReportWindow.xaml.cs
- Flow.Launcher/SelectBrowserWindow.xaml
- Flow.Launcher/SelectFileManagerWindow.xaml
- Flow.Launcher/WelcomeWindow.xaml
[#4173361](https://github.com/Flow-Launcher/Flow.Launcher/commit/41733615fd75cd35bf3933a90e92b93ae217e09a)
[#44aa17d](https://github.com/Flow-Launcher/Flow.Launcher/commit/44aa17d7c9a2bf1f24f0f8cdec01dcdb9781af61)
Original:
After:
> Improve Report Window Design

- Flow.Launcher/App.xaml.cs
- Flow.Launcher/Flow.Launcher.csproj
> Fix System.PlatformNotSupportedException & Add exception message box in App constructor

- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/ProgressBoxEx.xaml
- Flow.Launcher/ProgressBoxEx.xaml.cs
- Flow.Launcher/PublicAPIInstance.cs
* Minimize button is for users to temporarily hide progress box for this progress when they do not want to check the progress for now. They can view progress if they want from taskbar.
* Background button is for users to permanently hide progress for this progress when they do not care the progress. This will **not** cancel the progress. (It is different from cancel button & close button which is used to cancel the progress.)
* Set progress box topmost since we support to temporarily and permanently hide this window now.
Original:
New:
> Improve Progress Box Design

- Flow.Launcher/Helper/WallpaperPathRetrieval.cs
- Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
* Cache wallpapers
* Freeze images & brushes
* Invoke on UI Thread
* Error handling
* Reopen settings & navigate to appearance page, the wallpaper is loaded
> Improve Wallpaper Retrieval

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/PluginViewModel.cs
We should not initialize API in static constructor or it will create another API instance.
> Fix API instance create twice issue & Make PluginManager.API private

- Flow.Launcher.Core/Plugin/JsonRPCV2Models/JsonRPCPublicAPI.cs
- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
> Add loading bar api functions for all plugins

- Flow.Launcher.Core/Plugin/JsonRPCPluginBase.cs
- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
- Flow.Launcher/ViewModel/PluginViewModel.cs
Follow on with #3260, we can use `NeedCreateSettingPanel` function to check if we need to create settings panel to remove unnecessary calling of `CreateSettingPanel`.
* JsonRPC plugins can create settings panels correctly.
* JsonRPC plugins will not call `CreateSettingPanel` when their `SettingsTemplate.yaml` files do not have any configurations.
> Remove unneccessary CreateSettingPanel by introducing need check

- README.md
Wasn't sure where to put the new sponsor, if I placed them incorrectly, feel free to correct me.
> Add new sponsor to README

- Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
Fix ![image](https://github.com/user-attachments/assets/b9ba7c5d-89aa-4457-9bc0-0363429a6a2a)
We can upgrade this when we move to .net9.
> Revert "Bump System.Data.OleDb from 8.0.1 to 9.0.2"

- Flow.Launcher.Infrastructure/Logger/Log.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Closes #2317 #2313 
Allow users to select log level. Set to "info" by default.
> Allow log level selection

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
> Move log level to about page

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Flow.Launcher/Flow.Launcher.csproj
Update all Fody dependencies to Fody 6.5.5. Currently we have 6.5.5 in infrastructure and 6.5.4 in launcher and plugin.
> Update all Fody dependencies to Fody 6.5.5

- Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
- Flow.Launcher/SettingWindow.xaml.cs
Follow on with #3310.
We should use dependency injection instead of navigation parameter to get instances.
> Use dependency injection instead of navigation parameter

- Plugins/Flow.Launcher.Plugin.Sys/Command.cs
- Plugins/Flow.Launcher.Plugin.Sys/CommandKeywordSetting.xaml
- Plugins/Flow.Launcher.Plugin.Sys/CommandKeywordSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
- Plugins/Flow.Launcher.Plugin.Sys/Settings.cs
- Plugins/Flow.Launcher.Plugin.Sys/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Sys/SysSettings.xaml
- Plugins/Flow.Launcher.Plugin.Sys/SysSettings.xaml.cs
- Plugins/Flow.Launcher.Plugin.Sys/ThemeSelector.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsViewModel.cs
Previously, FL uses the English title & translated title & subtitle to search the commands. If English title is matched, the result title will be in English which I think can cause confusion for users.
This PR Introduces command keyword to replace the original function of searching with English title. (Users can still search with translated title & subtitle) And users can change this command keyword.
By default, the command keywords are the same as the English title. And users can set whatever they like for faster query.
https://github.com/user-attachments/assets/4ae1ee9d-5f97-47bb-a1a7-8d4adf048bf3
* Change command keyword & Search them.
* Name & Description column are now translated.
* Sys plugin can correctly save & load settings.
Close #3343
> Use Command Keyword to Search System Command

- Flow.Launcher/CustomQueryHotkeySetting.xaml
- Flow.Launcher/HotkeyControl.xaml.cs
As you can see, the new version of `HotkeyControl` uses `Type` to specific the `Hotkey` getter and setter.
And previously, the default value of `Type` is `Hotkey` so the `HotkeyControl` in `CustomQueryHotkeySettings` will fallback to `case HotkeyType.Hotkey:`, resulting the change of the search hotkey.
So we need to add a new `enum` type so that `HotkeyControl` will cache the hotkey value and return it as result which is needed for `CustomQueryHotkeySettings` (it uses )
Follow on with #3310.
* Set / Update / Delete custom query hotkey.
> Fix custom query hotkey settings issue

- Flow.Launcher/HotkeyControl.xaml.cs
We should not call RefreshHotkeyInterface here because DependencyProperty is not set yet, and it will be called in OnHotkeyChanged event or Hotkey setter later.
Also fix a local variable issue.
Follows on from https://github.com/Flow-Launcher/Flow.Launcher/pull/3354
> Fix hotkey initialization issue

- Flow.Launcher/MainWindow.xaml.cs
- Enable acrylic effect on first launch if running on Windows 11
- Default backdrop is none.
- Change the backdrop setting to Acrylic on first launch if the conditions are met.
- The first impression improves when the program is launched for the first time 😉
> Enable acrylic effect on first launch

- README.md
Since the current link open a page that redirects you to another one, maybe it's better to just lead to the new page directly?
> Update link to the plugins in README.md

- Flow.Launcher/App.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
When we call other functions that need `AllPlugins`, we should put them after `PluginManager.LoadPlugins(_settings.PluginSettings);`.
* Since FL introduces dependency injection #3175, the constructor of `MainViewModel` is brought forward because `PublicAPIInstance` needs its instance, so we cannot put `RegisterResultsUpdatedEvent()` in its constructor.
* Since `Ioc.Default.GetRequiredService<Internationalization>().ChangeLanguage(_settings.Language);` needs to check plugins with `IPluginI18n` interface, it should be put after `Ioc.Default.GetRequiredService<MainViewModel>().RegisterResultsUpdatedEvent();`
> Fix Plugin Manager Issue

- Flow.Launcher/MainWindow.xaml.cs
- Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/3373
- In the initial launch state, when navigating back from the context menu to the search results, the cursor is incorrectly positioned at the beginning.
- After Hide(), the cursor moves to the end without any issues.
- QueryTextCursorMovedToEnd is triggered whenever the value changes, but it seems it wasn't triggered initially because there was no default value or it was already True. When the window is hidden for the first time, a default value of false is added, which allowed it to function correctly afterward.
- A default value(false) has now been added during OnLoaded.
> Fix cursor doesn't move to the end on initial launch

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Core/Resource/Internationalization.cs
- Flow.Launcher/App.xaml.cs
Follow on with #3365.
Originally, we use `ChangeLanguage` to initialize language & change language, which I think is a little bit unclear.
Now I add `InitializeLanguage` for initializing language and I remove `ChangeLanguage` in `PluginManager` because we only need to call it once.
This function should be called after plugins are initialized because we will call `GetTranslatedTitle` function to update plugin metadata and many plugins use `Context.API` to get its translated titles and descriptions, so we would better to call `InitAsync` before calling this function.
> Fix Language Change Issue

- Plugins/Flow.Launcher.Plugin.ProcessKiller/Main.cs
> Back to original action for UX

- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/Resources/Dark.xaml
- Flow.Launcher/Resources/Light.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
Currently, there are the following issues in the dev branch:
- When show is called while in a mode where the query remains, the clock and search icon are displayed.
- When typing a query in a mode where the query remains, the animation no longer works.
- The QuerySuggestionText overlaps with the clock.
- The search icon overlaps with SearchIcon.
- The clock is no longer shown when show is called while in a mode where the query remains.
- If the query-remaining mode is in an action keyword active state, the search icon is not shown when show is called.
- The _isAnimating variable has been removed. It was used in the old animation system to prevent storing window coordinates while the window was moving. Since the new animation no longer moves the window, this variable is no longer needed. …
> Fix Clock/Search Icon show logic

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
Fix first-time window flicker.
Fix clock panel flicker.
> Fix first-time window flicker & clock panel flicker issue

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
When application is shutdowning, `Application.Current` will be null.
> Fix application null exception & Remove unused MainWindowOpacity property

- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
- Added glyph icons for Sys Plugin
- Adjust some glyphs
> Add glyph icons for Sys Plugin

- Flow.Launcher/Helper/WallpaperPathRetrieval.cs
- Flow.Launcher/Resources/Pages/WelcomePage1.xaml
- Flow.Launcher/Resources/Pages/WelcomePage2.xaml
- Flow.Launcher/Resources/Pages/WelcomePage5.xaml
- Fix Preview in Welcome Window
- Adjust BG Color
- Fix aspect ratio wallpaper bitmap
> Fix Preview in Welcome Window & Wallpaper Retriever Improvement

- Flow.Launcher/ViewModel/MainViewModel.cs
> Fix Application.Current null exception

- Flow.Launcher/ViewModel/MainViewModel.cs
> Remove search delay debug codes

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Resources/Controls/Card.xaml
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
- Reordered the settings items and changed some items to expandable card type
- Changed items that were previously shown only when enabled to use expandable sections instead.
- Replaced the theme creation guide link with the Theme Builder link
- Fix Padding for InsideFit card
- Add subtext indicating whether backdrop is available
> Organizing the settings page

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
> Add clean cache option & Add exception handler for cleaning folders

- Flow.Launcher.Core/Updater.cs
- Flow.Launcher.Infrastructure/Helper.cs
- Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
- Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
- Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
- Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
Move `Flow.Launcher.Infrastructure.Format` function to `Updater.cs` since this function is only used by `Updater.cs`.
Move `ValidateDataDirectory()` and `ValidateDirectory()` function in `Flow.Launcher.Infrastructure` project to `FilesFolders.cs` since they are functions related to directory and `Program` and `WebSearch` plugin use them so we would better to put them in `Flow.Launcher.Plugin` project for all plugin usage.
> New API Function ValidateDirectory and ValidateDataDirectory & Cleanup Helper.cs in Flow.Launcher.Infrastructure project

- Flow.Launcher.Core/Configuration/Portable.cs
- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
- Flow.Launcher.Core/Updater.cs
- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
- Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
- Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
- Flow.Launcher.Infrastructure/Win32Helper.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/Notification.cs
- Flow.Launcher/PublicAPIInstance.cs
Since #3367 has introduced `Application.Current.Shutdown` for app dispose, using `Environment.Exit(0)` will cause issue.
```
// If we call Environment.Exit(0), the application dispose will be called before _mainWindow.Close()
// Accessing _mainWindow?.Dispatcher will cause the application stuck
// So here we need to check it and just return so that we will not acees _mainWindow?.Dispatcher
```
Before restarting app, we should wait `ImageLoader.SaveAsync`.
Make multiple thread safe.
Use try when calling `JsonStorage` and `BinaryStorage` save.
> Fix environment exit & Wait image cache save before restarting & Add settings saving lock & Do not crash when caught exception saving

- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/MainWindow.xaml.cs
Initialize hotkey after main window is loaded because when main window is loading, it will change main window visibility state which can possibly cause conflict when hotkey operation like toggling main window visibility.
When we close FL, we should wait cache saved before closing app.
> Initialize HotKeyMapper after window is loaded & Wait image cache saved before closing main window

- Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
I think it is okay to set max result lower limit to 1.
Fix #3341
> Set max result lower limit to 1

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Core/Plugin/PluginsLoader.cs
- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
- Flow.Launcher.Infrastructure/Stopwatch.cs
- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/PublicAPIInstance.cs
- Plugins/Flow.Launcher.Plugin.Program/Main.cs
Added new api functions to helper csharp plugin developers quickly log debug & info message with function executing time.
```
/// <summary>
/// Log debug message of the time taken to execute a method
/// Message will only be logged in Debug mode
/// </summary>
/// <returns>The time taken to execute the method in milliseconds</returns>
public long StopwatchLogDebug(string className, string message, Action action, [CallerMemberName] string methodName = "");
/// <summary>
/// Log debug message of the time taken to execute a method asynchronously
/// Message will only be logged in Debug mode
/// </summary>
/// <returns>The time taken to execute the method in milliseconds</returns>
public Task<long> StopwatchLogDebugAsync(string className, string message, Func<Task> action, [CallerMemberName] …
```
> New API Function from Stopwatch & Improve Program Plugin

- Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Resources/Controls/InstalledPluginDisplay.xaml
- Flow.Launcher/Resources/CustomControlTemplate.xaml
**Before**
**After**
- Fixed a visual issue where the NumberBox appeared editable when disabled
- especially noticeable in the dark color scheme 
- When the setting was turned off, I could attempt to edit without understanding why it wasn’t working
- Added immediate tooltip on mouse hover.
- Tooltip clarifies that "Search Delay must be enabled in General to edit."
- Restored a string that Jack had previously removed. https://github.com/Flow-Launcher/Flow.Launcher/pull/3396/files#r2038439277
> Adjust Numberbox Design & Revert PositionResetToolTip string

- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
For the elements in `Gird.Column="1"`, we should use `SettingPanelItemLeftTopBottomMargin`.
> Fix explorer settings panel margin

- Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
Check directory before saving storage to fix `System.IO.DirectoryNotFoundException: Could not find a part of the path`.
Add old constructor for old `Program` plugin.
Fix #3451.
> Fix storage save directory issue

- Flow.Launcher.Core/Plugin/PluginManager.cs
- Flow.Launcher.Core/Resource/Internationalization.cs
- Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
- Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
- Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/Helper/ErrorReporting.cs
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/PublicAPIInstance.cs
Tested. When plugin throw exception during saving & disposing, the application can exit normally.
Make `DirectoryPath` is not null. Follow on with #3452.
Fix #3453.
> Improve FL Exiting & Exception Handler

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/Converters/BadgePositionConverter.cs
- Flow.Launcher/Converters/SizeRatioConverter.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
- Flow.Launcher/Themes/Win11Light.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultViewModel.cs
- Flow.Launcher/ViewModel/ResultsViewModel.cs
- Make Result badge great again.
- Add `BadgeIcoPath` string & `BadgeIcon` icon delegate & `ShowBadge` bool property in `Result` class so that plugins can change the results of their  badges.
- Fix global search determination issue in `MainViewModel`. (`if (query.ActionKeyword == Plugin.Query.GlobalPluginWildcardSign)`)
Related #2721. Close #2517.
- Setting the result badge
- Show the result badge
> Result Badge

- Flow.Launcher.Infrastructure/Win32Helper.cs
- Flow.Launcher/HotkeyControl.xaml.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginsViewModel.cs
- Fix the following error: an exception occurs when the Content Dialog in ModernWpf has no Owner set.
```
05:49:12 Exception: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Could not find an owner window for this ContentDialog.) ---> System.InvalidOperationException: Could not find an owner window for this ContentDialog. at ModernWpf.Controls.ContentDialog.ShowAsync() at Flow.Launcher.HotkeyControl.OpenHotkeyDialogAsync() in C:\DEV\Flow Launcher\Flow.Launcher\HotkeyControl.xaml.cs:line 246 --- End of inner exception stack trac
```
- Fix the Win32Exception
```
System.ComponentModel.Win32Exception (0x80004005): 작업을 완료했습니다.
at …
```
> Fix Content Dialog owner & Fix Win32Exception

- Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
- Flow.Launcher.Core/ExternalPlugins/CommunityPluginStore.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/Helper/AutoStartup.cs
- Flow.Launcher/Helper/HotKeyMapper.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
If FL enabled both logon task and registry,  `Hide Flow Launcher on startup` will not work since the later one will trigger main window show event. So we need to check both because if both of them are enabled.
Follow on with #3218.
Use null as flag to return value so that we can handle plugin source issue.
Follow on with #3460.
> Fix Possible Window Popup During Startup & Fix Store Plugin List Refresh Issue

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Resources/Light.xaml
- Rename ‘Search Window Position’ to ‘Search Window Location’
- Requested from @deefrawley 
- Only the option title has been changed; all other areas still use “Position.”
> Rename ‘Search Window Position’ to ‘Search Window Location’

- Flow.Launcher/MainWindow.xaml.cs
- When `HideOnStartup = off` and `Animation = on`, there was a bug where the clock would **not appear at all on the initial launch**.
- After the first launch, the clock behaves normally.
- This PR addresses the issue by **forcibly triggering the animation on `OnLoaded`**, ensuring the clock becomes visible on the first load.
- Even after this fix, **the animation might appear to be missing** due to rendering timing.  
If you slow down the animation duration, you’ll notice it’s actually running.
- Adjusting the position of the animation trigger within `OnLoaded` can make the animation look better.  
However, doing so caused a **slight delay in visibility when animation was disabled**.
- While a more refined fix is possible, it would **increase complexity**.  
Since the clock **does show …
> Fix clock not displaying in certain situations

- Flow.Launcher/Resources/CustomControlTemplate.xaml
- Flow.Launcher/Resources/Dark.xaml
- Remove background setter for disabled state and add placeholder color for NumberBox
Before
After
I clearly remember working on it and even testing it, but in the current dev build, the style is missing in dark mode. I also removed another unused style that wasn’t in the color list at all—though I’m pretty sure I worked on that too. I tried checking if I did it in another PR, but couldn’t find anything. Either aliens have tampered with my memory, or early-onset dementia is setting in. If I end up in a nursing home someday, please consider donating a portion of your funds in my memory.
> Fix NumberBox Placeholder text color

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
> Add cache folder button in dev tools

- Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Flow.Launcher/ActionKeywords.xaml.cs
- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/ViewModel/PluginViewModel.cs
Fix build warning `MSBUILD : warning FodyPackageReference: Fody: The package reference for PropertyChanged.Fody does not contain PrivateAssets='All'
Fix build warning
```
PluginViewModel.cs(159,9,159,10): warning : Fody/PropertyChanged: Type Flow.Launcher.ViewModel.PluginViewModel contains a method OnActionKeywordsChanged which will not be called as ActionKeywords is not found. You can suppress this warning with [SuppressPropertyChangedWarnings].
PluginViewModel.cs(164,9,164,10): warning : Fody/PropertyChanged: Type Flow.Launcher.ViewModel.PluginViewModel contains a method OnSearchDelayTimeChanged which will not be called as SearchDelayTime is not found. You can suppress this warning with [SuppressPropertyChangedWarnings].
```
> Improve PropertyChanged.Fody Code Quality

- Flow.Launcher/SettingPages/ViewModels/SettingsPaneAboutViewModel.cs
Follow on with #3411.
- We should firstly delete plugin cache directories and then delete plugin directory, or the settings page will freeze.
- Reverted original changes to set recursive to true.
Test
- Clean logs & clean caches option can work.
> Fix clean cache issue

- Flow.Launcher/ViewModel/MainViewModel.cs
From #3350, we use TextChanged event to invoke Query, which can cause duplicated call of Query if we use OnPropertyChange(nameof(QueryText)).
In this PR, we use 
```
// When executing OnPropertyChanged, QueryTextBox_TextChanged1 and Query will be called
// So we need to ignore it so that we will not call Query again
_ignoredQueryText = _queryText;
```
to resolve that.
Fix #3497, #3498.
> Do not query again when setting private field of QueryText

- Flow.Launcher/ViewModel/MainViewModel.cs
When querying with `e`, we will get more debug info.
```
22:03:03.2597+08:00 - DEBUG - MainViewModel.QueryResultsAsync - Start query with text: e
22:03:03.2597+08:00 - DEBUG - MainViewModel.QueryResultsAsync - Start query with ActionKeyword <> and RawQuery <e>
22:03:03.2597+08:00 - DEBUG - MainViewModel.RemoveOldQueryResults - Remove old results
22:03:03.2762+08:00 - DEBUG - MainViewModel.QueryResultsAsync - Valid <6> plugins: <Calculator> <Explorer> <Program> <System Commands> <URL> <Web Searches>
22:03:03.2762+08:00 - DEBUG - MainViewModel.QueryResultsAsync - Wait for querying plugin <Calculator>
22:03:03.2762+08:00 - DEBUG - MainViewModel.QueryResultsAsync - Wait for querying plugin <Explorer>
22:03:03.2762+08:00 - DEBUG - MainViewModel.QueryResultsAsync - Wait for querying plugin …
```
> Add more debug log info for query

- Flow.Launcher/ViewModel/MainViewModel.cs
- Dispose _updateSource when creating new one.
- Use _updateToken instead of _updateSource.Token to resolve ObjectDisposeException.
- Use local variable for stability to resolve possible token cancellation issue.
Fix #3508, #3511 from https://github.com/Flow-Launcher/Flow.Launcher/pull/3314
> Fix result missing + not updating issues

- Flow.Launcher/App.xaml.cs
- Flow.Launcher/MainWindow.xaml.cs
Remove `await _theme.RefreshFrameAsync();` in main window loaded event because in `App.xaml.cs`, it is already called in `Ioc.Default.GetRequiredService<Theme>().ChangeTheme();`
Resolve #3514.
> Fix startup flicker

- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultsForUpdate.cs
- Flow.Launcher/ViewModel/ResultsViewModel.cs
**Problem:**
Current result clearing logic creates a seemingly animation of flickering when results switch from: 
- home page to any result set
- action keyword result set to another action keyword result set
- action keyword result set to global action keyword result set
- global action keyword result set to action keyword result set
This is due to the use of result list clearing (MainViewModel.RemoveOldQueryResults) in between these result set changes.
**Solution**
Don't call `Results.Clear()`. Where Flow does the results update in `ResultsViewModel.NewResults` return particular set or combined/concatenated results.
**Before**
**After**
**Tested**
- home page to any result set
- action keyword result set to another action keyword result set
- action keyword result set to global action …
> Fix clearing of results logic & minor adjustment to results update

- .github/workflows/spelling.yml
Check spelling workflow ignore release PR targeting master branch, otherwise too much noise. Checking should occur and be resolved on PRs before merging to dev.
> Check spelling workflow ignore release PR targeting master branch

- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
Follow on with #3438.
Adjust margin in appearance page.
> Adjust margin in appearance page

- Flow.Launcher/ViewModel/MainViewModel.cs
Resolve #3519.
Tested:
- When home page feature is on and input is empty, if there are items in result list box, arrow up will trigger result index change instead of history results change.
> Fix Homepage with triggers history results on arrow up

- Flow.Launcher/Storage/TopMostRecord.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
Follow on with #3203.
Add `OriginQuery` for topmost results & plugin info results so that we can remove `result.OriginQuery` null check.
> Fix null origin query issue

- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
Add copy file name in explorer context menu.
Resolve #3505.
> Support copy file name

- Flow.Launcher/MainWindow.xaml.cs
When system resumes, we need to recreate Sound instance so that it can play sound normally.
From: https://stackoverflow.com/questions/64805186/mediaplayer-doesnt-play-after-computer-sleeps
Resolve #3278.
Tested.
> Fix sound effect issue after sleep or hibernation

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
Follow on with #3361.
Fix issue:
```
Please open new issue in https://github.com/Flow-Launcher/Flow.Launcher/issues
1. Upload log file: C:\Users\11602\AppData\Roaming\FlowLauncher\Logs\1.19.5\2025-05-12.txt
2. Copy below exception message
Flow Launcher version: 1.19.5
OS Version: 26100.3915
x64: True
Python Path: C:\Users\11602\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 05/12/2025 15:09:38
Exception:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Could not find a part of the path …
```
> Fix temp files deleting issue & Validate the cache directory before loading all bookmarks

- Flow.Launcher.Core/Plugin/PluginManager.cs
When one plugin is already disabled, we do not need to show initialization failure notification and we just need to log exception for it.
Or else the error message will be shown every time Flow starts which can be really annoying.
Resolve #1216.
> Do not show error message for initialization if plugin is already disabled

- Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultsViewModel.cs
Check if the results are selected and then set its visibility in `if (_mainVM == null || _mainVM.ResultsSelected(this))`. So if we click right arrow and input some characters at the same time, because the selected results are from context menu already, the visibility of the results will not be updated in `private void UpdateResults(List<ResultViewModel> newResults, bool reselect = true, CancellationToken token = default)`.
Resolve #2026.
> Fix results context menu display issue

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/SettingWindow.xaml.cs
From #2756.
Resolve #2320.
More information is available in #2756.
> Fix Vertical Window Positioning with Multiple Monitors

- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
- Flow.Launcher/Storage/TopMostRecord.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
Currently, for one query, Flow can only support one topmost record. We should support multiple topmost records because users may want to set many records to be topmost.
The latter record is, the topper it be.
- Old data `TopMostRecord.json` will be converted into new data `MultipleTopMostRecord.json`.
- Flow can display multiple topmost records.
- Latter records are topper.
e.g.
MultipleTopMostRecord.json:
```
{
"records": {
"vs": [
{
"Title": "Visual Studio 2022",
"SubTitle": "",
"PluginID": "791FC278BA414111B8D1886DFE447410",
"RecordKey": null
},
{
"Title": "Visual Studio Installer",
"SubTitle": "",
"PluginID": "791FC278BA414111B8D1886DFE447410",
"RecordKey": null
},
// This is the latest record and it should be the topmost
{
"Title": "Visual Studio Code",
"SubTitle": "",
"PluginID": …
```
> Support Multiple Topmost Records

- Flow.Launcher/MainWindow.xaml.cs
- Fixed an issue where changes to the system ColorScheme (e.g., via AutoDarkMode or OS settings) were not properly reflected in Flow's window background color.
- In Dev mode, select a theme that includes both Light and Dark modes (e.g., `win11light`).
- Set the ColorScheme option to **Follow system setting**.
- Change the OS ColorScheme (e.g., switch from Light to Dark).
- Observe that, although the system is in Dark mode, the window background remains white.
- The window background color is updated during the `RefreshFrame` process.
- Due to changes in the timing of `RefreshFrame`, the background color update was no longer triggered properly.
- Since `ModernWpf` already listens for system ColorScheme changes, we subscribe to its event.
- When the system ColorScheme change event is …
> Fix system ColorScheme update handling

- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
Originally, Flow only uses three buttons: Enable/Disable/Delete, Edit, Add which can cause confusion.
Now Flow uses four buttons for program source management: Enable/Disable, Edit, Delete, Add.
I think it can help users know our logic as follows. And if we use buttons for wrong actions, Flow will notify users with message box.
* Enable/Disable: Use to enable/disable **auto-loaded** and **non-auto-loaded** program sources.
* Edit:  Use to edit **auto-loaded** and **non-auto-loaded** program sources.
* Delete: Use to delete **non-auto-loaded** program sources.
* Add: Use to add **non-auto-loaded** program sources.
Note:
* **auto-loaded** program sources are the programs in the common paths of Window applications. They will be loaded and indexed every time Flow starts and reloads.
* …
> Improve Program plugin delete button logic

- Flow.Launcher/SettingWindow.xaml
- Fixed an issue where the font was not applied to certain elements in the settings window.
- In the Dev environment, the font in the settings window is changed. You can observe that the font is not applied to titles and card elements within the settings window, while it is correctly applied to regular controls.
- The root cause is unclear; the font application was working correctly at the time of the previous merge.
- To resolve the issue, the style was explicitly applied to the settings window itself, following the initial implementation approach.
- Verified that other windows still apply fonts correctly without needing explicit style settings.
> Add dynamic font family to SettingWindow

- Flow.Launcher/Resources/Pages/WelcomePage1.xaml.cs
- Flow.Launcher/Resources/Pages/WelcomePage2.xaml.cs
- Flow.Launcher/Resources/Pages/WelcomePage3.xaml.cs
- Flow.Launcher/Resources/Pages/WelcomePage4.xaml.cs
- Flow.Launcher/Resources/Pages/WelcomePage5.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneHotkey.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneProxy.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml.cs
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
If the navigation is not triggered by button click, so we need to reset the page type in all setting pages.
And in setting window, we need to update the selected item in navigation view.
If we use forward/backward button, `IsInitialized` is still true so we need to check nullability of view model instance instead.
- Use click / navigation button to navigate pages.
Confirmed by [vzabrodin](https://github.com/vzabrodin).
Resolve #3546.
> Fix setting window navigation update issue

- Flow.Launcher/SettingWindow.xaml.cs
Follow on with #3470. 
Because WindowStartupLocation is Manual, so we need to initialize position before InitializeComponent.
Fix:
> initialize position before InitializeComponent

- Flow.Launcher/PublicAPIInstance.cs
- Fixes #3550
- This PR resolves an issue where launching `explorer.exe` to open a folder path would result in a lingering zombie process even after the File Explorer window is closed.
Previously, we used `ProcessStartInfo` with `FileName = "explorer.exe"` and `Arguments = "folder path"` to open directories. However, when launched this way from a WPF application, `explorer.exe` remains as a child process and does not exit even after its window is closed.
Instead of launching `explorer.exe` directly, this PR updates the logic to:
- Use `Process.Start("folder path")` with `UseShellExecute = true` when the custom explorer is set to `explorer.exe`.
- This leverages the Windows Shell to open the folder using the default handler (usually File Explorer), avoiding the need to explicitly invoke …
> Fix prevent zombie explorer.exe processes when opening folders

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
Context:
Currently all default built-in plugins have their own versioning. This creates manual work to bump them individually and accordingly.
We need to change this to have them all set to uniform versioning following flow's. Since they always get published along with flow there is little need for them to be different. Instead we bump them all at the same time to the same version as flow regardless of there are changes to them. This also will indicate which release they are from.
Changes:
- Set their version to 1.0.0, which will be the version displayed when built locally.
- Use AppVeyor CI to set them to flow's current version when built.
Tested:
- Build passes
- When built by CI the version displayed on all plugins are they same as flow's version in abouts settings page.
> Unify all default built-in plugins' version

- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Plugins/Flow.Launcher.Plugin.Shell/Main.cs
- Fixes an issue where QueryTextBox did not receive focus when the launcher was shown via Win+R shortcut. (Shell Plugin)
- This was due to OS-level focus interference. Resolved by introducing a short delay before applying focus.
- In dev build, enable the Win+R setting in the Shell plugin and run the launcher
- Verify that the input box does not receive focus.
When launching Flow Launcher via the Win+R shortcut (with the Shell plugin's setting enabled), the main window appears, but the input box (QueryTextBox) does not receive focus, preventing immediate typing.
This happens because Win+R is a system-reserved shortcut. Even though the plugin intercepts the keyboard event and shows the main window, Windows continues to process the Win key, and briefly reclaims focus, typically sending it …
> Fix: Ensure QueryTextBox receives focus after Win+R

- Flow.Launcher/App.xaml.cs
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/WelcomeWindow.xaml.cs
If we call Win+R before creating main window, the Show will be called before main window constructor. So we need to check if main window is created.
```
Please open new issue in https://github.com/Flow-Launcher/Flow.Launcher/issues
1. Upload log file: C:\Users\11602\AppData\Roaming\FlowLauncher\Logs\1.19.5\2025-05-22.txt
2. Copy below exception message
Flow Launcher version: 1.19.5
OS Version: 26100.4061
x64: True
Python Path: C:\Users\11602\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 05/22/2025 18:33:08
Exception:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved …
```
> Fix main window null when checking exiting

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/pt-br.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml.cs
- Resolve https://github.com/Flow-Launcher/Flow.Launcher/issues/3533
- Adds a display of the file's creation or modification period in the preview area.
> Display the file age in preview panel

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
- Flow.Launcher/Themes/Base.xaml
We should use ResultContextMenu instead of ContextMenu because for Window, it already has one element called `ContextMenu`.
> Use ResultContextMenu instead of ContextMenu

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingPages/Views/SettingsPaneAbout.xaml
Two hardcoded texts have been replaced with string resources.
> Update Advanced title and reset button content to use dynamic resources

- Flow.Launcher.Infrastructure/Http/Http.cs
Handle SendAsync issue so that we will not get error message like those:
```
Please open new issue in https://github.com/Flow-Launcher/Flow.Launcher/issues
1. Upload log file: C:\Users\11602\AppData\Roaming\FlowLauncher\Logs\1.0.0\2025-06-01.txt
2. Copy below exception message
Flow Launcher version: 1.0.0
OS Version: 26100.4202
x64: True
Python Path: C:\Users\11602\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 06/01/2025 19:25:33
Exception:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (No such host is known. …
```
> Use try-catch to resolve SendAsync issue

- .github/update_release_pr.py
- .github/workflows/release_pr.yml
Automatically update release PR's description with the list of milestone PR title and number
> Add release PR workflow to auto update PR description

- Flow.Launcher.Core/Plugin/PluginManager.cs
If some plugins failed to construct, `Name` or `AssemblyName` property will not be initialized and could be null. This can cause this issue:
```
Please open new issue in https://github.com/Flow-Launcher/Flow.Launcher/issues
1. Upload log file: C:\Users\11602\AppData\Roaming\FlowLauncher\Logs\1.20.0\2025-05-24.txt
2. Copy below exception message
Flow Launcher version: 1.20.0
OS Version: 26100.4061
x64: True
Python Path: C:\Users\11602\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 05/24/2025 22:45:22
Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
at System.ArgumentNullException.Throw(String paramName)
at System.IO.Path.Combine(String path1, String …
```
> Fix argument null exception when updating plugin directories for erroneous plugins

- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
Use dynamic resource instead of binding for string resources to make sure it can listen to resource changed event
> Use dynamic resource instead of binding

- Flow.Launcher/Helper/ErrorReporting.cs
Since many plugins do not follow strict coding rules and they do not handle exception in async void functions, we should just log the exception and do not open exception message box.
Resolve #3619, #3622, #3628.
> Silent handle TaskSchedulerUnobservedTaskException

- Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/PublicAPIInstance.cs
Throw exception from `OpenInBrowserWindow` & `OpenInBrowserTab` function in `SearchWeb` and handle them in `OpenUri` of `PublicAPIInstance`.
Resolve #3473.
> Fix OpenUri Exception

- .github/workflows/default_plugins.yml
Update default plugin publish action to follow production version
This is already run, so it's tested working. For example https://github.com/Flow-Launcher/Flow.Launcher.Plugin.WindowsSettings/releases/tag/v1.20.0
> Update default plugin publish to follow production version

- .github/update_release_pr.py
- update workflow to get PR authors for release PR
- fix filter when getting state == all
- fix filter when label is empty string
> Add get PR authors to workflow

- Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLinkHelper.cs
Use `SLR_NO_UI` to avoid showing any UI during link resolving, like Problem with Shortcut dialogs
From: https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinka-resolve
Resolve #3386.
> Do not show UI when shortcuts cannot be resolved

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
Sometimes Everything installation will fail because of permission issues or file not found issues, so we should let the user know that Everything is not installed properly and ask them to install it manually.
Resolve #3184, #3381, #3393.
> Catch exception when installing Everything

- Flow.Launcher/Resources/CustomControlTemplate.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml.cs
- Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/3292
- This issue is reportedly due to a known WPF bug related to TabControl. I’ve adjusted the structure by removing the TabControl altogether.
> Replace TabControl with Expander in Explorer Plugin Setting Panel

- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
- Flow.Launcher.Infrastructure/Storage/FlowLauncherJsonStorage.cs
- Flow.Launcher.Infrastructure/Storage/PluginBinaryStorage.cs
- Flow.Launcher.Infrastructure/Storage/PluginJsonStorage.cs
- Flow.Launcher/PublicAPIInstance.cs
- Expose `ISavable` interface in derived class to make sure we are calling the new version of `Save` method. This can make sure we are calling the version of `Save` with error handling.
- Use `ISavable` instead of `object` for code quality
Since all `Save` methods are called with error handling, we can resolve #3043, #3130.
> Fix Derive Class Save Method Calling Issue

- Flow.Launcher/Resources/Controls/InstalledPluginDisplayKeyword.xaml
Modified Button to use auto width with a minimum width of 100. This change allows the button to grow when keywords do not fit.
> Update Button width for responsive design

- appveyor.yml
**Remove AppVeyor on tag release upload:**
I don't see a need for this in our release workflow. 
This builds new flow artifacts setup exe, portable zip, etc and uploads them again when the GitHub release is published (because publishing creates the tag). This causes the hash to be different to when the artifacts were uploaded during push from dev to master. Different hash causes duplicate deployments on those that rely on the publish action and causes validation failures for package manager projects if they are triggered on the publish release action, prior to the reupload of artifacts from tagging.
**Change NuGet publish to on master push:**
Change to be consistent with the release artifact upload, triggered when pushed to main.
> Remove on tag release upload & change NuGet publish to on master push

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
- Support Loading Msix FireFox Bookmarks
Since Win11 has introduced Msix package installer in Microsoft Store, Flow should support path to places.sqlite of MSIX installer: `C:\Users\{UserName}\AppData\Local\Packages\Mozilla.Firefox_n80bbvh6b1yt2\LocalCache\Roaming\Mozilla\Firefox`.
See more: https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_finding-your-profile-without-opening-firefox.
- Fix IsRelative logic in #3659
`(relativeAttribute == "0" || relativeAttribute == "IsRelative=0")`
- Fix incorrect Directory.Exists check on file path
Use `File.Exist` instead of `Directory.Exist`
- Use FireFox installed from Microsoft Store and its bookmarks can be loaded.
> Support Loading Msix FireFox Bookmarks & Fix IsRelative logic

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Helper/FaviconHelper.cs
Do not use pooling so that we do not need to clear pool to avoid ObjectDisposedException.
Follow on with #3641.
Issue:
```
EXCEPTION OCCURS: System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
at IntPtr System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, ref bool success)
at int SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_prepare_v2(sqlite3 db, Byte* pSql, int nBytes, out IntPtr stmt, out Byte* ptrRemain)
at int SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_prepare_v2(sqlite3 db, ReadOnlySpan<byte> sql, out IntPtr stm, out ReadOnlySpan<byte> tail)
at IEnumerable<(sqlite3_stmt Statement, int ParamCount)> Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
at …
```
> BrowserBookmark do not use SqliteConnection pooling to avoid ObjectDisposedException

- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/Main.cs
In WebSearch plugin, users may input url like `file:///D:/search/index.html?query={q}` which is regarded as files url in C# standard process. So we need to a new api to force using web brower to open it.
Resolve #3608.
- Go to the plugin settings of web search plugin.
- Add a new search engine.
- Set the URL to something with `file://` prefix like "file:///D:/search/index.html?query={q}"
- Search anything, for example casino. It will open "file:///D:/search/index.html?query=casino" in brower tab.
> Add New API to Force Web Url

- Flow.Launcher/ActionKeywords.xaml
- Flow.Launcher/ActionKeywords.xaml.cs
Updated `ActionKeywords.xaml` to use a new `Grid` layout, enhancing the structure and flexibility of the UI. Removed a couple of layers of nested grids and stackpanels. Changed tbOldActionKeyword from a TextBlock to a TextBox so user can copy the text. Modified `ActionKeywords.xaml.cs` so the old keywords are already filled in, in the TextBox.
> Refactor ActionKeywords UI and improve keyword handling

- appveyor.yml
Do not build on tag. We create a release on merge to master and building on tag will with our current configuration result in:
- upload artifacts twice changing the hash,
- update GitHub release again, turning it to a draft and causing a republish
- trigger NuGet deployment
- from updating the GitHub release and having to republish will cause another GitHub New Release Deployments action
> Add AppVeyor skip build on tag

- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
Follow on with #3631.
We need to add preview information back for external preview plugin like `Quick Look`.
> Add preview information back for external preview

- Flow.Launcher/CustomShortcutSetting.xaml
Fix tab focus sequence in custom shortcut setting window.
Continuously type `Tab`. And obverse the element which gets the focus.
Original: Preview button is the second to get the focus.
https://github.com/user-attachments/assets/d8b41f0e-4830-4953-9c0e-5a538d533a3a
After: Preview button is the third to get the focus.
https://github.com/user-attachments/assets/b4ba79d2-d2c0-4c14-baf7-0a35e2e0854e
> Fix tab sequence

- .github/actions/spelling/expect.txt
- .github/actions/spelling/patterns.txt
Fix false failing spell check rules.
patterns.txt use Cases:
- Alphanumeric Identifiers: Strings that contain a mix of letters and numbers, or specific symbols, which are common in code (like jjw24, SHA1Hash, myVar_v2).
- Specific Code Constructs: Regex patterns to ignore things that look like URLs, file paths, UUIDs, or specific syntax within comments that shouldn't be spell-checked as words.
- Technical Terms with Punctuation/Numbers: Terms that are not simple words but are common and should be ignored (e.g., camelCase, snake_case).
expect.txt use cases:
- Proper Nouns: Names of products, companies, or individuals that aren't in a standard dictionary (e.g., GitHub, Keptn, VSCode).
- Project-Specific Terminology: Unique terms or acronyms used within your project (e.g., DevOps, Agile).
- …
> Fix false failing spell check rules

- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
Allows hex numbers like `0x4F` to be used in the calculator plugin.
> Calculator: Support hex numbers

- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
Update Calculator plugin description. From #3774
> Update Calculator plugin description

- Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/QuickAccessLinks/QuickAccess.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Add support for volume type in quick access link.
> Support volume type for quick access link

- Flow.Launcher.Core/Plugin/PluginManager.cs
In 
https://github.com/Flow-Launcher/Flow.Launcher/blob/e965b5682468da026f4a4f2c87d9c2f798b834e3/Flow.Launcher/PublicAPIInstance.cs#L575-L576
we only pass `removePluginSettings` parameter.
But in
https://github.com/Flow-Launcher/Flow.Launcher/blob/e965b5682468da026f4a4f2c87d9c2f798b834e3/Flow.Launcher.Core/Plugin/PluginManager.cs#L555-L558
we have accepted four parameters and `removePluginSettings` parameter is passed to `removePluginFromSettings` parameter which can cause possible issues
> Fix Plugin Uninstallation Issue

- Flow.Launcher.Core/Plugin/PluginManager.cs
If one plugin is modified, do not use it when querying results. 
From #3572
> Check if plugin is modified before querying

- Flow.Launcher.Plugin/EventHandler.cs
- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/PublicAPIInstance.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
Add API functions:
```
/// <summary>
/// Representing whether the application is using a dark theme
/// </summary>
/// <returns></returns>
bool IsApplicationDarkTheme();
/// <summary>
/// Invoked when the actual theme of the application has changed. Currently, the plugin will continue to be subscribed even if it is turned off. 
/// </summary>
event ActualApplicationThemeChangedEventHandler ActualApplicationThemeChanged;
```
> Add Theme mode API Function

- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/UWPPackage.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Check `string.IsNullOrEmpty(query.Search)` for Program plugin so that Flow can return results when query is empty for program
> Return results when query is empty for Program

- Flow.Launcher.Infrastructure/Win32Helper.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneThemeViewModel.cs
For Win32 windows which cannot be set to dark mode by ModerWPFUI, we need to call `EnableWin32DarkMode` API to enable its dark mode.
And when users change the application theme mode setting, we should reset this API.
Example: Explorer context menu window.
Before:
After:
- Force light / Force dark / System theme change all work well
> Enable dark mode if the system is in dark mode for Win32 windows

- Flow.Launcher.Core/Plugin/PluginManager.cs
This can resolve the issue from @jjw24:
```
Store uninstall plugin with option set to no restart, when using the plugin's action keyword, query window seems unresponsive, e.g. remove bookmark plugin and use b balabala
pm uninstall plugin with option set to no restart, when using the plugin's action keyword, query window seems unresponsive, e.g. remove bookmark plugin and use b balabala
```
> Remove plugins from global & non-global plugins when they are removed from settings

- Flow.Launcher.Core/Plugin/PluginManager.cs
> Use System.Version to compare versions

- Flow.Launcher/MainWindow.xaml.cs
- When search is empty and Home Page feature is enabled, if the language is changed, the home page will not be updated by its translation until next non-empty query. So we should check if home page is shown and update the translations
- Enable Home Page and change language, the search window results will be updated
> Update home page when language changes

- Flow.Launcher.Infrastructure/UserSettings/PluginHotkey.cs
- Flow.Launcher/CustomQueryHotkeySetting.xaml
- Flow.Launcher/CustomQueryHotkeySetting.xaml.cs
- Flow.Launcher/CustomShortcutSetting.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneHotkeyViewModel.cs
Seperate from #3770. This refactor is helpful for hotkey model change in #3770.
- Add / Edit / Remove custom query hotkey
> Refactor CustomQueryHotkeySetting control

- Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/QuickAccessLinkSettings.xaml.cs
> Fix Quick Access Link Type Fetching Issue

- Flow.Launcher/MainWindow.xaml.cs
> Use try-catch for query text box paste

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
Currently, FLow.Launcher.Plugin NuGet package does not have documents when referring to its classes, etc.
This attribution is for enabling the documents in NuGet package so that developers can use it more effectively.
Use the NuGet package in CI:
> Generate documents for NuGet package

- .github/update_release_pr.py
Rather than trying to work out the milestone, get it from the release PR. This allows for action to run even when multiple milestones set.
Tested:
- Can retrieve PRs associated with 1.20.2 release.
> release_pr GitHub workflow automatically get milestone from release PR

- Plugins/Flow.Launcher.Plugin.Program/Programs/UWPPackage.cs
> Fix the issue that UWP changes that can't be monitored (#2345)

- .github/actions/spelling/expect.txt
- Flow.Launcher.Infrastructure/PinyinAlphabet.cs
- Flow.Launcher.Infrastructure/TranslationMapping.cs
- Flow.Launcher.Test/TranslationMappingTest.cs
- Improve Chinese character detection speed 1x by using our own function. The 3rd party one uses regex and it's slow.
- Some renames.
- More detailed exception handling.
> Improve performance and readablility of Pinyin Alphabet

- Flow.Launcher.Infrastructure/PinyinAlphabet.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
Follow on with #3829
Change reload logic
> Reload on all settings change

- Flow.Launcher.Core/Plugin/PluginInstaller.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
- Flow.Launcher/SettingPages/Views/SettingsPanePluginStore.xaml
* Add Auto Update description
* Add Auto Update Plugins option which can automatically check plugin updates in the background every 5 hours
* Add an option to check plugin updates in plugin store page
Since the plugin update message is implemented with message instead of message box which I do not think it will annoy users, I use default True value for Auto Update Plugins.
> Add Support for Automatically Checking Plugin Updates

- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
1. Support returning all usable commands while query is empty. 
#2040 
2. ChangeQuery by ThemeSelector Action with ActionKeyword  at the front as well
> Add Empty Query Returning & Change ThemeSelector Keyword with ActionKeyword for Sys Plugin

- Flow.Launcher/MessageBoxEx.xaml.cs
If message box ex type is not OK and it has no caption and icon, it will not set description to vertically center. This PR is for resolving this issue.
Test:
WebSearch delete dialog:
Orig:
After:
> Fix message box vertically center issue when message type is not OK

- Flow.Launcher.Core/Plugin/PluginInstaller.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/PluginUpdateWindow.xaml
- Flow.Launcher/PluginUpdateWindow.xaml.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPanePluginStoreViewModel.cs
Follow on with #3827. Pop up a plugin update dialog to let users select the plugins they want to update and whether to restart application after updating plugins.
> Add plugin update dialog for selective plugin updating

- Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml
- Flow.Launcher/SettingPages/Views/SettingsPanePlugins.xaml.cs
Clear selection to make sure all items can be mouse hovered.
Hover your mouse on the first item of the plugin list.
Original:
After:
> Clear plugin list selection to make sure all items can be mouse hovered

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultViewModel.cs
From https://github.com/TBM13/Flow.Launcher/commit/4db994c2a137c7313c3e66ae04a4006fdf357997. Thanks @TBM13!
- Toggle Always preview to off
- Search for some files (Use Explorer plugin results)
- PreviewPanel is not created if preview control is invisible
> Do not create customized preview panel when preview is off

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs
Clean orphan SQLite files on start-up that are being created by BrowserBookmark plugin.  This is a temporary solution to prevent users' cache accumulating very large numbers of files / MB.
Will be addressed properly with new version of plugin (complete rewrite for Flow Launcher V2).
> Clean orphan files, temp fix

- Flow.Launcher.Core/ExternalPlugins/Environments/PythonEnvironment.cs
- Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptEnvironment.cs
- Flow.Launcher.Core/ExternalPlugins/Environments/TypeScriptV2Environment.cs
- Flow.Launcher/Languages/en.xaml
> Add error handler for DroplexPackage.Drop

- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
This can help developers change query suggestion text for each result.
> Add new api Result.QuerySuggestionText

- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
- Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/PublicAPIInstance.cs
Load `Constant.ImageIcon` & `Constant.LoadingImgIcon` so that they can be freeze resources which can improve performance.
Add non-async method in `BinaryStorage` so that `ImageCache` can use it to remove async methods.
And we can remove `ImageLoader.WaitSaveAsync()` to improve code quality
- Loading missing icon can work
> Load images into ImageCache & Use non-async method in ImageCache

- Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
- Flow.Launcher.Plugin/UserPlugin.cs
Allows plugin to specify in the their plugin manifest, a new optional property 'MinimumAppVersion', e.g. `"MinimumAppVersion": "2.0.0"`. When the user's is running flow v1.20.2 or below, the plugin will not show up in the Store or the PluginsManager install command results. 
The goal is to prevent users from downloading a plugin version that uses an API method not available in their older flow version, or trying to upgrade to the latest plugin version that is not compatible with their existing outdated flow installation.
Tested:
- plugin excluded from manifest after sync if current user's app version does not meet the minimum requirement.
-  plugin included where app version meets the minimum required version or if the MinimumAppVersion is undefined
- MinimumAppVersion specified in …
> Allow setting of minimum app version plugin requirement

- Flow.Launcher.Core/ExternalPlugins/PluginsManifest.cs
For v2.0.0 flow, we switch the manifest file plugins.json back to the main branch. This is due to .NET 9 upgrade, we need to prevent older flow versions from updating to plugins in this release. Default plugins are now on .NET 9 and will not work with older versions.
Follows on from #3286 
Todos:
> Switch plugins manifest file download URL to be from main branch

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingPages/Views/SettingsPaneTheme.xaml
Since preview panel requires a certain minimum height, maximum results shown may not take effect. So we need to add a warning to notify users for that. (I even thought this is a bug originally😢)
When we enable the Always Preview and set a small number for maximum results shown, it will not take effect since preview panel requires a minimum height.
> Add maximum results shown warning when always preview is on

- Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
Rather than showing the user `EXCEPTION OCCURS: System.Threading.Tasks.TaskCanceledException...`, print not scary log msg
> Catch scary exception, print friendly log

- Flow.Launcher.Infrastructure/Logger/Log.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Languages/en.xaml
* User can now choose None, Error, Info, or Debug.
* Use `Flow.Launcher.${date:format=yyyy-MM-dd}.log` as log file format.
Fixes https://github.com/Flow-Launcher/Flow.Launcher/issues/3812
> Enhanced logging

- Flow.Launcher.Core/Plugin/JsonRPCPluginSettings.cs
* Constrain column 0 to 60% of the max width of the grid.
* Use wrap as default text wrapping option.
> Improve JsonRPC Plugin Setting Panel

- Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
Add `{get; }` to fix AllEverythingSortOptions issue
> Fix AllEverythingSortOptions issue

- Flow.Launcher.Infrastructure/Image/ImageLoader.cs
- Flow.Launcher/Helper/WallpaperPathRetrieval.cs
* Use `Lock` for `CacheLock`
* Use `LogError` instead of `LogInfo`
* Use `using ()` sentence so that file is not locked
* Use `OnLoaded` to ensure the wallpaper file is not locked
* Use `using` sentence for registry key to fix possible memory leak
Fix #3983
Open Flow Launcher -> Open setting window -> Navigate to appearance page -> Wallpaper file is not locked
> Fix Wallpaper File Lock

- Flow.Launcher.Core/ExternalPlugins/CommunityPluginSource.cs
> Use Debug instead of Info

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
- Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Flow.Launcher.Plugin.Explorer.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Main.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingDownloadHelper.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ViewModels/SettingsViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ActionKeywordSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/PreviewPanel.xaml.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/QuickAccessLinkSettings.xaml.cs
Use `Localize` class from `Flow.Launcher.Localization` to improve code quality. No feature updates.
The solution is compiled successfully.
> Use Flow.Launcher.Localization to improve code quality

- Flow.Launcher.Infrastructure/UserSettings/DataLocation.cs
- Flow.Launcher/SettingPages/ViewModels/SettingsPaneGeneralViewModel.cs
From #3982.
Use `!File.Exists(Path.Combine(PortableDataPath, DeletionIndicatorFile)))` instead of `!File.Exists(DeletionIndicatorFile))` so that we can check if deletion indicator file exists.
> Fix PortableMode Check Issue

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
- Plugins/Flow.Launcher.Plugin.Calculator/Flow.Launcher.Plugin.Calculator.csproj
- appveyor.yml
Merge v2.0.1 back into dev from master
> Merge v2.0.1 back into dev

- Flow.Launcher.Infrastructure/NativeMethods.txt
- Flow.Launcher.Infrastructure/Win32Helper.cs
- Flow.Launcher/MainWindow.xaml.cs
Follow on with #3532.
Use sleep mode listener to listen power mode change event to fix standby sleep mode issue. 
Inspired by: https://github.com/XKaguya/LenovoLegionToolkit and https://blog.csdn.net/mochounv/article/details/114668594.
Add lock for InitSoundEffects() & SoundPlay().
Resolve #4018.
Tested by [H5820121](https://github.com/H5820121).
Test on S0 modern standby sleep device. It works well.
> Use sleep mode listener to fix modern standby sleep mode issue
