Flow-Launcher/Flow.Launcher

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/Themes/Base.xaml
Adds ClearType for font smoothing in Flow Launcher
> Add ClearType to Flow Launcher

- Flow.Launcher.Test/Flow.Launcher.Test.csproj
- Flow.Launcher.Test/Plugins/ProgramTest.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
Tweaked PRI format so to correctly load UWP apps.
> Fix UWP apps loading

- README.md
@NickSeagull @SysC0mp @Kalaschnik @theClueless First cut of the readme update. Please let me know your thoughts, what I should add/remove/update.
Cheers
https://github.com/Flow-Launcher/Flow.Launcher/issues/3
> Update readme- First cut

- Plugins/Flow.Launcher.Plugin.Folder/Main.cs
Closes #20 
The folder plugin now recognizes and handles environment string paths.
1. Simply typing `%` will list all supported environment string paths (listed below).
2. Typing after the first `%` will filter the results
3. Typing a full path containing an environment string will replace it with the actual path and perform a normal path search
```
%appdata%
%localappdata%
%programfiles%
%programfiles%
%programdata(x86)%
%userprofile%
%temp%
```
> Folder plugin: handle environment string paths

- Plugins/Flow.Launcher.Plugin.Folder/Main.cs
Like discussed with @JohnTheGr8, this adds functionality to his added feature to load and use environment variables from Flow. It loads them dynamically from the system, which also includes user-defined variables.
Addition to #20
> Load environment variables from system

- Flow.Launcher.Infrastructure/KeyConstant.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Converters/OpenResultHotkeyVisibilityConverter.cs
- Flow.Launcher/Converters/OrdinalConverter.cs
- Flow.Launcher/Languages/da.xaml
- Flow.Launcher/Languages/de.xaml
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Languages/fr.xaml
- Flow.Launcher/Languages/it.xaml
- Flow.Launcher/Languages/ja.xaml
- Flow.Launcher/Languages/ko.xaml
- Flow.Launcher/Languages/nb-NO.xaml
- Flow.Launcher/Languages/nl.xaml
- Flow.Launcher/Languages/pl.xaml
- Flow.Launcher/Languages/pt-br.xaml
- Flow.Launcher/Languages/ru.xaml
- Flow.Launcher/Languages/sk.xaml
- Flow.Launcher/Languages/sr.xaml
- Flow.Launcher/Languages/tr.xaml
- Flow.Launcher/Languages/uk-UA.xaml
- Flow.Launcher/Languages/zh-cn.xaml
- Flow.Launcher/Languages/zh-tw.xaml
- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultViewModel.cs
- Flow.Launcher/ViewModel/ResultsViewModel.cs
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
* Adding the ability to set custom modifiers in settings
* as a result user see this
* in the future we might show the exact hotkey on the list (instead of _Mod+<num>_ . I haven't added it right now because it's a bit more complex and I wanted to get feedback from the users whether it doesn't make it too cluttered. 
* alternatively we could step back and take a more minimalistic approach and display just the number
> Enhance modifier + num launching

- Flow.Launcher/Flow.Launcher.csproj
- Scripts/post_build.ps1
Fixes #38 - the recursive copying of theme files from the build script was causing the issue...
> Update how theme files are copied to output folder

- README.md
Update build badge to AppVeypr pointing to dev branch
> Update build badge to AppVeyor

- README.md
- Scripts/flowlauncher.nuspec
> Update readme and authors

- Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
Fix issue where environment variable search was not activated using Explorer plugin.
https://github.com/Flow-Launcher/Flow.Launcher/issues/71
> Fix environment variable search not showing up in Explorer

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
Update Flow.Launcher.Plugin to version 1 following the v1 release of Flow Launcher
To do:
Publish to NuGet
> Update PackageVersion to 1.0.0

- Plugins/Flow.Launcher.Plugin.Explorer/Search/EnvironmentVariables.cs
Fix environment variable search to be case insensitive
> Fix environment variable search to be case insensitive

- Flow.Launcher.Plugin/Result.cs
- Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/ViewModel/ResultViewModel.cs
- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Constants.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/DirectoryInfo/DirectoryInfoSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/FolderLinks/QuickFolderAccess.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Show path on folder results
- Add custom plugin ToolTip display on result hover over
- Show ToolTip path message for current folder result
- Open containing folder for file results on pressing ctrl + enter
Closing https://github.com/Flow-Launcher/Flow.Launcher/issues/93
> Explorer plugin enhancements

- Flow.Launcher/Themes/BlurWhite.xaml
Fix auto-suggestions font color for BlurWhite theme
> Fix auto-suggestions font color for BlurWhite theme

- Flow.Launcher.Core/Updater.cs
- Flow.Launcher/App.xaml.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
- When updating, inform user if an update is found.
- Prompt user to restart after update applied
> Add update messages to indicate progress

- Flow.Launcher.Test/Plugins/ExplorerTest.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Use ItemUrl column from index query result rather than ItemPathDisplay
Fixes #137
> Fix navigation to localized path when using Explorer plugin

- README.md
Add to readme- join the Discord community
> Add discord badge and update readme

- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
Re-PRed from https://github.com/Flow-Launcher/Flow.Launcher/pull/181. Authored by @taooceros
> Fix calculator copy error

- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
Bump version from merged PR https://github.com/Flow-Launcher/Flow.Launcher/pull/182 on Calculator copy fix.
No code changes
> Plugin Calculator version bump

- README.md
It seems there are still users who would like to use Everything as their search tool, lets make it clear for new users who would like to do the same still.
> Update readme to make it clear for Everything users

- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
Bump version for changes in #216
> version bump for Calculator & Program plugins

- README.md
> Add link to website in readme

- README.md
> Update plugin usage in README

- Flow.Launcher.Infrastructure/Constant.cs
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
Update the website url in Settings' About tab
> Update url website in Settings

- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Add downloading message for updating plugin, and a continuewith to catch the error.
> Error handling for plugin update

- Flow.Launcher/ViewModel/MainViewModel.cs
make priority score bump higher due to later discussion in #274 
Users won't know how score is produced, which means that it will be hard to let them control scoring bump.
> make priority score higher

- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
Version bump for PluginsManager for #283
> Version bump for PluginsManager

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
Version bump Flow.Launcher.Plugin & plugins from #267 update
> Version bump Flow.Launcher.Plugin

- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
> Exclude index search from special chars

- Plugins/Flow.Launcher.Plugin.Program/Main.cs
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
close #303 
Also fix an issue that progressbar hide so quick due to no await
> Auto reindex

- Flow.Launcher.Test/Plugins/ExplorerTest.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Use Window Search Order by instead of getting the result and order by filename.
> Use Window Search Orderby

- Flow.Launcher/Languages/sk.xaml
- Plugins/Flow.Launcher.Plugin.Calculator/Languages/sk.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/sk.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/sk.xaml
> Update Slovak translation

- Flow.Launcher.Core/Plugin/PluginAssemblyLoader.cs
> avoid duplicate assembly load

- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
from https://github.com/microsoft/PowerToys/pull/9124
> add e to calculator plugin, and fix a NPE for debugging

- Flow.Launcher/SettingWindow.xaml
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
fix #375 
I increase the default width. The issue is due to the added Priority option, which uses more width than expected. Also, I allow users to resize the window. I don't know why we stop user from doing it before.
> Increase the default width and allow user to resize setting window, and reduce the margin for PluginDirectory

- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/SettingsControl.xaml.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
close #431 
UX/UI IMPROVEMENTS:
- Add Column for the "Title" of the web search
- Be able to double click an entry to edit it.
- Be able to click on the column to sort by that column
> WebSearch UI Improvement

- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
- Plugins/Flow.Launcher.Plugin.Program/Programs/Win32.cs
- Plugins/Flow.Launcher.Plugin.Program/Settings.cs
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
> Implement Option to disable program description

- Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
from PT-Run https://github.com/microsoft/PowerToys/pull/10394
release Com stream Object immediately
Co-Authored-By: Andrey Nekrasov <1828123+yuyoyuppe@users.noreply.github.com>
> Avoid AppxManifest.xml leak

- Flow.Launcher.Core/Plugin/PluginsLoader.cs
Add where.exe detect python path. It's simpler and able to detect python path installed in Microsoft Store
> Use where.exe to detect pythonPath easily

- Flow.Launcher.Core/Plugin/JsonPRCModel.cs
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Flow.Launcher.Core/Resource/JsonObjectConverter.cs
> Add Customized Object Converter, fix Length issue

- README.md
Add WinGet installation instruction in readme
> Add WinGet Installation Instruction

- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
> dev branch only: Explorer plugin version bump for PR 449

- Plugins/Flow.Launcher.Plugin.Program/Programs/ShellLinkHelper.cs
#452 
Co-Authored-By: Alekhya  <28739210+alekhyareddy28@users.noreply.github.com>
> Release Unmanaged Object

- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
bump for https://github.com/Flow-Launcher/Flow.Launcher/pull/489
> version bump Shell plugin

- Scripts/post_build.ps1
> dev branch: remove createdump.exe

- Flow.Launcher.Core/Plugin/PluginManager.cs
https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/issues/9
> Check null for ContextMenu

- Plugins/Flow.Launcher.Plugin.Program/Programs/UWP.cs
> Check Empty image path to avoid exception

- Plugins/Flow.Launcher.Plugin.Program/ProgramSuffixes.xaml.cs
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
> Remove Empty Entries in ProgramSuffixes.xaml.cs

- Flow.Launcher.Core/Plugin/JsonPRCModel.cs
- Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs
- Flow.Launcher/Storage/UserSelectedRecord.cs
> JsonRPC camelCase and Case Insensitive

- appveyor.yml
> AppVeyor: Skip branch with pr

- Flow.Launcher.Test/Plugins/ExplorerTest.cs
> add comment to explain locale swap

- appveyor.yml
Publish new flow updates to WinGet repo and only on success build of master branch.
Tested on a branch only build and 1.8.0 update PR is already submitted to the WinGet repo
Close #463
> Add WinGet update CD

- Flow.Launcher/App.xaml.cs
> save setting after startup

- Flow.Launcher/MainWindow.xaml.cs
Resolve Animation not start if we hide and display the main window when the operation is still continue
> fix animation logic

- appveyor.yml
hold off merging until release
> Version bump for release 1.8.0

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
> include saving SearchPrecisionScore because it is not public before

- appveyor.yml
Version bump for 1.8.2 release
> Version bump for 1.8.2 release

- appveyor.yml
> Release version bump 1.8.3

- Plugins/Flow.Launcher.Plugin.PluginsManager/Models/PluginsManifest.cs
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
> Use CDN for PluginsManifest

- Flow.Launcher.Core/Resource/Internationalization.cs
Prepare for plugin to use resx as their localization strategy.
> change cultural info when switching language

- Flow.Launcher/SettingWindow.xaml
> Change Icon Render in plugin /  plugin store

- Flow.Launcher/Notification.cs
> [dev] NotificationVersion

- Flow.Launcher/ActionKeywords.xaml
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Languages/ko.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/PriorityChangeWindow.xaml
- Flow.Launcher/SelectFileManagerWindow.xaml
- Flow.Launcher/SettingWindow.xaml
- Update Korean Translation
- Change Hardcoded text to string in plugin information (author, website, version)
- Remove Dark mode Tip String
- Add Accent color to button (OK, done) in popups & Adjust Button Width Size
- Add game mode menu (in tray) tooltip and string
> [dev] Update Korean translation / Change Hardcoded text to string / Add some button colors

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Languages/ko.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/SettingWindow.xaml
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
- Rename Dark Mode to Color Scheme
- Change Moon Icon to Sun
> [dev] Rename DarkMode Label to Color Scheme

- Flow.Launcher/SettingWindow.xaml
Fix overlapping of scrollbar and resize area
> Fix overlapping of scrollbar and resize area

- Plugins/Flow.Launcher.Plugin.WindowsSettings/Helper/ContextMenuHelper.cs
> Remove contextmenu of windowsseting plugin

- Flow.Launcher/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/en.xaml
> Correct the typo (private, bookmark)

- Flow.Launcher/SelectBrowserWindow.xaml
> Use Dynamic resource for NewTab & NewWindow

- Flow.Launcher.Core/Plugin/ExecutablePlugin.cs
Fix typescript plugin request
Tested with https://github.com/Flow-Launcher/Flow.Launcher.Plugin.HelloWorldNodeJS, both main.ts and main.js
> Fix typescript plugin request

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/ViewModel/MainViewModel.cs
See @onesounds comment below: https://github.com/Flow-Launcher/Flow.Launcher/pull/911#issuecomment-996713960
> Plugin activation icon

- Flow.Launcher/ViewModel/MainViewModel.cs
> use resources for raising top most success message

- Flow.Launcher/Languages/da.xaml
- Flow.Launcher/Languages/de.xaml
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/Languages/fr.xaml
- Flow.Launcher/Languages/it.xaml
- Flow.Launcher/Languages/ja.xaml
- Flow.Launcher/Languages/ko.xaml
- Flow.Launcher/Languages/nb-NO.xaml
- Flow.Launcher/Languages/nl.xaml
- Flow.Launcher/Languages/pl.xaml
- Flow.Launcher/Languages/pt-br.xaml
- Flow.Launcher/Languages/pt-pt.xaml
- Flow.Launcher/Languages/ru.xaml
- Flow.Launcher/Languages/sk.xaml
- Flow.Launcher/Languages/sr.xaml
- Flow.Launcher/Languages/tr.xaml
- Flow.Launcher/Languages/uk-UA.xaml
- Flow.Launcher/Languages/zh-cn.xaml
- Flow.Launcher/Languages/zh-tw.xaml
- Plugins/Flow.Launcher.Plugin.ControlPanel/Languages/ko.xaml
- Plugins/Flow.Launcher.Plugin.WebSearch/Settings.cs
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/setting.json
Small fix to spellings I noticed while trying out this program!
- "upadte" --> "update"
- "Windows Setting" --> "Windows Settings"
> Fix spellings in translation keys

- Flow.Launcher/Flow.Launcher.csproj
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/Notification.cs
> Use Microsoft Package to handle toast notification for registry 

- Flow.Launcher/ViewModel/MainViewModel.cs
Open plugin website from context menu
Close #990
> Open plugin website from context menu

- appveyor.yml
Should not be any additional changes except for the version bump, all the released changes were cherry picked from dev.
> [Dev] Merge 1.9.2 changes back into dev

- appveyor.yml
No changes just merging 1.9.3 release back into dev, which only bumps the version.
> [Dev] Merge back release 1.9.3 into Dev

- Flow.Launcher.Core/Resource/AvailableLanguages.cs
Add Spanish and Spanish Latin America to language selection
> Add Spanish and Spanish Latin America to language selection

- README.md
Add choco install cmd to readme
> Add choco install cmd to readme

- Flow.Launcher/ViewModel/MainViewModel.cs
> fix RemoveOldQueryResults NullPointerException

- Flow.Launcher/SettingWindow.xaml
> Fix plugin info not displayed when it has multiple actionkeywords

- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
- README.md
Remove unreleased feature
#1411
> [DEV] Remove unreleased feature from readme

- appveyor.yml
Update dev with release 1.9.5 changes
> [Dev] Merge release 1.9.5 into Dev

- Flow.Launcher/MainWindow.xaml.cs
Remove Async and DispatcherPriorty
**What's the PR**
- Fix Progress bar exception when type korean hurry
> Fixed Progressbar Dispatcher Exception

- Flow.Launcher.Core/Updater.cs
- README.md
Update readme explaning prs and milestones
> Update readme explaning prs and milestones

- Flow.Launcher/CustomShortcutSetting.xaml
- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
\t and space are mixed in .xaml files somehow.
> Fix mixed usage of \t and space in Shortcut branch

- Flow.Launcher/Languages/en.xaml
> [Dev] Update wording

- Flow.Launcher/Languages/en.xaml
Text for uninstall button in plugin list is missing somehow.
> [dev] Fix missing text

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/Flow.Launcher.Plugin.BrowserBookmark.csproj
revert `d7f966e4865cdab6a5de83f364c969eeb92f5fb9` in #1534 and fix deleting folder issue.
> [dev] Fix bookmark sql dependency issue

- Flow.Launcher/SettingWindow.xaml
Fix Freezing in plugin list.  This is a one-line code, and I apply it because the problem persists. (And it was confirmed that there was no particular impact on the memory.) If @taooceros want to modify, make new pr.
> Fix freezing in Plugin list

- Flow.Launcher/Languages/en.xaml
Change to "plugin" for consistency.
> Change spell of word "plug-in"

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
- Flow.Launcher/ResultListBox.xaml
- Flow.Launcher/ResultListBox.xaml.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/ResultsViewModel.cs
fix #1542 and tooltip not displayed
> Fix right click & tooltip

- Flow.Launcher/ViewModel/MainViewModel.cs
Refactor with source generator (hopefully solve the nullreference issue in #1558)
Also fix results modifier not working
Tested (debug mode):
> [Dev] Refactor KeyBinding Commands

- Flow.Launcher.Core/Resource/Internationalization.cs
- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
- Flow.Launcher/ViewModel/MainViewModel.cs
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
Fix main window creating a new `CultureInfo` object every second in clock/date update code.
Tests
> [Dev] Fix new culture info

- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- for slow query on 1st flow start up
- History: * -> ws (Window Service Plugin already use) -> s
> Change Windows Settings plugin Keyword to s from *

- Flow.Launcher/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Program/Languages/en.xaml
> [Dev] Fix typos in source string

- Flow.Launcher/ResultListBox.xaml.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
> [Dev] Fix Drag and Drop causing windows hang

- Flow.Launcher/ResultListBox.xaml.cs
> [Dev] fix null reference when clicking on Set Item to Top or plugin website

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
Bump plugin versions after .Net 6 upgrade
> [Dev] Bump plugin versions after .Net 6 upgrade

- Plugins/Flow.Launcher.Plugin.Program/Views/ProgramSetting.xaml
Fixed an issue where the button height was small and the letters were slightly truncated in some languages.
> Fix Program Plugin Buttons Size

- Flow.Launcher.Test/Plugins/ExplorerTest.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/SearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/QueryConstructor.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndex.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/WindowsIndexSearchManager.cs
Adds exception handling when Windows Search service used by Windows Index Search engine is not running or disabled.
Close https://github.com/Flow-Launcher/Flow.Launcher/issues/1628 
close #1668
close #1666
close #1665
close #1663
close #1631
close #1630
> Add exception handling when Windows Search service not available

- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
> Fix item can't be unselected after editing shortcut

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
> fix a typo

- Plugins/Flow.Launcher.Plugin.WebSearch/Languages/ko.xaml
hotfix. it will bee made error.
> Remove Duplicated Key (Korean)

- Plugins/Flow.Launcher.Plugin.WindowsSettings/WindowsSettings.json
Close #1718 - Command updated for `CreateAndFormatHardDiskPartitions` in WindowsSettings plugin.
> WindowsSettings plugin - command updated for diskmgmt

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
Close https://github.com/Flow-Launcher/Flow.Launcher/issues/1720
> Update Explorer plugin description

- Plugins/Flow.Launcher.Plugin.Sys/Languages/da.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/fr.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/it.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/ja.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/ko.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/nl.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/pl.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-br.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-pt.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/ru.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/sr.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/tr.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/uk-UA.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-tw.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
Add a prompt for the **Log Off command** _(System commands plugin)_ which prevents users from accidentally logging off from their system.
> Add prompt for Log Off command

- README.md
> Add sponsor to readme

- Flow.Launcher/PriorityChangeWindow.xaml
- Resolve https://github.com/Flow-Launcher/Flow.Launcher/issues/1822
- Add Minimum value (-100) / Maximum Value (100)
- It works fine even if you use a value other than -100 to 100. (Exist Value)
> Add Maximum/Minimum Priority Value 

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
> Version bumps for release 1.12.0

- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
> Use File.Move when the setting file does not exists

- appveyor.yml
Version bump for 1.12.1 release
> Version bump for 1.12.1 release

- Flow.Launcher.Infrastructure/Storage/JsonStorage.cs
fix #1853 
Note:
- It's too late for me to create a comprehensive test, but I believe it shall work. If anyone would like to give it a test, thank you so much!
> Fix Error of loading backup when original file doesn't exists

- Plugins/Flow.Launcher.Plugin.PluginsManager/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
Closes #1189. Forget to create a PR. It was done months ago.
Tests:
- Plugin name shows on the install success notification.
> Show plugin names in download success notification

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
Bump versions for .Net upgrade and release
> Release version bumps

- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
> Fix Dark Text Color in Everything Panel

- README.md
> Fix Wikipedia typo in readme

- Flow.Launcher/SettingWindow.xaml
> Add Theme Section Title

- Flow.Launcher/MainWindow.xaml.cs
**What's the PR**
- Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/1944
- Resolve the issue of no sound for some users.
- For the existing media player class, it uses the WindowsMediaPlayer that your system uses. My guess is that if there is a problem with the Windows Media Player on your system, it won't play in Flow either. I changed that code to a class called SoundPlayer.
> Fix the sound issue

- .github/actions/spelling/expect.txt
- .github/actions/spelling/patterns.txt
- Flow.Launcher/Notification.cs
- Flow.Launcher/PublicAPIInstance.cs
- appveyor.yml
Release Notes
=========
- Fix Windows 11 22H2 (22621) notification error #2073
- Fix main thread issue of LegacyShow() #2073
> Release 1.14.1

- appveyor.yml
Merging the v1.14.1 release back into dev, essentially bumping the version in dev.
> Merge release 1.14.1 back into Dev

- appveyor.yml
> Update AppVeyor NuGet API

- Flow.Launcher/Helper/AutoStartup.cs
Related to #2000 and #2131. It doesn't actually fix these issues.
> Add quotes surrounding auto startup entry

- .github/actions/spelling/expect.txt
- Flow.Launcher.Core/Resource/AvailableLanguages.cs
> Add Czech and Arabic Language Support

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
> Bump versions for release

- Flow.Launcher.Core/Resource/AvailableLanguages.cs
> Fix name of Slovak language

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
> Bump plugin versions

- appveyor.yml
Release 1.16.1 version bump patch
> Release 1.16.1 version bump

- README.md
addition to #2350
Use relative path in case we want to edit it in the future
> Update README.md for custom shortcut

- Flow.Launcher/Converters/BoolToVisibilityConverter.cs
- Flow.Launcher/MainWindow.xaml
- Fix the issue resizable while preview turned off
- Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/2289
- It should not be resizable when preview is off.
> Fix the issue resizable while preview turned off

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
Bump version for main and plugin projects
> Release 1.16.2 version bump

- .github/workflows/spelling.yml
Fix the error introduced in spell check v0.0.22. See ![here](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.22).
> Fix spell check extra dict missing error

- Flow.Launcher.Infrastructure/Flow.Launcher.Infrastructure.csproj
Reverts Flow-Launcher/Flow.Launcher#2434
When trying to install a local build of Flow of dev branch the following error occurs. Flow crashes when starting. After reverting `f7f0d40` everything is fine.
```
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\^^$%^%\AppData\Roaming\FlowLauncher\Logs\1.0.0\2023-11-25.txt
2. copy below exception message
Flow Launcher version: 1.0.0
OS Version: 19045.3636
x64: True
Python Path: D:\Program Files\Python311\pythonw.exe
Node Path: C:\Users\^^$%^%\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 11/25/2023 00:53:02
Exception:
System.PlatformNotSupportedException: SystemEvents is not supported on this platform.
at …
```
> Revert "Bump System.Drawing.Common from 7.0.0 to 8.0.0"

- .github/actions/spelling/expect.txt
- .github/actions/spelling/patterns.txt
- .github/workflows/spelling.yml
Fix the broken spell check workflow by using the pre-release version of spell check and with some small fixes.
Ref: https://github.com/check-spelling/check-spelling/issues/59
> Fix spell check

- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
> Add "Sign Out" as an alias for "Log Off"

- Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs
- Flow.Launcher/PublicAPIInstance.cs
- Plugins/Flow.Launcher.Plugin.Sys/Languages/ar.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/cs.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/da.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/de.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/es-419.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/es.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/fr.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/it.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/ja.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/ko.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/nb.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/nl.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/pl.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-br.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/pt-pt.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/ru.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/sk.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/sr.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/tr.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/uk-UA.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-cn.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Languages/zh-tw.xaml
- Plugins/Flow.Launcher.Plugin.Sys/Main.cs
- README.md
- New methods added to Plugin API (`ToggleGameMode`, `SetGameMode`, `IsGameModeOn`)
- `Toggle Game Mode` added to sys plugin
- Left a note about it in ReadMe
> Add ToggleGameMode to system commands

- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
Found in https://github.com/FlorianRappl/Mages/blob/devel/doc/functions.md
Added `factorial`, `sign`, `isprime`, `isinfty`.
> [Calculator] Allow more functions to be used

- README.md
> Update system commands in README

- Plugins/Flow.Launcher.Plugin.Calculator/Main.cs
New operators added
- Remainder (`%`)
- Comparison (`>`, `<`, `>=`, `<=`)
> [Calculator] Add comparison operators & remainder

- Plugins/Flow.Launcher.Plugin.Explorer/ContextMenu.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
This PR closes #2327
I am open to hearing your suggestions. Maybe the icon needs to be changed if there is a more suitable one
I have added a new option in the context menu, so that the "open with" dialog of windows is called
Add new option to context menu for files
> feat: Add open with option for files in context menu

- README.md
Fixes #2300 
Thanks for the heads up @HorridModz
> Remove redundant wording

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
> Bump versions for release 1.17.0

- Flow.Launcher/MainWindow.xaml
- Flow.Launcher/MainWindow.xaml.cs
* Clipboard clears previous text in query when paste is used
* Prepend clipboard text to current query
> Prepend clipboard to query

- Flow.Launcher/Converters/BoolToIMEConversionModeConverter.cs
- Flow.Launcher/Converters/BoolToVisibilityConverter.cs
- Flow.Launcher/Converters/BorderClipConverter.cs
- Flow.Launcher/Converters/HighlightTextConverter.cs
- Flow.Launcher/Converters/IconRadiusConverter.cs
- Flow.Launcher/Converters/OpenResultHotkeyVisibilityConverter.cs
- Flow.Launcher/Converters/OrdinalConverter.cs
- Flow.Launcher/Converters/QuerySuggestionBoxConverter.cs
- Flow.Launcher/Converters/StringToKeyBindingConverter.cs
- Flow.Launcher/Converters/TextConverter.cs
First tiny portion of changes, only from the `Flow.Launcher/Converters` folder, to receive first feedback and learn more about what and how I should do.
> Code cleanup: Flow.Launcher/Converters

- Flow.Launcher/Languages/en.xaml
- Flow.Launcher/SettingWindow.xaml
- Change Item order to PREV/NEXT from NEXT/PREV (page, item)
- Change the label string "Quick Adjust Window Width Size" to "Quick Adjust Window Width" (with Height)
> Fix Icon Position in PREV/NEXT page hotkey

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- README.md
- Improved readme file
- Add a sentence as summary.
- Merge "New Features" to "Features".
- Reorganized installation section so winget/scoop/choco users can copy commands easier.
- Add supported languages list.
- Fix incorrect hotkeys.
- Add default hotkey for prev / next page
> Improve readme

- Flow.Launcher.Infrastructure/UserSettings/Settings.cs
- Flow.Launcher/SettingWindow.xaml.cs
- Flow.Launcher/ViewModel/SettingWindowViewModel.cs
> Fix Setting Window Centering Logic when First Launch

- Flow.Launcher.Infrastructure/Storage/BinaryStorage.cs
> Suppress Binary Storage Exception

- Flow.Launcher/SettingWindow.xaml
- Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/2759 
- Hotkey / Plugin -> Hotkeys / Plugins in Sidebar
> Change Sidebar Menu String

- Plugins/Flow.Launcher.Plugin.PluginsManager/Views/PluginsManagerSettings.xaml
- Fix wrong text wrap (by margin and width.)
Before
After
> Fix Plugin Manager Setting Panel

- Flow.Launcher/Themes/Win11Light.xaml
Fix result right margin mismatch in windows11 theme.
> Fix Win11 Theme's Right Margin

- Plugins/Flow.Launcher.Plugin.Explorer/Languages/en.xaml
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/Everything/EverythingSearchOption.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Settings.cs
- Plugins/Flow.Launcher.Plugin.Explorer/Views/ExplorerSettings.xaml
- Added an option in _Explorer > Everything Settings_ to enable/disable _Run Count_ for file/folder.
fixes issue #2830
> feat: Everything Run Count option

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.ProcessKiller/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
Version bumps for release 1.19.0
> Version bumps for release 1.19.0

- Plugins/Flow.Launcher.Plugin.BrowserBookmark/plugin.json
- Plugins/Flow.Launcher.Plugin.Calculator/plugin.json
- Plugins/Flow.Launcher.Plugin.Explorer/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginIndicator/plugin.json
- Plugins/Flow.Launcher.Plugin.PluginsManager/plugin.json
- Plugins/Flow.Launcher.Plugin.Program/plugin.json
- Plugins/Flow.Launcher.Plugin.Shell/plugin.json
- Plugins/Flow.Launcher.Plugin.Sys/plugin.json
- Plugins/Flow.Launcher.Plugin.Url/plugin.json
- Plugins/Flow.Launcher.Plugin.WebSearch/plugin.json
- Plugins/Flow.Launcher.Plugin.WindowsSettings/plugin.json
- appveyor.yml
> Version bump 1.19.4 release

- Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs
> Fix null reference exception when checking source

- Flow.Launcher/Flow.Launcher.csproj
> Use official Task Scheduler

- Flow.Launcher/SettingPages/Views/SettingsPaneGeneral.xaml
> Ungroup Item in general page

- .github/workflows/website_deploy.yml
GitHub action to deploy website on each release.
For https://github.com/Flow-Launcher/flow-launcher.github.io/pull/45
> Deploy website on release

- Plugins/Flow.Launcher.Plugin.PluginsManager/Settings.cs
> Disable auto restart after plugin install by default

- Flow.Launcher.Plugin/Flow.Launcher.Plugin.csproj
- appveyor.yml
Merging release v1.20.1 back to dev
> Merge release v1.20.1 back to dev

- Flow.Launcher/ReleaseNotesWindow.xaml.cs
- Fix #3775 
- Add Separator and margin in release note
> Add Separator and margin in release note
